WeblateOrg/weblate

docs/vcs.rst
This is merely taken from the Debian package release notes, it just incorporates the actual error message (so that it can be searched for) and adjusts configuration file location.
=> docs: Describe RSA keys weakness

docs/changes.rst, weblate/accounts/forms.py, weblate/templates/accounts/add-mail.html, weblate/templates/accounts/email.html, weblate/templates/accounts/profile.html
- use radio instead of select to make all choices directly visible (there won't be much of them)
- clarify how each e-mail address is used (fixes #10352)
- add shared text about e-mail verification
- rename "add e-mail" to "verify e-mail" as that better describes what it does
Screenshot:
=> profile: Improve e-mail configuration

docs/changes.rst, weblate/trans/models/suggestion.py, weblate/trans/views/edit.py
This makes it behave consistent with translating.
Fixes WEBLATE-58R
=> suggestions: apply autofixes

weblate/trans/tests/test_widgets.py, weblate/utils/stats.py
* avoid ensuring data is loaded on each `store()` invocation
* avoid using `__getattr__` on aggregating as it has some expensive checks we do not need here
=> stats: improve aggregating performance

weblate/utils/stats.py
This performs 3 times better than conditional sums in the database. Most likely PostgreSQL is unable to reuse calculated fields within conditional sum.
=> stats: calculate translation stats in Python

weblate/trans/models/unit.py, weblate/utils/stats.py
We only need selected values and this makes the code simpler than dealing with dict with results.
=> stats: use values_list to fetch values

docs/changes.rst, weblate/trans/models/category.py, weblate/trans/tests/test_categories.py
Otherwise the repo does not match linked component.
Fixes WEBLATE-58K
=> category: update linked component repos upon organizing

weblate/utils/stats.py
This has about the same performance as previous code, but is easier to read.
=> stats: use comprehensions and sum/len to aggregate

docs/admin/addons.rst, docs/changes.rst, weblate/addons/forms.py, weblate/addons/gettext.py
=> add-ons: generate MO can optionally include strings needing editing

docs/changes.rst, weblate/machinery/views.py
Otherwise the results are not properly highlighted.
=> machinery: produce same results for search as for translate

docs/changes.rst, weblate/accounts/middleware.py, weblate/accounts/models.py, weblate/trans/views/basic.py, weblate/trans/views/dashboard.py, weblate/trans/views/js.py
This shows more prominently translations user understands.
Fixes #8937
=> accounts: use accepted languages from http headers as fallback for ordering

docs/changes.rst, docs/user/checks.rst, weblate/checks/markup.py, weblate/trans/autofixes/html.py, weblate/trans/tests/test_autofix.py, weblate/utils/html.py
- nh3 (amonia) espaces it while bleech did not what causes regressions
- make both autofix and check share same sanitizer code
=> autofix: allow non-breaking space character

weblate/formats/base.py
All Weblate built in definitions are POSIX style, but user definitions or aliases can bring in anything, so do the real conversion here.
Fixes #10395
=> formats: add real conversion to POSIX style

weblate/trans/models/__init__.py, weblate/utils/stats.py
- delete no longer needed stats as they would expire in a long time
- collect list of parents to update before actual removal
Fixes WEBLATE-5AE
=> stats: improve stats cleanup on removal

docs/admin/install.rst, docs/changes.rst, requirements.txt
This is needed for Python 3.12 support.
Fixes #10361
=> deps: increase minimal Celery version

weblate/trans/tests/test_search.py, weblate/trans/views/edit.py
This makes the search input back visible.
Fixes #10430
=> edit: redirect to search tab for empty results

weblate/addons/base.py, weblate/addons/cleanup.py, weblate/addons/gettext.py, weblate/formats/base.py, weblate/trans/tests/test_edit.py
Without that, we might miss some of the updates.
=> addons: update translation revision

.github/workflows/test.yml
=> ci: Add tests for import_demo command

weblate/machinery/base.py, weblate/machinery/deepl.py, weblate/machinery/tests.py, weblate/trans/models/project.py, weblate/utils/hash.py, weblate/utils/tests/test_hash.py
The configuration can heavily influence output. Different URLs will use different servers, different API keys might use differently tweaked models, and there are also parameters directly changing output (like DeepL formality or upcoming OpenAI personas).
=> machinery: include configuration in cache key

docs/admin/install.rst, docs/admin/machine.rst, docs/changes.rst, docs/conf.py, requirements-optional.txt, requirements-test.txt, weblate/machinery/base.py, weblate/machinery/deepl.py, weblate/machinery/forms.py, weblate/machinery/models.py, weblate/machinery/openai.py, weblate/machinery/tests.py, weblate/trans/models/project.py, weblate/utils/hash.py, weblate/utils/tests/test_hash.py
- supports model selection
- supports persona customization
- prepared for glossary integration
Fixes #9009
=> machinery: add OpenAI support

weblate/trans/views/settings.py, weblate/utils/stats.py
- Avoid dict based deduplication
- Generate list without a duplicates directly
- Use iterator to free no longer needed stat objects
=> stats: optimize stats generating

docs/changes.rst, weblate/utils/stats.py
These lists are never used again in the same scope, so caching them only consumes memory without a use case.
See #10473
=> stats: avoid using cached properties for child objects

weblate/utils/stats.py
Aggregate processed timestamp instead of using current one. Without that, some updates might have been missed when aggregation takes long and translation stats are updated.
=> stats: aggregate timestamp

weblate/memory/models.py, weblate/utils/db.py
It is used for translation memory queries, but the thresholds was changed on the default connection.
=> db: correctly adjust similarity on memory_db connection

weblate/trans/autotranslate.py
=> auto-translate: add more verbose logging

weblate/accounts/captcha.py, weblate/accounts/pipeline.py, weblate/machinery/netease.py, weblate/trans/tasks.py, weblate/trans/views/edit.py, weblate/utils/checks.py, weblate/utils/stats.py, weblate/utils/tasks.py, weblate/utils/tests/test_checks.py, weblate/wladmin/middleware.py
There is guaranteed starting point, so the time can go backwards between process invocations or system reboots.
Fixes #10473
=> chore: avoid using monotonic for actual timestamps

weblate/templates/translate.html
=> translate: always show read-only reason

weblate/trans/models/project.py, weblate/trans/models/unit.py
It is typically needed several times during machine translation, so avoid fetching it repeatedly.
=> project: cache Automatically translated label

weblate/trans/models/project.py
It will be needed for glossary integartion (see #7086).
=> machinery: include actual project in machinery settings

weblate/api/tests.py, weblate/formats/base.py, weblate/formats/ttkit.py, weblate/trans/models/translation.py
Otherwise user ends up with plural that disappears upon save.
Fixes #10498
=> api: validate whether format supports plural before adding one

weblate/utils/stats.py
These were missing for some time so these were never updated.
Fixes #10508
=> stats: add update for CategoryLanguageStats

docs/changes.rst, weblate/trans/tasks.py, weblate/utils/views.py
- parse full path instead of just component name
- look for repo dirs only
- remove directories for no longer existing projects or categories
-
=> trans: Improve repository cleanup

docs/changes.rst, docs/user/checks.rst, weblate/checks/chars.py, weblate/trans/autofixes/chars.py, weblate/trans/models/_conf.py, weblate/trans/tests/test_autofix.py
=> fixups: add punctuation spacing fixup

weblate/templates/matrix.html, weblate/trans/views/source.py
This makes the error handling more straightforward.
=> matrix: Use form validation for js backend as well

docs/changes.rst, weblate/machinery/base.py, weblate/machinery/deepl.py, weblate/machinery/googlev3.py, weblate/machinery/tests.py
Utilize HTML mode and wrap placeables and newlines in a non-translatable HTML tags. This also makes the XML escaping logic shared between DeepL and Google backends.
Fixes #10145
=> machinery: Improve Google Advanced handling of placeables and newlines

ci/pip-install, weblate/checks/tests/test_checks.py
=> Add support for Django 5.0

weblate/trans/forms.py, weblate/trans/tests/test_search.py, weblate/trans/views/basic.py, weblate/trans/views/edit.py
This makes the search query be again present, see #10430.
=> search: preserve URL passed query

weblate/trans/models/component.py
This way we commit most of the files even if the main component is broken.
=> component: commit linked components in case main has missing template

docs/changes.rst, weblate/gitexport/tests.py, weblate/gitexport/views.py
This avoids buffering the git objects several times in the memory.
=> git-exporter: use streaming response to send response from git

weblate/trans/models/component.py
This avoids collecting info we will not use on bilingual translations.
=> component: collect hash update needing translations only when needed

weblate/addons/cleanup.py
The hash should not be stored in update_translation path as that one is executed before parsing possibly updated files.
Fixes #10595
=> add-ons: fix cleanup missing some translation updates

weblate/trans/models/component.py
Otherwise the add-ons would not be applied on these.
See #10392
=> component: emit store_post_load for template and intermediate file

weblate/api/serializers.py, weblate/trans/views/create.py, weblate/utils/views.py
There is no reason to reimplement validation logic just for the API.
Fixes #10608
=> api: Use shared component uniqueness validation

weblate/trans/views/search.py
Fix `limited` so the notice that only the first 250 matches are affected is shown.
=> search: fix replacement limit notice

weblate/trans/autotranslate.py
The original code could have added a suggestion to strings which already had one in case it had the same source string as another.
=> auto-translate: properly filter units to add suggestions to

weblate/trans/backups.py
Otherwise we might end up importing component with a VCS that is not supported, see #10536.
=> projectbackup: Validate VCS of restored components

docs/changes.rst, weblate/auth/management/commands/createadmin.py
- log which users are matching
- log which user is to be updated
- useful for Docker setup, where user has no clue how this is executed, see #10625
=> createadmin: provide more useful error messages

docs/changes.rst, weblate/addons/forms.py, weblate/templates/addons/discovery_preview.html, weblate/trans/discovery.py, weblate/trans/tests/test_discovery.py
This makes it more obvious why certain components could not be created.
Fixes #10515
=> discovery: report skipped entries

docs/changes.rst, docs/formats/moko.rst, weblate/formats/models.py, weblate/formats/ttkit.py
Depends on https://github.com/translate/translate/pull/5146
=> formats: Add Mobile Kotlin support

docs/admin/continuous.rst, docs/changes.rst
=> Various language fixes

docs/changes.rst, docs/formats/formatjs.rst, weblate/formats/models.py, weblate/formats/ttkit.py
Depends on https://github.com/translate/translate/pull/5162
Fixes #8802
=> formats: Add Format.JS support

weblate/accounts/views.py, weblate/lang/views.py, weblate/trans/feeds.py, weblate/trans/models/change.py, weblate/trans/views/basic.py, weblate/trans/views/edit.py, weblate/trans/views/js.py
This utilizes server side cursors on PostgreSQL which performs better on fetching only a small portion of the results.
See https://github.com/WeblateOrg/weblate/discussions/10723
=> changes: Utilize iterator() to fetch recent changes

weblate/accounts/tasks.py
This makes it easier to debug issues with third-party e-mail servers.
=> accounts: log SMTP DATA result

docs/changes.rst, weblate/machinery/libretranslate.py
This improves performance when translating multiple strings.
=> machinery: Support batch mode for LibreTranslate

weblate/accounts/tests/test_notifications.py, weblate/addons/models.py, weblate/auth/forms.py, weblate/trans/forms.py, weblate/trans/models/alert.py, weblate/trans/models/category.py, weblate/trans/models/comment.py, weblate/trans/models/component.py, weblate/trans/models/project.py, weblate/trans/models/suggestion.py, weblate/trans/models/translation.py, weblate/trans/models/unit.py, weblate/trans/tasks.py, weblate/trans/views/acl.py, weblate/trans/views/basic.py, weblate/trans/views/hooks.py
This makes the code shorter and easier to read.
=> chore: use change_set to create related change object

weblate/auth/data.py
These are typically needed together, so it makes no sense to not include locking in repository management.
See #10750
=> auth: Include locking permission in the "Manage repository" role

docs/changes.rst, weblate/trans/models/component.py, weblate/trans/tasks.py
The age was decided based on the most recent change while it should look for the oldest one.
Fixes #10754
=> component: fix commit pending by age

weblate/trans/models/translation.py
This makes upload behavior consistent with what git stored files do.
Related to #10763
=> translation: trigger store_post_load for uploaded content

weblate/addons/gettext.py, weblate/trans/models/component.py, weblate/trans/models/translation.py
- makes the code easier to read
- prepares for future project/global scoped add-ons
=> addons: add component method to get an add-on

weblate/formats/ttkit.py
Generate the list at once including all the parts directly.
=> formats: simplify msgmerge command generating

docs/changes.rst, weblate/static/editor/full.js, weblate/static/loader-bootstrap.js, weblate/static/prism-weblatesearch.js, weblate/static/style-bootstrap.css, weblate/templates/base.html, weblate/utils/forms.py
This makes it easier to realize how the search will be interpreted.
Fixes #9728
=> ui: add syntax highlighting to search input

weblate/addons/autotranslate.py, weblate/addons/base.py, weblate/addons/cdn.py, weblate/addons/cleanup.py, weblate/addons/consistency.py, weblate/addons/discovery.py, weblate/addons/events.py, weblate/addons/example.py, weblate/addons/example_pre.py, weblate/addons/flags.py, weblate/addons/generate.py, weblate/addons/gettext.py, weblate/addons/git.py, weblate/addons/management/commands/list_addons.py, weblate/addons/migrations/0001_squashed_weblate_5.py, weblate/addons/models.py, weblate/addons/properties.py, weblate/addons/removal.py, weblate/addons/tasks.py
This makes it easier to use and avoids defining various mappings.
See #10172
=> addons: use enum to define events

weblate/addons/models.py, weblate/addons/tasks.py
Add generic handle_addon_event which includes all the logic and all the signal handlers just call this. This heavily reduces code duplication and makes the implementation consistent in all invocations. The new code is also more robust and provides a better logging.
Fixes #10172
Builds on #10806
=> add-ons: Refactor signals handling

weblate/formats/auto.py, weblate/formats/base.py, weblate/formats/tests/test_external.py, weblate/formats/tests/test_formats.py, weblate/trans/models/component.py, weblate/trans/models/translation.py
It is used in auto format tests only for years, so there is no need to maintain additional abstraction layer just for that. The uploader uses try_load instead, so do that in the tests as well.
=> formats: remove parse() wrapper

weblate/trans/discovery.py, weblate/trans/tasks.py
This reduces window for creating duplicate components in a category.
Fixes WEBLATE-5S5
=> component: validate args prior creating component

weblate/glossary/forms.py, weblate/glossary/tests.py, weblate/trans/models/translation.py
Fixes #10581
Fixes WEBLATE-2NK
Fixes WEBLATE-5AM
=> glossary: skip existing entries when creating terminology

weblate/api/serializers.py, weblate/auth/permissions.py
=> permissions: provide more detailed reasoning on lack of unit.review

weblate/trans/models/change.py, weblate/trans/views/reports.py
- Avoid doing join in the Python, let the database do the hard work.
- Order credits consistently instead of randomly.
Fixes WEBLATE-5VX
=> reports: generate credits in the database

weblate/trans/models/unit.py, weblate/trans/tasks.py
Prefetch to all_checks attribute instead of using queryset.
Fixes WEBLATE-452
=> unit: improve checks prefetch

weblate/sitemaps.py, weblate/trans/models/project.py
Without that the performace is poor.
Fixes WEBLATE-41P
=> sitemap: prefetch project languages

weblate/checks/views.py, weblate/utils/db.py, weblate/utils/stats.py
This is way faster for the database to perform.
=> db: use conditional aggregation instead of expression

weblate/utils/tasks.py
This avoids issues when the database is already populated with Weblate data from the inistal setup.
Fixes #10852
=> utils: create postgresql backup to clean the database

weblate/checks/flags.py, weblate/trans/autofixes/__init__.py, weblate/trans/autofixes/base.py, weblate/trans/autofixes/chars.py, weblate/trans/autofixes/html.py, weblate/trans/autofixes/whitespace.py
Used to get list of ignore flags so that these are allowed even if the corresponding check is disabled.
Fixes #10880
=> autofix: expose related checks

weblate/formats/base.py, weblate/formats/tests/test_formats.py
The type checking discovered wrong usage of some API calls, this fixes it.
=> formats: fix find API

weblate/formats/tests/test_multi.py, weblate/trans/autotranslate.py, weblate/trans/forms.py, weblate/trans/models/suggestion.py, weblate/trans/models/translation.py, weblate/trans/tests/test_models.py, weblate/trans/tests/test_tasks.py
This is what most of the code paths already use, so make it simpler.
=> suggestions: accept only list of strings as param

weblate/checks/tests/test_checks.py, weblate/machinery/base.py, weblate/trans/models/unit.py
It is easier to understand than doing it delayed.
=> machinery: always initialize results cache dict

weblate/metrics/models.py, weblate/metrics/wrapper.py
- use cached_property instead of doing caching manually
- add type hints
=> metrics: simplify code and add type hints

.github/workflows/setup.yml, docs/admin/install.rst, docs/changes.rst, docs/contributing/release.rst, requirements-ci.txt, requirements-test.txt, scripts/create-release, scripts/extract-release-notes
Let's automate more of the release process.
=> Use workflow to perform a release

weblate/addons/base.py, weblate/addons/forms.py, weblate/auth/models.py, weblate/formats/tests/test_convert.py, weblate/formats/tests/test_exporters.py, weblate/lang/tests.py, weblate/legal/models.py, weblate/middleware.py, weblate/settings_docker.py, weblate/settings_example.py, weblate/trans/models/_conf.py, weblate/trans/models/unit.py, weblate/trans/views/edit.py, weblate/utils/apps.py, weblate/utils/inv_regex.py, weblate/utils/models.py, weblate/utils/tests/test_checks.py, weblate/utils/version.py
Slowly moving towards mypy being usable.
=> Improve type annotations

docs/Makefile, weblate/trans/tests/test_selenium.py
=> tests: Use staticfiles handler to avoid need of collectstatic

weblate/trans/models/change.py
This way it is also triggered via bulk_create and thus for events that were created during repository update. We reuse post_save emitting logic which is already present in bulk_create for the fedora messaging integration.
See #10651
=> change: use post_save signal to trigger notifications

weblate/trans/tests/test_backups.py
This makes it easier to add support for another database in case somebody wants to.
=> tests: use Django feature based tests skipping

weblate/auth/models.py, weblate/auth/utils.py
This avoids an addtional SQL query during the migration and ensures that the fetching code can not diverge from migration one.
Fixes #11025
=> auth: use migrate_groups to fetch groups

weblate/utils/django_hacks.py
=> utils: use public interface of patch instead of dunder methods

weblate/machinery/base.py, weblate/machinery/deepl.py, weblate/machinery/ibm.py, weblate/machinery/microsoft.py, weblate/machinery/modernmt.py, weblate/machinery/netease.py, weblate/machinery/saptranslationhub.py, weblate/vcs/git.py
=> chore: rely on requests to do basic HTTP auth

weblate/vcs/git.py
This makes it less likely to break.
=> vcs: make additional request kwargs kwargs-only

weblate/auth/models.py, weblate/auth/permissions.py
Added mypy hints and fix errors it discovered.
=> auth: add type hints and fix errors

docs/contributing/addons.rst, weblate/addons/base.py, weblate/addons/tests.py, weblate/addons/views.py, weblate/api/serializers.py
- add type hints to base add-on class
- remove some possibilities of passing None
- better validation error when installing invalid add-on
=> add-ons: add type hints

docs/admin/checks.rst
Mention in the admin documentation the ability to specify number of lines. This also described on https://docs.weblate.org/en/latest/user/checks.html#maximum-size-of-translation, but Weblate itself links to the admin docs and should thus be equally complete.
=> Update checks documentation for admins to mention maximum number of lines (for font check)

weblate/trans/models/alert.py, weblate/trans/models/component.py
This brings the logic to the alert instead of having a huge update_alerts method in the Component class.
=> alerts: move trigger logic to alert classes

weblate/trans/models/alert.py, weblate/trans/models/component.py
This makes the license change immediate effect on the alert.
=> component: update libre conditions alert upon saving

docs/admin/machine.rst, docs/changes.rst, weblate/machinery/apertium.py, weblate/machinery/baidu.py, weblate/machinery/base.py, weblate/machinery/deepl.py, weblate/machinery/google.py, weblate/machinery/microsoft.py, weblate/machinery/modernmt.py, weblate/machinery/mymemory.py, weblate/machinery/yandex.py, weblate/machinery/yandexv2.py, weblate/machinery/youdao.py
Add way for backends to hook into request error handling to provide more useful error messages.
Issue #11185
=> machinery: consolidate error handling

docs/contributing/start.rst
The proposed change to document the missing requirement for contributing. Discussed in issue #11094
In short, the tool `jq` was not mentioned in the documentation.
I have added an instruction to install the tool.
Fixes #11094
=> Update start.rst to document missing requirement

docs/changes.rst, weblate/utils/stats.py
We need to count these based on the language, not only on the category.
Fixes #11240
=> stats: Fixed per-language statistics on nested categories

.github/workflows/test.yml, .pre-commit-config.yaml, docs/admin/customize.rst, docs/admin/install.rst, docs/changes.rst, pyproject.toml, weblate/accounts/forms.py, weblate/addons/models.py, weblate/auth/permissions.py, weblate/formats/base.py, weblate/formats/convert.py, weblate/formats/external.py, weblate/formats/ttkit.py, weblate/formats/txt.py, weblate/lang/models.py, weblate/metrics/models.py, weblate/trans/backups.py, weblate/trans/templatetags/translations.py, weblate/trans/util.py, weblate/utils/classloader.py, weblate/utils/inv_regex.py, weblate/utils/stats.py
This also raises minimal Python version to 3.10.
=> deps: require Django 5.0

weblate/lang/models.py, weblate/utils/inv_regex.py
It is prone to errors, so enforce same lenght. Replace one zip usage with dict.fromkeys.
=> chore: do not use zip(strict=False)

docs/admin/auth.rst
Small typo on documentation: the pip specifier `>=` without quote is interpreted à a redirection and create a file.
ZSH example:
```
$ pip install django-auth-ldap>=1.3.0
zsh: 1.3.0 not found
```
=> Use quotes around pip version specifier

weblate/checks/tests/test_source_checks.py, weblate/utils/stats.py
This also changes loading logic to make it type clear.
=> stats: add type annotations

weblate/examples/git-merge-gettext-po
Move output to correct output file destination
See #11279
=> Fix merging of po files with "git merge-file".

docs/api.rst, docs/changes.rst, weblate/api/tests.py, weblate/api/views.py, weblate/auth/permissions.py
Addressing #10222 
This PR will add API endpoints for granting and revoking admin rights.
I have added tests for the endpoints.
=> Adding grant revoke admin endpoints

docs/changes.rst, weblate/lang/data.py, weblate/lang/models.py, weblate/trans/models/alert.py
This simplistic heuristics can not work there, so better to avoid it.
Fixes #11315
=> alerts: skip monolingual alert on non-whitespace languages

docs/changes.rst, weblate/checks/glossary.py
=> checks: do not use word boundary logic for languages which do not have one

docs/changes.rst, weblate/formats/base.py, weblate/formats/convert.py, weblate/formats/ttkit.py, weblate/trans/tests/test_files.py
- factor out translation presence check
- properly handle plural strings
- do not mark needs editing strings without a translation (fixes #11305)
=> formats: fix state calculation

docs/changes.rst, weblate/vcs/git.py
This will override whatever is present in the .gitreview file.
Fixes #11366
=> vcs: configure gerrit remote to match push URL

docs/changes.rst, weblate/memory/views.py, weblate/trans/forms.py, weblate/trans/management/commands/__init__.py, weblate/trans/management/commands/auto_translate.py, weblate/trans/models/component.py, weblate/utils/search.py, weblate/utils/tests/test_search.py
The code didn't properly deal with the categories in several places, this is now fixed.
=> component: consolidate filtering component by path

ci/pip-install
These are incompatible with xmlsec, see https://github.com/xmlsec/python-xmlsec/issues/316
=> ci: do not use wheels for lxml

docs/formats/appstore.rst
The "Typical Weblate component" now points to the correct default path for fastlane in Android applications
=> docs: update typical setup for appstore

.github/workflows/macos.yml, docs/admin/install/venv-macos.rst
It should be no longer needed as Python xmlsec builds just fine with recent version.
=> docs: remove workaround for xmlsec

weblate/accounts/notifications.py, weblate/accounts/tasks.py, weblate/trans/models/change.py
This reduces amount of fired tasks which would be procesed.
=> notification: emit task only in case there is handler for given event

docs/changes.rst, weblate/trans/models/unit.py
Without that the timestamp won't get updated.
=> unit: automatically include last_updated in update_fields

docs/admin/machine.rst, docs/changes.rst, weblate/machinery/forms.py, weblate/machinery/microsoft.py
=> machinery: support custom translators in Azure AI translation

docs/changes.rst, weblate/templates/translate.html, weblate/trans/models/unit.py, weblate/trans/tests/test_edit.py, weblate/trans/tests/test_search.py
=> unit: allow editing strings when source is for review

.github/workflows/macos.yml
We need fixed openssl for https://github.com/Homebrew/homebrew-core/pull/169721.
=> ci: add brew upgrade

weblate/formats/ttkit.py
Without that the newly added units might be wrongly wrapped.
Still, this doesn't fully explain behavior observed in #11032.
=> formats: include wrapper on units which need it

weblate/trans/models/component.py
There are often linked projects so we can fetch the result just once.
=> fix(component): share AsyncResult instance when prefetching tasks

docs/changes.rst, weblate/addons/tests.py, weblate/addons/views.py, weblate/auth/data.py, weblate/templates/addons/addon_list.html
Without that users can be confused that their previously installed add-ons are gone.
Fixes #11539
=> feat(add-ons): add indication of other scopes to add-on list

weblate/checks/format.py
- use different code path for counter and list based checking
- normalize strings early
- add type hints
=> chore(checks): simplify check code

docs/changes.rst, weblate/machinery/base.py, weblate/machinery/openai.py
Do not confuse it by talking about placeholders when there are none, it then tends to hallucinate and add ones.
=> fix(machinery): better handle placeholders in OpenAI

weblate/trans/backups.py, weblate/trans/forms.py
This makes type checking more usable on ProjectBackup and the code easier to read.
=> chore: avoid overriding single variable for two uses

weblate/templates/language-project.html, weblate/trans/models/announcement.py, weblate/trans/tests/test_manage.py, weblate/trans/views/basic.py, weblate/trans/views/settings.py
Add announcement form on project/language
This solves issue #11003
=> Add announcement for project/language

weblate/checks/utils.py, weblate/fonts/utils.py, weblate/formats/external.py, weblate/machinery/aws.py, weblate/machinery/openai.py, weblate/screenshots/views.py, weblate/utils/validators.py
These are not used frequently and delaying makes positive impact on startup performance and memory usage.
=> chore: delay some third-party imports

weblate/glossary/models.py, weblate/trans/views/edit.py
Unless we are rendering full sidebar, most of the data is not needed, so limit prefetching.
=> fix(glossary): fetch only needed info with glossary terms

weblate/formats/ttkit.py
Otherwise the source update upload is there and it doesn't have desired results.
=> fix(formats): remove BilingualUpdateMixin from monolingual PO files

weblate/auth/models.py, weblate/auth/permissions.py
We do these often enough to fetch permissions at once same as we do with specific permissions.
=> fix(auth): cache global permissions lookup

docs/admin/install/docker.rst
=> clarifying that it is not about purchasing but priority of the services

docs/changes.rst, weblate/formats/convert.py
The convertor does skip these by default, make this consistent with the other converted formats.
=> fix(formats): saving fuzzy strings to RC

docs/api.rst, docs/changes.rst, weblate/api/serializers.py
=> feat(api): expose last_updated for a unit

docs/changes.rst, weblate/checks/markup.py
=> fix(checks): follow XML specification for matching XML entities

weblate/formats/tests/test_formats.py, weblate/formats/ttkit.py
=> Fix bad language format for XWiki formats. fixes #11879

weblate/checks/glossary.py, weblate/checks/same.py, weblate/glossary/models.py, weblate/machinery/microsoft.py, weblate/machinery/openai.py
Only matching source strings should be included, the variants are useful for display only.
Fixes #11883
=> fix(glossary): skip variants inclusion for machinery and checks

docs/api.rst, docs/changes.rst, weblate/api/serializers.py
Expose old and details fields.
Fixes #11807
=> feat(api): include more details about changes

docs/admin/machine.rst
differentiation of Weblate and Weblate TM
=> better description of Weblate automatic suggestion sources

weblate/templates/snippets/libre-basic.html
some projects were trying to make it through with non-libre code and libre-licensed translations. Not fair, not good.
=> preventing cherrypicking by non-libre projects

weblate/trans/models/component.py, weblate/trans/views/js.py, weblate/vcs/git.py
- use push branch counts to detect whether push is needed
- use correct remote when using git merge requests
=> fix(vcs): improve counting changes in remote repo

docs/changes.rst, weblate/templates/language-project.html, weblate/templates/language.html, weblate/trans/tests/test_widgets.py, weblate/trans/views/widgets.py, weblate/trans/widgets.py, weblate/utils/stats.py, weblate/utils/views.py
Make the code consistent and show only filtered languages on multi language widgets in all cases.
Fixes #3153
Fixes #4193
=> feat(widgets): support language- and site-wide widgets

weblate/templates/category.html, weblate/trans/forms.py, weblate/trans/models/change.py, weblate/trans/tests/test_reports.py, weblate/trans/views/basic.py, weblate/trans/views/reports.py
This enables report generation from Category.
This solves issue #11739.
Example image:
=> Generate reports for Category

weblate/billing/views.py, weblate/trans/backups.py, weblate/utils/management/commands/sentry_deploy.py
=> Veracode reported issues fixes

weblate/addons/base.py, weblate/addons/models.py, weblate/addons/tests.py, weblate/checks/base.py, weblate/checks/models.py, weblate/formats/base.py, weblate/formats/exporters.py, weblate/formats/models.py, weblate/machinery/models.py, weblate/trans/autofixes/__init__.py, weblate/utils/classloader.py, weblate/utils/tests/test_classloader.py, weblate/vcs/models.py
- This makes it fail with a proper error message
- Needed some reshuffling of modules to avoid circular imports
Fixes #11976
=> feat(classloader): add type checking

weblate/templates/snippets/format-translation.html, weblate/templates/translate.html, weblate/templates/translation.html, weblate/templates/zen-units.html, weblate/trans/forms.py, weblate/trans/templatetags/translations.py, weblate/trans/tests/test_templatetags.py, weblate/trans/views/edit.py
This fixes the tabindex sequence of items as suggested on  issue #9481.
This solves issue #9481.
=> Fix tabindex sequence

weblate/middleware.py
Follow current best practices on most of the fields (we still use inline CSS, though).
=> feat(middleware): tighthten Content-Security-Policy

docs/changes.rst
=> improved point on add-ons scope

weblate/trans/forms.py, weblate/trans/templatetags/translations.py, weblate/utils/stats.py
Ongoing effort towards https://github.com/WeblateOrg/weblate/issues/3703
=> Add type annotations

weblate/formats/tests/test_formats.py
Extracted from #11937 since that one is likely going to take a while and IMO this is worth merging on its own.
The test data wasn't realistic for PHP files: It happened to work, but didn't create a correct PHP file. We fix the test fixture to have more realistic data.
=> test(format): more realistic PHP keys for test_new_unit

docs/changes.rst, weblate/addons/git.py, weblate/gitexport/migrations/0001_squashed_0002_fill_in_url.py, weblate/gitexport/models.py, weblate/gitexport/views.py, weblate/trans/forms.py, weblate/vcs/models.py
This consolidates separate lists in several places which diverged over years.
Fixes #12011
=> fix(vcs): consolidate list of git based backends

weblate/lang/models.py, weblate/middleware.py, weblate/trans/models/component.py, weblate/trans/models/project.py
The languages lookup has severe impact when peforming nearly no-op updates of huge components.
=> feat(languages): cache language lookups while updating component

weblate/auth/tests/test_utils.py, weblate/auth/utils.py, weblate/utils/tests/test_validators.py, weblate/utils/validators.py
Include the problematic e-mail address so that it is clear what went wrong.
=> fix(auth): improve error message for invalid e-mail

docs/changes.rst, weblate/machinery/openai.py, weblate/machinery/tests.py
This might be more useful than matching existing output.
=> feat(machinery): make OpenAI suggest rephrasing to translated strings

weblate/formats/txt.py
=> Support alternative fastlane filenames

docs/conf.py
See https://about.readthedocs.com/blog/2024/07/addons-by-default/ for more info.
=> docs: migrate to addons for readthedocs.org

weblate/glossary/forms.py, weblate/trans/forms.py
- share constructor for NewUnitBaseForm
- move fields patching to a separate method
- make glossary forms support plural terms
@harriebird This (among other cleanups) polishes is_source_plural logic.
=> chore(forms): consolidate constructor args

weblate/addons/base.py, weblate/addons/cdn.py, weblate/addons/cleanup.py, weblate/addons/example.py, weblate/addons/generate.py, weblate/addons/gettext.py, weblate/addons/git.py, weblate/addons/models.py, weblate/addons/properties.py, weblate/addons/scripts.py, weblate/addons/tests.py, weblate/trans/models/component.py, weblate/trans/models/translation.py
The add-ons should not store translation hash when the current translation hasn't yet been parsed like when adding new translation.
Fixes #12106
=> fix(add-ons): avoid missing some updates

weblate/static/style-bootstrap.css, weblate/templates/list-comments.html, weblate/templates/snippets/suggestions.html
The actions box no longer covers the text field under it. Also fixed spacing between the buttons inside the box.
Fixes: #8356
=> Update suggestions box

weblate/checks/format.py, weblate/checks/tests/test_format_checks.py
- look for escaped braces in the original string as well
- treat { } escapes same as with %
- remove bogus detection of % placeable
- detect any stray { } besides parsed format string
See #12198 and #12197
=> fix(checks): make python brace format more robust

weblate/addons/cleanup.py, weblate/formats/base.py
=> formats: skip cleanup if not supported

weblate/templates/last-changes-content.html
Refactor the breadcrumb element from an ordered list to an unordered list for better accessibility and styling consistency.
Closes #5464
=> Update last-changes-content.html template

.github/workflows/test.yml, .gitignore, docs/contributing/tests.rst, pyproject.toml, weblate/checks/tests/test_format_checks.py
This allows junit output to be fed into CodeCov for test analytics integration.
=> ci: add pytest support for running tests

weblate/vcs/base.py
It can happen that the child process (git) gets stuck and this should not block other operations which might be needed on the repository.
=> fix(vcs): add timeout to subprocess execution

docs/admin/install.rst, docs/admin/install/docker.rst
Add documentation for CELERY_SINGLE_PROCESS variable introduced in https://github.com/WeblateOrg/docker/pull/2420
This is the first time I am working with Sphinx and RST. I tried my best to figure out the syntax from surrounding documentation. Any feedback is highly appreciated!
I could not find any documentation on contributing to documentation. I wanted to add the list of packages I had to install on Fedora in order to be able to run `make html`. In case you are interested:  `dnf install python3-sphinx python3-sphinxcontrib-httpdomain python3-sphinx-jsonschema python3-sphinx-copybutton python3-sphinxext-opengraph python3-furo`.
=> Document CELERY_SINGLE_PROCESS environment variable

weblate/fonts/utils.py
https://github.com/python-pillow/Pillow/issues/3853 has been fixed years ago, so remove workaround for it (we depend on recent Pillow anyway for security fixes).
=> chore: remove workaround for ancient Pillow bug

.github/workflows/test.yml
As documented on https://docs.astral.sh/uv/guides/integration/github/#caching
=> feat(ci): cache uv dependencies

weblate/static/style-bootstrap.css, weblate/templates/last-changes-content.html, weblate/templates/list-comments.html
Fixed the Mobile UI overlapping in Latest Changes 
Closes: #12247
=> Fix latest changes UI overlapping in Insights

docs/admin/addons.rst, docs/changes.rst, weblate/formats/convert.py, weblate/trans/tests/test_component.py
These typically need updates of non-translation content when the base file is changed without changes in translations. See #12334 or #12123
=> feat(formats): automatically enable cleanup add-on for convert based formats

.github/workflows/codeql-analysis.yml, .github/workflows/docs.yml, .github/workflows/licenses-update.yml, .github/workflows/migrations.yml, .github/workflows/mypy.yml, .github/workflows/pylint.yml, .github/workflows/schema-update.yml, .github/workflows/setup.yml, .github/workflows/test.yml, ci/pip-install, pyproject.toml
- consolidate caching for installs and doc builds
- remove direct uv dependency
=> chore(ci): use hynek/setup-cached-uv instead of doing that manually

ci/pip-install, ci/run-migrate
- the lxml workaround was limited in edge path
- the cffi workaround should not be needed now
=> chore(ci): remove no longer needed install workarounds

docs/changes.rst, weblate/trans/models/component.py
The linked components were updated only upon commit and not on update making it likely that some updates will not be parsed.
Fixes #12275
Fixes #12365
=> fix(component): fix updating revision info in database

docs/changes.rst, weblate/accounts/models.py
This was intended in the initial implementation, but was never finished.
=> feat(accounts): remember last used second factor

weblate/addons/tests.py
This triggers warning that the test can not be collected.
=> fix(add-ons): avoid using Test for non-testcase classes

docs/changes.rst, weblate/accounts/tests/test_views.py, weblate/accounts/views.py, weblate/settings_docker.py, weblate/settings_example.py, weblate/templates/403.html, weblate/templates/about/donate.html, weblate/templates/base.html, weblate/templates/registration/logged_out.html, weblate/templates/snippets/donate.html, weblate/trans/context_processors.py, weblate/trans/tests/test_selenium.py
- avoids redirect loop with REQUIRE_LOGIN
- makes sign out work with SSOs (fixes #10159)
- brings another place to display our donate pledge
=> feat(accounts): add sign out page

weblate/templates/last-changes-content.html, weblate/templates/mail/base.html, weblate/templates/mail/digest.html, weblate/templates/mail/styles/digest.css
**Fixed the Digest Email**
Fixes to layout, responsiveness, and styling to match changes view in the app
See: #5464
**Mobile**
- I am not sure how this looks on email clients, however the changes are insured correct with `?digest=1` preview. And the styles are inline. If more testing is required please provide the steps to send a test digest email in a local setup.
- Don't mind the images not displaying. I think its just an issue with my local setup related to `Content Security Policy` as the server is running in **wsl** and port forwarded to windows. pretty messy stuff and unrelated (unless I missed something).
=> Fix digest email

weblate/auth/models.py, weblate/auth/permissions.py, weblate/templates/base.html, weblate/templates/snippets/project/state.html
It now checks based on whether user has it configured instead of looking at current session. This allows API usage for 2fa enforced projects.
=> fix(auth): adjust checks for required 2fa

docs/contributing/frontend.rst
=> Remove extra character

docs/changes.rst, weblate/trans/autofixes/base.py, weblate/trans/autofixes/chars.py
This also adds type annotation to autofixes.
Fixes #12517
=> fix(autofixes): skip devanagari danda fix for latin variants

pyproject.toml
This removes years old releases.
=> chore(deps): bump lower versions of some dependencies

client/package.json
There might be difference in output between minor versions and that would cause mess in our CI.
=> chore(js): pin exact webpack versions

weblate/trans/management/commands/benchmark.py, weblate/trans/models/component.py
The long list of bool args is messy.
=> chore(component): make after_save accept only kwargs

weblate/static/loader-bootstrap.js, weblate/static/style-dark.css, weblate/static/styles/main.css, weblate/static/styles/variables.css
- Added clear btn that removes any date selected.
closes: #12560
=> Add clear btn to date range picker

weblate/trans/models/unit.py
- the position might be 0 in some cases (source strings without a file), so avoid listing nearby strings in that case
- the positions might be screwed up, so avoid listing too many strings
Fixes #12594
=> fix(unit): limit nearby units count

weblate/trans/forms.py, weblate/trans/views/basic.py, weblate/trans/views/search.py
This will make #12470 easier to implement.
=> feat: include object path in the search/replace form

ci/apt-install
This allows testing against PostgreSQL 17.
=> feat(deps): include postgresql-client-17

docs/api.rst, docs/changes.rst, pyproject.toml, weblate/middleware.py, weblate/settings_docker.py, weblate/settings_example.py, weblate/urls.py, weblate/utils/requirements.py
=> feat(api): add OpenAPI schema using drf-spectacular

weblate/utils/search.py, weblate/utils/tests/test_search.py
This makes the query more effective even though PostgreSQL still seems to not like using index here.
=> fix(search): search for full timestamp instead of date

weblate/billing/models.py, weblate/billing/tasks.py, weblate/billing/tests.py, weblate/trans/models/project.py
This way it gets complete view and not something intermediate while deleting a lot of translations, components or whole project.
Fixes #12627
Fixes WEBLATE-Y
Fixes WEBLATE-VHT
Fixes #12477
=> fix(billing): update billing status at the end of removal transaction

weblate/trans/models/translation.py, weblate/trans/models/unit.py, weblate/trans/tasks.py
Doing that in task makes it subject to race condition - if translation is completed before previous tasks are handled, the completed event is fired multiple times. Doing the check at the end of transaction makes it both faster and more reliable.
Fixes #12638
=> fix(translation): move completion detection from task

weblate/settings_docker.py, weblate/settings_example.py, weblate/trans/models/component.py, weblate/trans/models/label.py, weblate/utils/colors.py
This makes it behave more standard and allows to expose this nicely in spectator.
=> chore: use TextChoices for color choices

weblate/api/views.py
- Use separate method for creating than for listing
- The OpenAPI export now has correct documentation
=> feat(api): cleanup notifications API and document it

.github/matchers/spectacular.json, .github/matchers/spectacular.json.license, .github/workflows/api.yml, .gitignore, .reuse/dep5, redocly.yaml
=> feat: add OpenAPI lint to CI

weblate/formats/convert.py, weblate/memory/models.py, weblate/utils/request.py
These contribute considerably to startup time and are not always needed.
=> chore: lazily import some external dependencies

docs/changes.rst, weblate/templates/language-project.html, weblate/templates/snippets/git-info.html, weblate/templates/snippets/info.html, weblate/templates/snippets/plural.html, weblate/templates/translation.html, weblate/trans/templatetags/translations.py
This makes the information about language more visible.
=> feat(info): include basic language info in translation/language views

weblate/middleware.py
This avoids need to manually include it in WEBLATE_CSP_FORM_SRC.
=> fix(csp): automatically include SAML IDP URL in form-action

.github/matchers/mypy.json, .github/matchers/mypy.json.license, .github/workflows/mypy.yml
There are too many errors for now so filter pull request output to changed files only.
=> chore(ci): filter mypy for changed files only

.github/workflows/setup.yml, pyproject.toml
=> chore(ci): use uv to build and publish the package

weblate/machinery/apertium.py, weblate/machinery/tests.py
Hi,
This seems like a good project for a [ hacktoberfest](https://github.com/WeblateOrg/weblate/labels/hacktoberfest) may I contribute?
I've tried to fix an issue #12579 with an option to overwrite the validation arguments.
Any feedback is welcome :smiley: 
P.S. I really love the documentation of your project - and specially the custom `checks` messages. You really know the Django framework, that's awesome! :rocket: :muscle:
=> fix: use only supported languages when validating Apertium settings. Fixes: #12579

weblate/addons/base.py
It is typically updating the files so avoid possible concurrency with other repository operations.
Fixes #12692
=> fix(add-ons): perform post-update with repository lock held

weblate/static/styles/main.css
If the toolbar is long, it becomes scrollable
closes: #12687
=> Fix overflow issue in editor toolbar

docs/admin/machine.rst, docs/changes.rst
Added documentation for AWS permission requirement
fixes #12597
=> Documentation update for AWS Translate

weblate/addons/tasks.py, weblate/trans/models/component.py
This might be prohibited in some cases (for example when user adding of languages is disabled in component settings) since introduction of add-on bot users.
=> fix(component): allow consistency add-on to add languages

weblate/trans/forms.py
We need to include all transation languages, not only source languages.
=> fix(component): allow to add all existing languages in a project

weblate/accounts/models.py
Use `<strong>` and `<code>` to highlight some important parts of the audit log.
=> feat: make audit log nicely formatted

weblate/accounts/captcha.py
Switch to ast.Constant and using value attribute.
=> chore: avoid using deprecated ast

.github/workflows/macos.yml, docs/admin/auth.rst, docs/admin/install.rst, docs/admin/install/source.rst, docs/admin/install/steps/install-python.rst, docs/admin/install/steps/install-uv.rst, docs/admin/install/venv-debian.rst, docs/admin/install/venv-macos.rst, docs/admin/install/venv-redhat.rst, docs/admin/install/venv-suse.rst, docs/admin/upgrade.rst, docs/contributing/modules.rst, docs/contributing/start.rst
It performs better and comes with virtualenv embedded making it easier to manage.
=> docs: use uv as recommended tool to install Weblate

.github/workflows/migrations.yml, .github/workflows/setup.yml, MANIFEST.in, ci/pip-install, ci/run-migrate, pyproject.toml
* merge ci and test deps
* use uvx to execute twine
* introduce pydistcheck
=> chore: improve wheel linting

.github/matchers/setuptools.json, .github/matchers/setuptools.json.license, .github/workflows/setup.yml
This should collect errors seen in #12778.
=> feat(ci): add matcher for setuptools warnigs

weblate/accounts/views.py, weblate/wladmin/sites.py
Completely override Django logic as we want to divegre here.
=> fix(admin): improve second factor behaviour in admin login

weblate/templates/accounts/2fa.html, weblate/templates/accounts/login.html, weblate/templates/accounts/register.html, weblate/templates/accounts/reset.html, weblate/templates/snippets/login-info.html
- use same widht columns for info and form giving the form more space (the auth buttons or second factor buttons did not fit before)
- use full width login buttons on larger screens to give more space to lengthy names
- always show login info pane, but show it after the form on small screens
=> fix: improve sign in layout

weblate/settings_docker.py
Also enable the Azure OpenAI machinery by default in the container.
=> machinery: enable Azure OpenAI in container

docs/changes.rst, weblate/trans/models/project.py, weblate/trans/models/translation.py, weblate/trans/views/basic.py, weblate/utils/stats.py
- cache by language id instead of Language objects
- add prefetch method to speed up pages with many languages
- utilize database ordering to get instantly correct value
=> fix: improve workflow settings performance

weblate/accounts/templatetags/authnames.py, weblate/middleware.py
It doesn't define complete URL in the backend, but only a hostname what break our assumptions on how URL looks like and was ignored.
Also makes such errors visible in logs to spot it earlier.
=> fix: gracefully handle sign in using OpenInfraID

weblate/vcs/git.py
These are gracefully handled, but it is useful to collect more data on these.
=> feat(vcs): collect error reports for VCS API failures

docs/faq.rst
=> docs: mention project backups on renaming files FAQ

biome.json, weblate/static/loader-bootstrap.js
This commit fixed biomejs warnings and errors in loader-bootstrap.js.
Note also other .js files contain minor issues, they should be addressed separately. However, now the big portion is fixed. now.
closes: #12489
=> fix and enhance biomejs configuration

docs/formats/mi18n.rst, weblate/formats/ttkit.py
It was renamed upstream, see
https://github.com/Draggable/i18n/commit/f6f7fa43f37c5b0b403d21eb02e108c7f80e2a3a
=> fix(formats): rename mi18n format

docs/changes.rst, weblate/accounts/models.py
The formatting was applied to HTML formatted method.
Fixes #12909
=> fix(auditlog): fix formatting authentication method

.github/renovate.json, .github/workflows/api.yml, .github/workflows/licenses-update.yml, .github/workflows/migrations.yml, .github/workflows/mypy.yml, .github/workflows/pylint.yml, .github/workflows/test.yml, .pre-commit-config.yaml, MANIFEST.in, REUSE.toml, ci/lib.sh, ci/pip-install, ci/run-migrate, pyproject.toml, scripts/generate-license-data, scripts/set-version, scripts/show-extras, uv.lock
Use PEP 735 dependency groups for development dependencies.
=> feat: use PEP 735 for devel deps

.github/workflows/rundev.yml, rundev.sh
=> chore: use uv export to build docker requirements

.github/workflows/rundev.yml, rundev.sh, weblate/settings_docker.py, weblate/trans/tests/test_selenium.py, weblate/utils/files.py
This makes the Docker container ready for upcoming changes during the development.
=> feat: run all tests in Docker

.github/workflows/api.yml, .github/workflows/migrations.yml, .github/workflows/mypy.yml, .github/workflows/pre-commit.yml, .github/workflows/pylint.yml, .github/workflows/test.yml, ci/lib.sh, ci/pip-install, ci/run-migrate, pyproject.toml, uv.lock
This makes it easier to develop with the hosted enviroment.
=> feat: add wlhosted extra

weblate/accounts/models.py, weblate/addons/models.py, weblate/auth/models.py, weblate/billing/models.py, weblate/fonts/models.py, weblate/lang/models.py, weblate/machinery/views.py, weblate/screenshots/models.py, weblate/trans/mixins.py, weblate/trans/models/change.py, weblate/trans/models/componentlist.py, weblate/trans/models/translation.py, weblate/utils/stats.py
This is expected by Django so do not break this assumption.
Fixes WEBLATE-15WN
=> fix: make get_absolute_url return string

pyproject.toml, weblate/checks/format.py, weblate/checks/tests/test_checks.py, weblate/checks/tests/test_fluent_checks.py, weblate/checks/tests/test_icu_checks.py
While doing changes here, the type annotations were improved for check tests.
Fixes WEBLATE-15ZT
=> fix(checks): do not assume all format checks have a valid regexp

weblate/trans/checklists.py, weblate/trans/models/project.py, weblate/utils/render.py
Identified by subclass-builtin (FURB189) ruff check.
=> chore: avoid subclassing dict, list and str

weblate/trans/models/change.py
This allows to fight with spam suggestions more effectively even after removing the actual suggestions.
=> feat: log IP address for anonymous suggestions

weblate/vcs/git.py
The payload for creating a Pull Request on Bitbucket cloud has been fixed: PR description is now properly displayed
- fixes #12949
=> fix: create pull request on Bitbucket cloud payload

docs/changes.rst, docs/user/search.rst, weblate/templates/snippets/info.html, weblate/utils/search.py
This allows to search from the info tab to match shown numbers.
Fixes #12969
See also #11808
=> feat: allow user search to filter changes

docs/admin/addons.rst
points describing AT add-on triggers reflect current behavior
=> improved description of AT add-on triggers

weblate/templates/configuration/custom.css
fixes and close: #12966
**Note navigation color customization and ui**
=> fix(styles): update navbar svg color to match header text color

weblate/static/editor/base.js, weblate/static/editor/full.js, weblate/templates/snippets/embed-units-clone.html, weblate/templates/snippets/format-translation.html
updated data attributes from data-clone-text to data-clone-value
=> fix: update data attributes from data-clone-text to data-clone-value

weblate/static/loader-bootstrap.js
- Show an alert instead of the respone html text.
- Console.error the response for debugging
close: #13054
=> Improve error handling in loader-bootstrap.js with displaying an alert

weblate/static/editor/base.js, weblate/templates/translate.html
- Fixed buttons visual heirarchy in  translation editor.
- Added a confirmation popup when the user clicks skip if there are unsaved changes.
close: #13050
=> Add skip unsaved changes confirmation

.github/workflows/macos.yml, docs/admin/install/venv-macos.rst
=> docs: update macos instructions to use pkgconf

docs/admin/continuous.rst, docs/changes.rst, weblate/trans/models/unit.py
Bulk update units and create changes instead of doing all the operations manually. This should considerable reduce time needed for propagation, but still there is some time to be spent on checks.
=> feat: improve translation propagation performance

weblate/checks/same.py, weblate/checks/tests/test_fluent_checks.py, weblate/formats/exporters.py, weblate/formats/ttkit.py, weblate/machinery/openai.py, weblate/utils/html.py, weblate/vcs/tests/test_vcs.py
=> chore: use raw strings for re

weblate/trans/models/component.py, weblate/vcs/base.py, weblate/vcs/git.py, weblate/vcs/tests/test_vcs.py
This makes it harder to mess it up.
=> chore(vcs): make some args kwargs only

docs/admin/addons.rst, weblate/addons/management/commands/list_addons.py
=> docs(addons): document add-on triggering events

docs/vcs.rst
Based on https://hosted.weblate.org/translate/weblate/documentation/en/?checksum=0b0cdd77ad4a29ce#comments
=> docs: clarify what is actually enforced by the platforms

docs/admin/install/docker.rst
See https://github.com/WeblateOrg/docker/issues/1831 and https://github.com/WeblateOrg/docker/issues/2816
=> docs: describe running Docker container with read-only filesystem

docs/devel/translations.rst, docs/user/glossary.rst
=> docs: document automatic context adjustment

weblate/accounts/views.py
- factor out content generating
- use EmailMessage as we are not sending multipart here
=> chore: simplify contact mail sending

weblate/vcs/git.py
We have no use for sample hooks and other files.
=> chore: do not use template when initializing git repository

docs/changes.rst, weblate/api/views.py
=> feat: provide detailed error on permission denied for upload

weblate/trans/models/unit.py
This ensures the row level lock is being held.
=> fix: use select_for_update for translation propagation

weblate/trans/models/component.py
The push branch needs to be different from the pull one when creating a merge request.
=> fix: deny using same pull and push configuraiton for merge requests

weblate/trans/models/translation.py
=> fix: use select_for_update when deleting

weblate/trans/models/unit.py
This avoids additional SQL query in this case.
Fixes WEBLATE-1CMK
=> chore: use self as source_unit when ids match

weblate/accounts/notifications.py
Contrinue with others even if one of them can not be redndered.
=> fix: do not discard all digest notifications on render error

.github/workflows/rundev.yml, .github/workflows/test.yml
The downloads from GitHub started to timeout in CI, so utilize cache for these.
=> chore(ci): cache tesseract data

weblate/glossary/tasks.py, weblate/trans/models/translation.py
=> chore(glossary): factor out removal check to the model

docs/changes.rst, docs/vcs.rst, weblate/vcs/base.py, weblate/vcs/git.py, weblate/vcs/mercurial.py
- use git 2.28 features to avoid need for manual branch change
- rename method to create_blank_repository to better describe purpose
- hold lock while initializing the repository
Fixes WEBLATE-YW9
=> fix: consolidate repository initialization

docs/admin/projects.rst, docs/formats/appstore.rst
=> docs: add examples for key filtering

weblate/trans/models/translation.py
Removing might have unintended side-effects, so better keep it pending same as we do with saving errors.
=> fix: gracefully handle non-existing strings while saving

weblate/trans/models/suggestion.py, weblate/trans/tests/test_suggestions.py, weblate/trans/views/edit.py
The diff for `Suggestion removed` is now consistent with the diff for the `Suggestion added`
- fixes #12670
Since it's a minor fix, I thought it's not necessary to mention in changelogs.
=> 12670 inconsistent diff

docs/admin/install.rst, docs/admin/install/docker.rst, docs/changes.rst, pyproject.toml, scripts/show-extras, uv.lock, weblate/settings_docker.py, weblate/settings_example.py
- added gelf extra to install gelf logging backend
- add environment configuration to Docker image
- add example configuration in weblate/settings_example.py
=> feat: add Graylog integration

weblate/utils/search.py
- try dateutil parser first as that one works faster on standard dates
- support only English for dateparser as going through all locales is super slow (can takes second for a single lookup)
@harriebird this fixes performance of a9af33d7883d496d1684878a3a9a2998affceb6a.
=> fix: improve date parsing performance

weblate/billing/models.py, weblate/trans/models/component.py, weblate/utils/licenses.py
- visually highlight problematic bits
- do not use links without a valid URL
- add type annotations to related methods
=> feat: improve libre checklist rendering

weblate/metrics/models.py
Zero metrics should be used instead of non-existing, the only necessary thing is current metric to avoid calculating it later.
=> fix(metrics): avoid generating all past metrics entries upon creating

weblate/trans/templatetags/translations.py
The tags are usually sparsely distributed over the translation string and overhead of the long list is way bigger than dictionary. This way we also don't contrucst list for each character, but only where it is actually needed.
=> fix: utilize defaultdict for collecting hightlight tags

weblate/lang/models.py, weblate/lang/tests.py
Use prefetch and iterator to avoid caching all objects.
=> fix: effectively perform language sync

weblate/trans/templatetags/translations.py
Using function call here brings visible overhead.
=> fix: inline HTML escaping

weblate/trans/templatetags/translations.py
This avoids too many split/join calls.
Built on top of https://github.com/WeblateOrg/weblate/pull/13233
=> fix: operate on chunks when highlighting

weblate/accounts/tasks.py, weblate/trans/models/change.py
We usually need them, so better to do that in a single SQL query.
=> fix: prefetch all change attributes for notifications

weblate/trans/models/unit.py
- create change objects in bulk
- invalidate component level stats instead of doing that per translation
=> fix: batch operations in source string update

weblate/memory/tasks.py, weblate/memory/tests.py, weblate/trans/models/unit.py
Avoid repeated fetching of objects from the database by doing most operations in the main process. These are cheap, the only expensive part is updating memory entries which is now a separate task.
=> chore: refactor translation memory updates

weblate/trans/autotranslate.py, weblate/trans/models/unit.py
Also makes some args kwarg only.
=> chore: add type annotations to Unit.translate

weblate/auth/utils.py
=> chore(auth): optimize permissions sync

weblate/trans/models/component.py
Otherwise we might end up doing repeated updates.
=> feat: pospone alerts update after stats are updated

weblate/trans/models/translation.py
These are single language only so there is no source language stored there.
=> fix: set same source and target language for monolingual files

weblate/trans/templatetags/translations.py
There is no need to store the list of tokens we are going to join later.
=> chore: use generator for string formatting

weblate/trans/models/translation.py
=> chore: bulk create changes for add upload

weblate/utils/markdown.py
The MarkdownRenderer is not thread-safe, see https://github.com/miyuchina/mistletoe/issues/210
Fixes WEBLATE-1Q34
=> fix: lock protect markdown rendering

docs/changes.rst, weblate/accounts/captcha.py, weblate/accounts/forms.py, weblate/accounts/tests/test_captcha.py, weblate/accounts/tests/test_registration.py
=> fix(captcha): correctly deal with valid submission after invalid one

docs/admin/config.rst, docs/user/translating.rst
Fix Sphinx syntax errors as reported by [sphinx-lint](https://pypi.org/project/sphinx-lint/)
=> Fixes to a couple of Sphinx errors in the docs

weblate/static/styles/main.css
This makes it look more fit inside the panel.
Before:
After:
=> fix(css): base metric border radius on variable

weblate/static/styles/main.css
- make table heading (reverts part of #12982)
- use consistent border inside the tables
- avoid double border in headings
Before:
After:
=> fix(css): improve look of tables in panel

weblate/machinery/base.py
This will make it easier to diagnose issues like #13467.
=> feat(machinery): more detailed reporting of http errors

weblate/trans/util.py, weblate/utils/data.py, weblate/vcs/base.py, weblate/vcs/git.py, weblate/vcs/ssh.py, weblate/vcs/tests/test_ssh.py
This makes the code easier to read.
=> chore: use pathlib for some path manipulations

weblate/machinery/base.py, weblate/machinery/tests.py, weblate/utils/requests.py
There is additional logic to fetch detailed error.
=> fix: use machinery error handling instead of generic one

weblate/api/spectacular.py, weblate/api/views.py
- Set (Open)API tag order the same than in the official documentation, some with additional description.
- Add descriptions for most API operations.
Relates to #12584
=> Set tag order and add operation descriptions to OpenAPI spec

weblate/accounts/notifications.py
This makes the code more straightforward instead of doing that via result dict. Also makes type checking possible.
=> chore(notification): directly get translation url from change

weblate/trans/models/translation.py
This is more effective than going throught the queryset which we no longer need here.
=> chore: use list while commiting pending units

weblate/examples/mt_service.py, weblate/machinery/alibaba.py, weblate/machinery/apertium.py, weblate/machinery/aws.py, weblate/machinery/baidu.py, weblate/machinery/base.py, weblate/machinery/cyrtranslit.py, weblate/machinery/deepl.py, weblate/machinery/dummy.py, weblate/machinery/glosbe.py, weblate/machinery/googlev3.py, weblate/machinery/ibm.py, weblate/machinery/libretranslate.py, weblate/machinery/microsoft.py, weblate/machinery/modernmt.py, weblate/machinery/mymemory.py, weblate/machinery/netease.py, weblate/machinery/openai.py, weblate/machinery/saptranslationhub.py, weblate/machinery/systran.py, weblate/machinery/tmserver.py, weblate/machinery/weblatetm.py, weblate/machinery/yandex.py, weblate/machinery/yandexv2.py, weblate/machinery/youdao.py, weblate/memory/machine.py
Make it clear what is the language identifier and what is source string.
=> chore: improve variable names in machinery

weblate/templates/addons/addon_list.html
Inspired by #12448 by @comradekingu
=> fix(add-ons): consistently use levels and not scopes

docs/changes.rst, weblate/trans/models/component.py
This is more expected behavior than having to do it one by one when the repository is shared.
=> feat: make file sync work on all components in a repository

.github/workflows/docs.yml, docs/conf.py, scripts/list-documentation-languages.py
This allows to catch errors in translations earlier.
=> feat(ci): build localized documentation in CI

.github/workflows/docs.yml
This was merged prematurely due to error in the job and we do not want to have all CI failed until the root cause is addressed.
=> fix(ci): temporarily ignore failures from non-English documentation builds

weblate/api/spectacular.py
This is followup for #13430
CC @walpox
=> feat(api): dynamically generate documentation URL in OpenAPI

weblate/trans/models/unit.py, weblate/trans/tests/test_edit.py, weblate/trans/tests/test_views.py
Also adds tests to cover this workflow.
Fixes #13552
=> fix(unit): correctly mark bulk-edited units as pending

docs/changes.rst, weblate/api/serializers.py, weblate/api/spectacular.py, weblate/settings_docker.py, weblate/settings_example.py
- Add stub class to include HTTP 423 in OpenAPI specification
- Factor out DRF settings to be generated in the code. User typically does not want to change these and we change them quite often in the recent releases.
=> feat(api): document 423 in OpenAPI

docs/api.rst
These sentences have one more similar in the page, and translating with the same text causes Reused Translation to pop up. This PR basically edits to uniformize, which will deduplicate strings for translation.
=> Deduplicate strings in API page

docs/changes.rst, weblate/checks/duplicate.py, weblate/checks/same.py, weblate/checks/tests/test_duplicate_checks.py
We cannot just strip the markup as the strings around it might now be duplicate even when they are not in the original string.
=> feat(checks): better handle markup in duplicates check

weblate/trans/models/component.py
Otherwise it tries to commit not yet existing translation file and fails.
Fixes #13590
=> fix(component): commit pending changes before creating new translation

weblate/trans/tests/test_manage.py, weblate/trans/views/settings.py
Allow translators to reorder the strings.
=> fix: improve error message on failed rename

weblate/api/authentication.py, weblate/api/spectacular.py
Expose Authorization in the description.
=> feat(api): improve OpenAPI authentication description

weblate/api/serializers.py, weblate/api/views.py, weblate/screenshots/views.py, weblate/trans/models/component.py, weblate/utils/backup.py, weblate/utils/lock.py, weblate/vcs/apps.py, weblate/vcs/base.py, weblate/vcs/git.py
Include scope and compoent in the error message so that it gives more insight where the blocking operation is happening.
Issue #13345
=> feat(api): provide more detailed errors on locking

weblate/static/editor/tools/search.js, weblate/templates/addons/addon_detail.html
=> Add Search Preview in Bulk Edit Addon and Remove close when focus is lost

docs/changes.rst, weblate/accounts/tasks.py, weblate/fonts/utils.py, weblate/trans/widgets.py, weblate/utils/icons.py, weblate/utils/templatetags/icons.py
This avoids need to have static files collected locally for application run making it possible to use third-party static storage such as S3.
See #13615
=> feat: use finders to load static files locally

weblate/trans/tasks.py
This needs to be the same as for translation level.
Issue #5686
=> fix: hold component lock for component wide autotranlation

weblate/templates/accounts/user.html, weblate/templates/auth/teams-name.html, weblate/templates/manage/teams.html, weblate/templates/trans/project-access.html
=> fix(auth): list localized team names

weblate/addons/generate.py
The add-on should be explicitely installed on a component instead.
Fixes WEBLATE-215R
=> fix: disable propagation on generate add-on

weblate/trans/forms.py, weblate/trans/views/edit.py
It was used by single caller, so better to do it there explicitely.
=> chore(forms): remove get_search_query api

weblate/auth/models.py, weblate/auth/tests/test_models.py
Gracefully handle dummy fields we already do map in save.
Fixes #12700
=> feat(auth): make User.objects.get_or_create compatible with Django one

docs/changes.rst, weblate/machinery/microsoft.py, weblate/machinery/tests.py
The service supports new languages and is now stricter in accepting language codes.
=> feat: improve language mapping for Azure AI Translator

weblate/static/style-dark.css, weblate/static/styles/main.css, weblate/static/styles/variables.css
It used to be always white No matter what theme is.
Close: #13520
=> Fixed input color to match theme

weblate/trans/models/unit.py
The pending commit should happen before editing, not after it.
=> fix(unit): avoid commiting each propagated change separately

docs/api.rst, docs/changes.rst, pyproject.toml, uv.lock, weblate/api/renderers.py, weblate/api/spectacular.py, weblate/api/tests.py, weblate/api/views.py
This allows to fetch API responses in the CSV formats. This might be especially useful for statistics as outlined in #13304.
=> feat(api): add CSV renderer

weblate/api/views.py
This makes it more likely that results fit into single response.
See #13304
=> feat: use large pagination for statistics endpoint

docs/user/search.rst, weblate/metrics/models.py, weblate/templates/snippets/info.html, weblate/trans/models/change.py, weblate/utils/search.py, weblate/utils/tests/test_search.py
* feat(metrics): collect total number of contributors
* chore(change): factor out users counting
* feat(search): separate timestamp from contributor search
Fixes #11808
=> Collect total contributor count

ci/apt-install
=> chore(ci): do not use deprecated methods for postgresql apt repo

weblate/checks/chars.py, weblate/checks/same.py, weblate/examples/check_czech.py, weblate/lang/models.py, weblate/trans/autofixes/chars.py
This is faster to check and harder to mistakenly pass a string.
=> chore(lang): adjust is_base to expect set

weblate/templates/snippets/list-objects.html, weblate/trans/templatetags/translations.py
=> fix: do not show translation as completed when there are failing checks

weblate/static/style-dark.css, weblate/static/styles/main.css, weblate/static/styles/variables.css
Fix signup human verification text color n dark theme.
also grouped scattered css varaiables into one place in `variables.css`
Close: #13525
=> Fix signup human verification text color

docs/changes.rst, pyproject.toml, uv.lock, weblate/checks/consistency.py, weblate/checks/tests/test_consistency_checks.py, weblate/lang/models.py, weblate/templates/snippets/info.html
Apply different logic to languages which are not case sensitive as these will translate the same strings differing only in case.
Fixes #9450
Will need https://github.com/WeblateOrg/language-data/pull/1662 for better language case-sensitive data.
=> feat(checks): make reused check case insentive for case insensitive languages

weblate/api/serializers.py, weblate/api/tests.py
=> fix(api): validate label ID

weblate/trans/forms.py, weblate/trans/tests/test_labels.py, weblate/trans/views/labels.py
=> fix: validate label uniqueness upon creating

weblate/checks/markup.py, weblate/checks/tests/test_markup_checks.py
- catch extra space at the beginning of the string
- catch missing references when one reference is used multiple times
=> feat(checks): detect more missing references

weblate/trans/models/unit.py
=> fix: do not maintain translation memory for bots

weblate/auth/utils.py
Fetch all existing instances at once and perform sync on top of that.
=> fix: optimize permissions sync during migration

weblate/trans/backups.py
This is way faster and avoids stats update on each label.
=> fix(projectbackup): use bulk create to assign labels

weblate/trans/models/unit.py
These can not make the translation complete.
=> fix(unit): skip completed translation check for not translated strings

weblate/templates/component-list.html, weblate/trans/views/basic.py, weblate/trans/views/dashboard.py, weblate/utils/views.py
This makes the page rendering reasonable for large component lists.
=> feat: add paginator to component list view

weblate/middleware.py
=> feat(csp): automatically add awsapps.com for Amazon SAML

weblate/trans/backups.py, weblate/trans/tests/test_backups.py
=> fix(projectbackup): improve linked components restore

.github/workflows/test.yml, ci/pip-install, ci/print-versions, pyproject.toml, weblate/vcs/apps.py, weblate/vcs/mercurial.py, weblate/vcs/tests/test_vcs.py
=> feat(vcs): support mercurial with rust extensions

docs/changes/contributors/5.7.1.rst, docs/changes/contributors/5.7.2.rst, docs/changes/contributors/5.7.rst, docs/changes/contributors/5.8.1.rst, docs/changes/contributors/5.8.2.rst, docs/changes/contributors/5.8.3.rst, docs/changes/contributors/5.8.4.rst, docs/changes/contributors/5.8.rst, docs/changes/contributors/5.9.1.rst, docs/changes/contributors/5.9.2.rst, docs/changes/contributors/5.9.rst, docs/conf.py, scripts/list-contributors
There is nothing to translate there, so let's exclude them from translation.
This needs a bit hacking with Sphinx for now as there doesn't seem to be a native way to achieve the exclusion, see
https://github.com/sphinx-doc/sphinx/issues/13307.
=> docs: avoid translating contributor names

docs/admin/config.rst, docs/user/checks.rst
It was in two places and one of them was incomplete.
=> docs: consolidate autofixes docs

weblate/templates/accounts/user.html
Part of https://github.com/WeblateOrg/weblate/pull/12448
=> fix(profile): improve 2fa strings in admin profile

weblate/trans/views/create.py
The actualy error might be hidden somewhere in the form, so make it clearly visible in the top as well.
Fixes #13791
=> fix: show error message when creation form has invalid configuration

weblate/trans/models/component.py
Make the error messages formatted and easier to read.
Issue #13664
=> feat: improve error reporting on parse errors

weblate/trans/views/settings.py
=> feat(projectbackup): include project slug in downloaded file name

weblate/billing/tests.py, weblate/billing/views.py
- these are single project so the project is more important
- the plan is always the same
=> chore: remove plan info from hosting request

weblate/lang/views.py, weblate/templates/language-project.html, weblate/templates/language.html, weblate/templates/snippets/list-objects.html, weblate/trans/views/basic.py
This makes rendering faster for larger sites and large projects.
=> feat: paginate langage views

docs/changes.rst, weblate/checks/chars.py
The condition was used for Japanese only, let's expanding to to all CJK languages.
Fixes #13678
=> feat(checks): consolidate stop check behavior for CJK langs

weblate/api/renderers.py, weblate/api/tests.py, weblate/api/views.py
This does not include pagination info to make the JSON files directly consumable.
Issue #13304
=> feat(api): add flat json serializer

weblate/trans/autotranslate.py
These are read-only so they should not be altered by the automatic translation.
=> fix(autotranslate): exclude read-only strings

weblate/vcs/apps.py, weblate/vcs/git.py
=> chore(vcs): move git attributes setup to GitRepository.global_setup

docs/changes.rst, docs/user/checks.rst, weblate/checks/chars.py, weblate/trans/autofixes/chars.py
It seems more a habit than rule there, so let's not enforce it.
Fixes #13819
=> fix(checks): do not apply punctuation spacing to Breton

weblate/static/loader-bootstrap.js
Now it is editable in /browse and in /changes as well.
close: #13399
=> Fix the pagination input.

.github/workflows/macos.yml
=> chore: bump os version

docs/changes.rst, weblate/addons/models.py
Filter out only repository scoped events and not all of them.
Fixes #13432
=> fix(add-ons): limit repository scoped event delivery

weblate/trans/templatetags/translations.py, weblate/trans/tests/test_suggestions.py, weblate/trans/tests/test_templatetags.py
This makes it easier to see what was changed in the string.
Fixes #7516
=> feat: highlight leading space in diff

docs/changes.rst, docs/user/checks.rst
=> docs: changelog entry and docs for #13728 / #13786

weblate/checks/placeholders.py
The regex module supports this so let's use it as it can allow other threads to run while matchin on long strings.
=> feat(checks): release GIL during matching

docs/changes.rst, weblate/checks/source.py
- trigger only when there are multiple translations with failing check
- fixed listing of actual failures to identify all the checks
Fixes #13856
=> fix(checks): corrected multiple failures behavior

weblate/trans/views/edit.py
This is the base query which is then filtered for source and target matches.
=> fix: avoid double applying filter on other units

weblate/lang/management/commands/setuplang.py, weblate/lang/models.py, weblate/lang/tests.py
- make args kwargs only to avoid confusion position based bool
- type annotate logger
- avoid using lambdas
=> chore: clarified type of setup args

weblate/lang/models.py
- copy missing plurals instead of moving them to gracefully handle non-migrated translations
- update plurals only on migrated translations
- keep plural source upon migration
Fixes #13732
Fixes WEBLATE-22ZX
Fixes WEBLATE-22PF
=> fix: improve plurals migration to the new language

weblate/trans/autofixes/__init__.py, weblate/trans/models/suggestion.py
=> chore: add type annotations to suggestions

.github/workflows/migrations.yml, client/package.json, docs/changes.rst, docs/changes/contributors/5.10.1.rst, docs/conf.py, pyproject.toml, uv.lock, weblate/utils/requirements.py, weblate/utils/version.py
Avoid overwriting package name by inner loop.
Fixes #13872
=> fix(requirements): correctly generate URLs for packages

.pre-commit-config.yaml, docs/changes.rst, weblate/checks/base.py, weblate/checks/glossary.py, weblate/checks/source.py, weblate/utils/html.py
- use markup to better format the error
- include links to the strings
=> feat: improved rendering of multiple failing checks

docs/changes.rst, weblate/templates/zen-units.html
It just duplicated the textarea and is not really useful.
Fixes #13885
=> fix(zen): avoid displaying source language while editing it

.github/workflows/test.yml
=> feat(ci): publish tests summary

weblate/api/spectacular.py
This was mistakenly removed in a68a96cfdd0befcf8e3a2c80bfc4cdfe63901d14, see #13345.
=> fix(api): bring back custom exception handler

weblate/lang/models.py
This avoids need to enforcing this while translating.
=> fix: use title case for language name

weblate/trans/forms.py
Include links to problematic components to make it easier to address.
Issue #13896
=> feat: improve validation error on unlicensed components

docs/changes.rst, weblate/glossary/tests.py, weblate/trans/templatetags/translations.py, weblate/trans/tests/test_templatetags.py
The ending tag needs to be the first so that it does not close possibly earlier added tags.
Fixes #13907
=> fix(templatetags): correct tags ordering

docs/changes.rst, weblate/templates/js/git-status.html, weblate/trans/mixins.py, weblate/trans/models/category.py, weblate/trans/models/component.py, weblate/trans/models/project.py, weblate/trans/models/translation.py
The components can be in mixed states, so present it clearly and show both actions in mixed state situation.
Fixes #13915
=> feat(ui): detailed locking status on project

weblate/trans/views/basic.py
=> fix: show ghost translations only on the first page

weblate/templates/snippets/component-glossary-badge.html, weblate/templates/snippets/list-objects.html, weblate/templates/snippets/project-component-settings.html, weblate/trans/templatetags/translations.py
This performs better than including it.
=> fix: use template tag for redering glossary badge

weblate/trans/models/component.py
This is only needed to detect changes upon save, so store only attributes we need.
=> fix(component): store only needed attribute instead of doing full copy

docs/Makefile, rundev.sh, weblate/trans/tests/test_models.py
We should not collect static files manually and use StaticLiveServerTestCase which does handle serving static files.
=> fix(tests): use StaticLiveServerTestCase

.github/workflows/test.yml, docs/Makefile, pyproject.toml, rundev.sh, uv.lock, weblate/settings_test.py
- use separate data dir
- use automatic logic to decide number of workers
=> feat(ci): use paralel test execution

weblate/checks/duplicate.py
=> feat: localize comma in consistency checks

weblate/templates/category-project.html, weblate/trans/views/basic.py
=> fix: show ghost translations on first page only

docs/changes.rst, docs/user/search.rst, weblate/utils/search.py, weblate/utils/tests/test_search.py
This might be useful to search for strings with approved source or similar queries.
=> feat: search for source string state

weblate/trans/templatetags/translations.py
=> fix: avoid doing full query when fetching users

weblate/checks/base.py, weblate/checks/glossary.py, weblate/checks/tests/test_glossary_checks.py, weblate/trans/models/unit.py
=> fix: skip glossary initial char check for non-glossary components

weblate/utils/migrations/0001_alter_role.py
Without that this causes issues in parallel test execution. There was probably no reason for disabling transactions initially.
=> fix: execute ALTER ROLE in a transaction

weblate/accounts/notifications.py, weblate/accounts/tasks.py
- prefetch all data to reduce number of queries
- operate in transcation to ensure consistent view
Fixes WEBLATE-273H
=> fix(notify): prefetch all needed data at once

weblate/checks/tests/test_models.py
- is lowercase
- does not contain any special chars
=> test: verify that check_id matches expectations

weblate/trans/templatetags/translations.py, weblate/trans/tests/test_templatetags.py
Highlight trailing whitespace in a diff as well.
Fixes #7516
=> fix: improve whitespace highlighting

weblate/metrics/wrapper.py
- fetch using RANGE as that always uses index, unlike IN where PostgreSQL often chooses to do table scan which performs horribly
- simplify fetching wanted values
=> fix(metric): optimize fetching metric

docs/admin/memory.rst
Make the workflow easier to understand by splitting out the add-on and manual exection. Also do not mention "view" when it is actually a "tab".
Triggered by the feedback from @Geeyun-JY3 at https://hosted.weblate.org/translate/weblate/documentation/en/?checksum=63298578e2d434eb#comments.
=> docs: clarify translation memory usage

docs/changes.rst, weblate/addons/consistency.py, weblate/addons/models.py, weblate/addons/tasks.py
This makes sure that the add-on is saved in the database before the task is executed.
Fixes WEBLATE-S81
=> fix(add-ons): trigger add-on upon transaction commit

docs/user/checks.rst, weblate/checks/duplicate.py, weblate/checks/tests/test_duplicate_checks.py
- highlight words
- avoid reusing the same string for description and error message
=> feat(checks): improved error messages from duplicate words check

docs/user/checks.rst, weblate/checks/management/commands/list_checks.py
- describe why it is problematic
- move it into correct place
- add special scope for glossary terms
=> docs: clarify prohibited initial character documentation

ci/run-docs, docs/_ext/djangodocs.py
=> feat(ci): build docs using multiple threads

weblate/trans/tests/test_selenium.py
=> feat(tests): show page source if element cannot be found

weblate/trans/models/component.py, weblate/trans/templatetags/translations.py
=> fix: use configured timezone in display and commits

weblate/accounts/notifications.py, weblate/auth/models.py
Also fixes some of the unhandled conditions.
=> chore: add type annotations to notifications

weblate/utils/stats.py
It is used while constructing the object to store
old_component_settings.
Fixes WEBLATE-28VW
=> fix(stats): fetch check_flags as that is needed

docs/changes.rst, weblate/trans/models/component.py
The link cannot have linked components, so avoid fetching it from the database.
Fixes WEBLATE-27QC
=> fix: optimize fetching linked components for links

ci/run-migrate
This is not compatible with the test system for now.
=> fix(ci): avoid installing too new pygobject

weblate/templates/translate.html, weblate/trans/models/translation.py
This is actually the desired behavior to get to the list of defined terms.
Fixes #14114
=> feat: make browse link point to browsing of the glossary

weblate/trans/tests/test_selenium.py
This should avoid occasionally failing CI tests on macos when executed on already busy system.
=> fix(ci): increase webdriver timeout

weblate/machinery/weblatetm.py
=> fix(machinery): utilize md5 index for exact searches

docs/changes.rst, weblate/vcs/git.py
Without that it fails with terminal prompts disabled.
=> fix(vcs): use proactive authentication only with password provided

ci/pip-install
It apparently never worked, so remove the code.
=> chore: remove attempt to build rhg

weblate/checks/consistency.py
Reduce the mess to avoid overriding handle_batch method.
=> chore(checks): cleanup type annotations

weblate/configuration/models.py, weblate/trans/autotranslate.py, weblate/trans/models/project.py
=> chore: type annotate autotranslate

docs/changes.rst, weblate/accounts/forms.py, weblate/accounts/views.py
These are not automated, so avoid users entering captcha.
=> feat: hide captcha for invitation-based registrations

weblate/trans/models/unit.py
The event was stored, but the explanation change not.
=> feat: track explanation changes in history

weblate/trans/views/basic.py
We already limit other translations, so there is no point in showing all ghosts here if there are too many.
Fixes WEBLATE-15VH
=> fix: limit ghost translations on the translation page

weblate/glossary/tests.py, weblate/trans/models/unit.py, weblate/trans/views/source.py
Otherwise we might be discarding the state change by editing at the same time.
=> fix: use select for update when updating state

weblate/trans/autotranslate.py
The progress could have done weird things since introduction of batch translations.
Noticed in #14177
=> fix(autotranslate): corrected progress reporting

weblate/trans/models/unit.py
We really do not want to process blank strings at this point.
Might be related to #14189
=> fix(unit): exclude blank target plurals from same target units

weblate/formats/base.py, weblate/formats/convert.py, weblate/formats/exporters.py, weblate/formats/multi.py, weblate/formats/ttkit.py, weblate/formats/txt.py, weblate/trans/util.py
This also fixes one corner case in adding strings not covered by the tests.
=> chore(formats): add type annotations

weblate/trans/models/unit.py, weblate/utils/db.py
This is just a safeguard that the code is implemented as expected.
=> fix(unit): enforce transaction for some edits

weblate/utils/similarity.py, weblate/utils/tests/test_similarity.py
It is way faster and works similarly for this purpose.
=> chore: use QRatio instead of DamerauLevenshtein to measure similarity

docs/changes.rst, weblate/api/views.py, weblate/trans/models/translation.py
=> fix(api): effectively prefetch data when listing translations

docs/changes.rst, weblate/utils/search.py, weblate/utils/tests/test_search.py
=> fix(search): correctly perform exact search on a component

weblate/trans/forms.py, weblate/trans/views/edit.py
It actually does the same as source scope here, so it is just a confusing choice.
Fixes #14125
=> fix(forms): remove translation scope when commenting source

weblate/addons/tasks.py
Filter for components with missing languages first and then do the heavy lifting processing. This avoids doing repeatedly query for already consistent components.
Fixes WEBLATE-151P
=> fix(add-ons): optimize language consistency add-on

weblate/static/loader-bootstrap.js
=> Highlight string page number on click

weblate/accounts/models.py, weblate/lang/models.py, weblate/trans/forms.py, weblate/trans/views/basic.py
This makes it easier for user to choose languages he knows.
Fixes #5731
=> feat: list user languages first when adding

docs/changes.rst, pyproject.toml, uv.lock, weblate/utils/tests/test_validators.py, weblate/utils/validators.py
There is no good use case for this and it is often used for spam accounts.
=> feat: block disposable e-mails from registration

weblate/static/styles/main.css
=> Fix altcha input border radius

weblate/static/loader-bootstrap.js
Show Sort By selection. And update the `search order` icon based on what is selected.
_
https://github.com/user-attachments/assets/da495fb5-056b-47e2-bffc-c41e7065e0c7
_
close: #14098
=> Fix Sort By search menu

weblate/trans/models/unit.py
- make it behave consistently while propagating
- move the user check to the code
=> chore: consolidate translation memory update code

weblate/checks/consistency.py
Perform the check fully in the database instead of fetching the models to Python.
Issue #14274
=> fix(checks): optimize inconsistent check

weblate/checks/consistency.py
We can use existing md5 index for faster lookup.
=> fix(checks): utilize index in reused check

.github/workflows/macos.yml, weblate/accounts/tests/test_registration.py
Let's take same approach as we already do on Linux as these wheels are always causing some issues.
See also https://github.com/xmlsec/python-xmlsec/issues/346
=> chore(ci): avoid installing binary wheels for xmlsec/lxml

.github/workflows/macos.yml
Without that codecov does not find it, see
https://github.com/codecov/codecov-action/issues/1712
=> fix(ci): generate XML coverage report

weblate/trans/models/unit.py
Show summary if there is too much of errors to avoid filling up whole page.
=> fix(unit): show detailed propagation errors only if not too many

weblate/trans/models/unit.py
We only want to lock Unit object while updating, not any possible related queries included in the select.
Fixes WEBLATE-21WB
Fixes WEBLATE-2EG9
Fixes WEBLATE-2CX0
=> fix(unit): limit select_for_update scope

docs/admin/checks.rst, docs/user/checks.rst, weblate/checks/angularjs.py, weblate/checks/chars.py, weblate/checks/consistency.py, weblate/checks/duplicate.py, weblate/checks/fluent/inner_html.py, weblate/checks/fluent/parts.py, weblate/checks/fluent/references.py, weblate/checks/fluent/syntax.py, weblate/checks/format.py, weblate/checks/glossary.py, weblate/checks/markup.py, weblate/checks/placeholders.py, weblate/checks/qt.py, weblate/checks/render.py, weblate/checks/ruby.py, weblate/checks/same.py, weblate/checks/source.py, weblate/checks/tests/test_models.py
Make them all be a sentences ending with a stop.
Fixes #13999
=> fix(checks): consolidate check descriptions

docs/changes.rst, weblate/trans/discovery.py, weblate/trans/management/commands/import_project.py
- fetch existing objects info once and update it in memory, this makes huge impact when looking for hundredths of matches
- store set of existing slugs internally to fasten looking for collisions, this makes the slug collisions work on preview and is much faster
Discussion #14333
=> feat(discovery): avoid repeated database access

docs/changes.rst, docs/user/checks.rst, weblate/checks/base.py, weblate/checks/flags.py, weblate/checks/format.py, weblate/checks/management/commands/list_checks.py, weblate/checks/tests/test_checks.py, weblate/checks/tests/test_flags.py, weblate/checks/tests/test_format_checks.py, weblate/trans/tests/test_templatetags.py
This makes it compatible with GNU gettext and other third-party tools.
Fixes #14324
=> feat: add csharp-format compatibility flag to C# format check

weblate/static/loader-bootstrap.js
Ref: https://github.com/WeblateOrg/weblate/pull/14329#issuecomment-2752127318
Close: #14350
=> Fix error on non search pages

weblate/trans/models/component.py
This is now always executed async, so simplify the code and do not account on return value which is always False with run_async=True.
=> chore: simplify creating translations code

weblate/static/styles/main.css
If any of the tabs needs to overflow it will be scrollable instead.
close: #14143
=> Fix translation editor bottom tabs overflow

biome.json, weblate/static/editor/base.js, weblate/static/editor/browse.js, weblate/static/editor/full.js, weblate/static/editor/zen.js, weblate/static/js/screenshots/clipboard-paste.js, weblate/static/loader-bootstrap.js
- exclude vendored files
- apply unsafe autofixes (mostly unused variables and debug logging)
Generally, this  reduces noise from biome checker, but there are still quite some warnings in the output.
=> fix(js): update biome config and apply fixes

weblate/accounts/views.py
It suffers the same issues as OpenID, so reuse the code.
See https://github.com/python-social-auth/social-app-django/issues/481
=> fix(auth): keep next parameter over SAML auth

weblate/machinery/apertium.py
Using chain and converting to set at once is better than doing repeatedly union.
=> fix(apertium): simplify getting list of languages

weblate/trans/models/agreement.py
It cannot accept the agreements, so avoid checking for it. This avoids possible race conditions in multihtreaded environments.
Fixes  WEBLATE-2FJ9
=> fix(agreement): short circuit agreement evaluation for anonymous

docs/admin/checks.rst
This allows users to go directly to places where the flags can be set.
=> docs: describe options for adding flags

docs/admin/management.rst, docs/contributing/documentation.rst, docs/contributing/index.rst, docs/index.rst
- move existing content from index to a separate document
- better describe local build
- add documentation for list_* commands used to generate templates for the documentation
=> doc: separate and extend documentation contribution

docs/changes.rst, weblate/templates/last-changes-content.html, weblate/trans/models/change.py, weblate/trans/models/unit.py, weblate/trans/views/edit.py
- do not save no-change edit of explanation
- use diff for rendering
- correctly store previous value
Issue #13930
=> feat(changes): improve explanation and flags history

weblate/checks/markup.py, weblate/checks/tests/test_checks.py, weblate/checks/tests/test_markup_checks.py
Do no include specific labels if there are more same tags present and we do not have a way to figure which one is actually missing as they can be translated.
=> feat(checks): improve feedback on rst references check

dev-docker/docker-compose.yml, docs/contributing/start.rst, rundev.sh
Bundle maildev/maildev container in rundev and configure Weblate to use it for e-mail delivery. This makes e-mail related development easier with rundev.
=> feat(rundev): integrate maildev service

docs/user/checks.rst, weblate/accounts/password_validation.py, weblate/templates/trans/alert/common-repo.html
Issues discoverd by our translators at Hosted Weblate.
=> fix: apply fixes based on translators feedback

.pre-commit-config.yaml, client/src/altcha.js, client/src/autoComplete.js, client/src/autosize.js, client/src/fonts.js, client/src/main.js, client/src/mousetrap.js, client/src/multi.js, client/src/prismjs.js, client/src/sentry.js, client/src/tribute.js, client/webpack.config.js, weblate/static/editor/base.js, weblate/static/editor/full.js, weblate/static/editor/tools/search.js, weblate/static/js/screenshots/clipboard-paste.js
This avoids flood of warnings when the new code introduces an error. All current warnings are annotated and probably should be addressed separately.
=> feat(ci): let biome check fail on warnings

weblate/static/js/accounts/profile/index.js
- include trailing slash
- escape the URL part
=> fix(profile): correctly generate URL

weblate/lang/models.py, weblate/lang/tests.py, weblate/machinery/base.py, weblate/machinery/dummy.py, weblate/machinery/tests.py, weblate/trans/models/unit.py
This builds the basic infrastructure to support translating from other languages than the component source language.
Fixes #13768
=> feat(machinery): support translating from other source language

weblate/trans/tasks.py
=> fix(checks): use select for update when updating unit states

weblate/utils/tasks.py
This ensures that celery is running with same configuration. This might explain issues in #14504.
=> feat: include DATA_DIR in settings checked in ping

weblate/trans/widgets.py
This makes it look better when localized.
=> fix: use ngettext for languages widget label

weblate/static/editor/full.js
issue:
The  event listener for submit of the form, and the one for modal.bs.show weren't attached at all to the elements.
close: #14546
=> fix(editor): fix glossary dialog initialization and event handling

weblate/static/js/keyboard-shortcuts.js, weblate/templates/base.html
- The option opens the available shortcuts modal.
- The shortcuts modal is more accessible empowering advanced users.
=> feat: add shortcuts button to the navigation menu

weblate/machinery/cyrtranslit.py, weblate/machinery/tests.py
* Fixed placeholders handling
* Remove Belarusian alias to Russian
=> Cyrtranslit fixes

weblate/addons/tasks.py
This makes it load all the attributes instead of possibly loading later when rendering.
=> fix(add-ons): use prefetch when working on changes

.github/workflows/macos.yml
Hopefully this will resolve occasional crashes.
=> fix(ci): use uv from brew and update Python

weblate/addons/models.py, weblate/addons/tests.py
Deliver only events which are likely to be consumed.
=> fix(add-ons): filter change events to be delivered

ci/docker-compose-postgresql.yml, dev-docker/docker-compose.yml
- use alpine versions in CI
- pin exact versions in dev-docker
=> chore: consolidate used Docker containers

weblate/trans/backups.py, weblate/trans/tests/test_backups.py
Backup per-project access control teams during project backups.
Fixes #13744
Depends on https://github.com/WeblateOrg/weblate_schemas/pull/429 and https://github.com/WeblateOrg/weblate/pull/14531.
=> feat: backup project teams

weblate/checks/chars.py
This allows to short-circuit check processing before going into individual strings.
=> chore(checks): utilize should_skip API when possible

docs/contributing/addons.rst, weblate/accounts/notifications.py, weblate/accounts/tasks.py, weblate/addons/base.py, weblate/addons/tasks.py, weblate/addons/webhooks.py, weblate/trans/models/change.py
- it is no longer used with .get() so rename the method
- use prefetch_related for files which are likely to be repetated
- use select_related for unique fields which will have to be fetched
- add type annotations
=> fix(change): optimize prefetch for rendering changes

weblate/trans/models/translation.py
=> fix: correctly store glossary sync events

docs/admin/install.rst, docs/admin/install/docker.rst
Rendered docs: https://weblate--14674.org.readthedocs.build/en/14674/admin/install/docker.html#ssl-terminating-proxy
=> docs: describe SSL termination setup with Docker container

weblate/checks/tests/test_checks.py, weblate/glossary/models.py, weblate/glossary/tests.py, weblate/machinery/openai.py, weblate/trans/views/edit.py
This heavily reduces number of queries needed while browsing in zen mode and in OpenAI bulk translate.
=> feat(glossary): bulk fetch glossary terms for units

weblate/formats/base.py
It can contain invalid XML chars as well, process it.
Fixes WEBLATE-2A7G
=> fix(exporters): apply string filter to location

docs/changes.rst, docs/user/search.rst, weblate/utils/search.py, weblate/utils/tests/test_search.py
=> feat(search): add has:location lookup

.github/workflows/api.yml, .github/workflows/docs.yml, .github/workflows/linkcheck.yml, .github/workflows/macos.yml, .github/workflows/migrations.yml, .github/workflows/mypy.yml, .github/workflows/pre-commit.yml, .github/workflows/pylint.yml, .github/workflows/setup.yml, .github/workflows/test.yml, .github/workflows/uv-upgrade.yml, .readthedocs.yml, ci/lib.sh, ci/pip-install, ci/run-migrate, dev-docker/weblate-dev/start-dev, scripts/set-version
We no longer have source dependency in pyproject.toml so that did nothing and it is now not compatible with some other args.
=> fix: avoid using uv .. --no-sources

weblate/utils/files.py
=> fix: include leading and trailing slash when testing for excluded paths

weblate/glossary/models.py
=> fix(glossary): prefetch parent object info in fast mode

weblate/glossary/tasks.py, weblate/trans/models/component.py
- hold repository lock while performing the sync
- avoid repeated trigger from a single transaction
Fixes WEBLATE-26S8
=> fix(glossary): avoid concurrent glossary sync exection

weblate/vcs/ssh.py
Add connection timeout 20 seconds to avoid overly long waiting for the SSH connection to establish.
=> feat(ssh): add connection timeout

weblate/static/editor/base.js, weblate/static/editor/zen.js
=> fix(editor): pass event to indicateChanges for accurate context

docs/contributing/release.rst, docs/security/index.rst
=> docs: clarify security updates

weblate/addons/tests.py
Noticed by @KasukabeDefenceForce in #14733.
=> fix(test): correctly test for JSON sorting

weblate/templates/mail/base.html
=> fix: restructure footer in email template for better compatibility with email clients

docs/changes.rst, weblate/addons/webhooks.py
This is backend change only so it stores the info, makes it possible to debug it, but additional UI to make the log display nicer is needed.
Issue #14662
=> feat(add-ons): log request and response for the webhook add-on

weblate/addons/webhooks.py
This sets a custom user agent so that the behavior is consistent with other requests coming from Weblate.
=> fix(add-ons): use weblate requests interface for webhooks

weblate/addons/tasks.py
Avoid using auto scope as that makes log entry about the add-on execution for each component in a project and filters out it later. Instead get the scope from the change instance directly and filter add-ons before executing handle_addon_event.
=> chore(add-ons): simplify change add-on trigger

weblate/utils/apps.py
This makes the code simpler and easier to maintain.
=> chore: use pathlib to check data dirs

weblate/addons/gettext.py
The msgmerge has no use in monolingual setup (and is not implemented there) so do not offer it.
Fixes #14814
=> fix(add-ons): remove po-mono from msgmerge compatibility list

weblate/auth/models.py, weblate/templates/snippets/info.html, weblate/trans/models/project.py
Add a row for showing project reviewers if any on the info tab under overview section.
Fixes: https://github.com/WeblateOrg/weblate/issues/12694
=> Add section for showing project reviewers

weblate/templates/snippets/share-menu.html
Also reorder the sharing links.
Fixes #14850
=> feat: add share to Bluesky link

.pre-commit-config.yaml, docs/admin/install/docker.rst
It is available in the Docker image since
https://github.com/WeblateOrg/docker/pull/3269.
=> docs: document Anubis integration

weblate/templates/manage/backups.html, weblate/templates/manage/index.html, weblate/utils/checks.py, weblate/utils/const.py, weblate/wladmin/apps.py, weblate/wladmin/models.py
- make unpaid subscription and configuration error
- indicate which backup services have errors in the listing
- add explanation if subscribed backup no longer works with unpaid subscription
- add custom status when using community support but had a subscription before
Issue #14872
=> feat: improve reporting broken backups or unpaid subscriptions

docs/security/issues.rst
This describes current practice of publishing vulnerabilities and includes some CRA requirements that will affect us.
=> docs: add vulnerability disclosure policy

weblate/trans/models/component.py
=> fix: removing locking alert on manually locked component

weblate/templates/accounts/2fa.html, weblate/templates/accounts/login.html, weblate/templates/accounts/register.html, weblate/templates/accounts/reset.html, weblate/templates/accounts/snippets/login-about.html, weblate/templates/accounts/snippets/login-info.html, weblate/templates/accounts/snippets/login-title.html, weblate/templates/snippets/about.html
This makes the content customization simpler.
=> feat: restructure login templates

weblate/accounts/models.py
This can be used to route it to GELF or other external log storage.
=> feat(accounts): log auditlog entries to system log

weblate/trans/models/unit.py
If the source string was changed twice, keep previous change.
Fixes #14957
=> fix(unit): keep previous source when present

weblate/trans/models/translation.py, weblate/utils/validators.py
Remove exclamation mark and make it more descriptive.
=> fix: improve validation error messages

.github/workflows/issue-closed.yml
- make it clear when the fix will be available
- some wording changes
=> feat: improve automated comment on issue closing

docs/admin/auth.rst, docs/index.rst, docs/security/passwords.rst
Document how passwords are stored and validated. Mostly this refers to the Django documentation.
=> docs: document password security

docs/admin/addons.rst, weblate/addons/forms.py, weblate/templates/addons/pseudolocale.html
The changes are based on feedback from our translators community.
=> fix(add-ons): improve texts in pseudolocale and CDN add-ons

BACKERS.rst, docs/admin/auth.rst, docs/admin/install.rst, docs/admin/management.rst, docs/changes.rst, docs/changes/v0.rst, docs/changes/v3.rst, docs/changes/v4.rst, docs/contributing/schemas.rst, docs/user/checks.rst, docs/user/search.rst
=> docs: apply feedback from translators

weblate/trans/models/unit.py
Even if the file format does not support this, the change is useful for audit.
=> fix(unit): always generate change entries for explanation

weblate/trans/models/unit.py
=> fix(unit): avoid generating change if there is no change in flags

docs/admin/backup.rst, docs/index.rst, docs/security/disaster-recovery-plan.rst, docs/security/issues.rst
This describes our own infrastructure, but can be similarly applied to other installations.
=> docs: add disaster recovery plan

.github/workflows/setup.yml, .github/workflows/uv-upgrade.yml, .github/workflows/yarn-update.yml, MANIFEST.in, REUSE.toml, docs/changes.rst, docs/index.rst, docs/security/dependencies.rst, docs/security/index.rst, docs/specs/sbom/partial/javascript.json, docs/specs/sbom/partial/python.json, docs/specs/sbom/sbom.json
Automatically generated from the JavaScript and Python dependencies. This is probably incomplete and will need additional tuning, but it is a starting point to providing a SBOM.
Fixes #14106
=> feat: add SBOM documentation

docs/changes.rst, docs/index.rst, docs/security/index.rst, docs/security/threat-model.rst
Basic threat model utilizing STRIDE and describing common mitigation strategies.
=> docs: add threat model

docs/admin/optionals.rst, docs/index.rst, docs/security/index.rst, docs/security/privacy-compliance.rst
This describes how Weblate complies with various regulatory frameworks.
=> docs: add privacy compliance framework

weblate/templates/last-changes-content.html
Lack of the badge is not a good indication.
=> feat(changes): add complimentary badge to "Current translation"

docs/user/glossary.rst
The glossary documentation was missing links to uploading files thus made it hard for some users to notice this possibility.
Fixes #6615
=> docs: describe glossary import

docs/devel/mobile.rst, docs/index.rst
Describe the recommended approach to localize apps on multiple platforms.
Fixes #9196
=> docs: add multi-platform localization

weblate/templates/category.html
The watch menu for category wrongly used category instead of project leading to broken behavior.
=> fix: watch menu for category

weblate/utils/stats.py
It was already added at other levels, but is missing here.
Fixes WEBLATE--G9
Fixes WEBLATE--JT
=> fix(stats): add missing select in component list fetch

weblate/formats/ttkit.py, weblate/trans/models/translation.py
The updateheader does not add new entries unless explicitely told to do so.
=> fix(formats): ensure that generated PO files have full header

weblate/trans/forms.py, weblate/trans/tests/test_changes.py, weblate/trans/views/changes.py
Addresses https://github.com/WeblateOrg/weblate/issues/12531#issuecomment-2917047914 but does not close #12531 completely.
We can change the label of the field if we want to.
Screenshot:
=> Add exclude user changes

weblate/trans/tasks.py, weblate/trans/views/hooks.py
This makes it easier to identify origin of the updates in the history.
See #12531
=> feat(hooks): create bot users for webhooks

.github/workflows/macos.yml
MacOS 15.4 is broken and there is no way to revert to 15.3 so let's revert to 14.
Fixes #14645
=> chore(ci): downgrade macos system

weblate/trans/models/component.py, weblate/trans/models/translation.py, weblate/utils/messages.py
The middleware is always installed, these are fake request objects used internally where no messages are expected.
Fixes WEBLATE-2VJK
=> fix: fail silently if messages can not be added

weblate/formats/tests/test_formats.py, weblate/formats/ttkit.py
Make the formatting consistent with what Weblate would write out.
Fixes #15046
=> fix(formats): correctly format Android blank file

weblate/static/styles/main.css
Fixes one of the occurrences of the translation editor overlay misaligning with the text, causing confusing behavior
Fixes #14370
=> fix: consistent line wrapping in text editor

docs/security/dependencies.rst
Make the description generic and link to the used services.
=> docs: clarify container vulnerability scanning

weblate/formats/tests/test_formats.py, weblate/formats/ttkit.py
This seems required see #15096.
=> fix(formats): use BCP for naming of Fluent files

docs/admin/install/venv-redhat.rst
=> docs: fix RedHat package names

weblate/templates/category-language.html, weblate/utils/stats.py
Fixes #11198
Follow-up for #15010
=> feat: add translation tab to category-language view

docs/admin/auth.rst, docs/admin/install.rst, docs/changes.rst, pyproject.toml, scripts/show-extras, uv.lock
The xmlsec dependency is most tricky one we have, so remove the burden of dealing with it from users who do not use SAML.
See #15163
=> fix(deps): exclude SAML from all extras

weblate/trans/models/unit.py
=> fix(checks): consider only translated strings for reused check

docs/changes.rst, weblate/machinery/base.py
Apparently the error responses could vary even if documented otherwise, so be flexible in what we handle gracefully.
=> fix(machinery): improve erorr handling

weblate/trans/migrations/0040_auto_20250613_1813.py
If an author is not available for a unit change, set it to the anonymous user.
fix #15254.
=> bugfix(pending-migration): handle missing author

docs/changes.rst, docs/user/search.rst, weblate/auth/models.py, weblate/screenshots/views.py, weblate/trans/models/unit.py, weblate/utils/search.py, weblate/utils/tests/test_search.py
This itroduces a way to add annotations from the search to make such lookups effective.
Fixes #14467
=> feat(search): add support for filtering by labels count

weblate/trans/models/component.py, weblate/trans/tasks.py
This will be a lenghty operation and it does not have to be synchronous.
=> feat(component): perform commit for file sync in the background

weblate/utils/lock.py
- define lock params explicitely
- check whether lock is already acquired and extend it in that case
- fixed ordering on lock acquire
- make depth thread local to catch threading issues
=> fix(lock): make the lock reentrant

docs/formats/qt.rst, docs/user/checks.rst, docs/user/search.rst, weblate/formats/ttkit.py
Update links to follow upstream redirects and documentation updates.
=> docs: update external links

docs/changes.rst, weblate/api/tests.py, weblate/trans/models/component.py, weblate/trans/models/translation.py, weblate/trans/models/unit.py
The Change objects for replace uploaded file were not properly credited to the uploading user.
Fixes #15298
=> fix(upload): correctly track change authorship on replace upload

weblate/checks/flags.py, weblate/checks/tests/test_flags.py, weblate/formats/base.py, weblate/formats/convert.py, weblate/formats/multi.py, weblate/formats/tests/test_formats.py, weblate/formats/ttkit.py, weblate/formats/txt.py, weblate/trans/models/unit.py
=> Use Flags object on file format flags

weblate/addons/base.py, weblate/formats/ttkit.py, weblate/utils/backup.py, weblate/utils/files.py, weblate/vcs/gpg.py, weblate/vcs/ssh.py
These bring little value and just make the error messages longer.
=> feat(errors): hide data and cache paths from user visible messages

weblate/trans/change_display.py
- use StrOrPromise to gracefully handle lazy gettext
- add explicit conversion to string where needed
=> chore: fix type annotations

weblate/trans/models/alert.py
=> fix(alerts): prefetch language field which is always used

docs/changes.rst, weblate/lang/forms.py, weblate/templates/lang/language_edit_warning.html, weblate/templates/lang/language_form.html
- motivate users to contribute to the Weblate language data package
- add warning that edits might be reverted upon update
Fixes #15407
=> feat: indicate that language edits might be reverted

weblate/trans/actions.py, weblate/trans/models/change.py
This adds additional storage for some important events in the system making it easier to store them on another system for audit purpuses.
=> feat(change): log important change events

weblate/utils/lock.py
This makes it easier to debug locking issues.
=> feat(lock): log state information in Sentry

weblate/utils/ratelimit.py
Use functools.wraps to correctly wrap inner function.
=> chore(utils): improve ratelimit decorator

docs/workflows.rst
Make it more obvious who is responsible for which file.
See #15410
=> docs: clarify quality gateway workflow description

docs/admin/install.rst, docs/admin/install/docker.rst, docs/admin/management.rst, docs/contributing/internals.rst
- how tasks are defined and triggered
- why there are different task queues
=> docs: describe Celery tasks internals

weblate/templates/category.html, weblate/templates/component.html, weblate/templates/translation.html
Half of the views had it in the nav_pill, half outside.
=> fix: consolidate position of watch menu

weblate/trans/change_display.py
This is mostly to make mypy happy, but also produces easier to read code and fails nicely in case something goes wrong.
=> chore(changes): add sanity checking to display code

weblate/trans/util.py, weblate/utils/licenses.py, weblate/utils/messages.py
Corrected some mistakes in type annotations.
=> chore: update type annotations

weblate/templates/trans/backups.html, weblate/trans/models/project.py
Use Django built-in filter instead of doing that manually.
Fixes #15555
=> feat(backup): improved display of backup size

weblate/screenshots/models.py, weblate/trans/backups.py
=> chore: add type annotations to backups

docs/changes.rst, weblate/trans/models/component.py, weblate/vcs/base.py, weblate/vcs/git.py
When pushing to a different branch or using pull requests, conflicts should not block pushing to make it easier to resolve conflicts upstream.
=> feat(vcs): allow pushing in case of merge conflicts

docs/changes.rst, weblate/api/serializers.py, weblate/api/views.py, weblate/auth/models.py, weblate/auth/permissions.py, weblate/auth/results.py, weblate/trans/models/unit.py, weblate/trans/util.py
- add more verbose Denied statements to the permission check
- gracefully handle boolean return value
=> fix(api): improved permission denied handling

weblate/trans/management/commands/import_demo.py, weblate/trans/models/component.py, weblate/trans/models/translation.py, weblate/trans/models/unit.py, weblate/trans/tests/test_component.py
This significantly improves performance of parsing bilingual translations when a lot of new source strings are introduced.
Issue #15427
=> feat(translation): bulk create source strings while parsing

weblate/trans/models/component.py, weblate/trans/tasks.py
This makes the changes correctly associated to the acting user (or webhook bot user).
=> fix(component): pass acting user to background translation sync

weblate/templates/translate.html
It makes sense to show it prominently as it usualy contains important info.
=> feat: show source note if explanation is not available

weblate/utils/stats.py
=> fix(stats): avoid duplicate listing of components inside project-language

weblate/templates/base.html, weblate/templates/footer.html, weblate/trans/tests/test_selenium.py
- Add link to privacy policy with the legal app (this seems to required in most countries)
- Do not use legal_url / privacy_url if legal app is installed
- Shorten the texts in the footer
- Use context to clarify the short text in the footer and help menu for translators
=> feat: improve footer links

docs/admin/addons.rst, weblate/addons/management/commands/list_addons.py, weblate/checks/management/commands/list_checks.py, weblate/machinery/management/commands/list_machinery.py
This way it is more compact while keeping possiblity to localize field and description separately.
=> docs: use nested tables for add-on parameters

.github/workflows/mypy.yml, scripts/filter-mypy.sh
Remove things which we are not able to address in the near future.
=> chore(ci): filter out mypy errors

pyproject.toml
- add one more typo
- exclude map files (those are generated)
=> chore: update typos confiuration

scripts/filter-mypy.sh, weblate/addons/management/commands/list_addons.py, weblate/addons/views.py, weblate/checks/base.py, weblate/checks/management/commands/list_checks.py, weblate/checks/models.py, weblate/checks/tasks.py, weblate/checks/tests/test_fluent_checks.py, weblate/checks/views.py, weblate/formats/tests/test_formats.py, weblate/trans/autofixes/__init__.py, weblate/trans/autofixes/base.py, weblate/trans/filter.py, weblate/trans/forms.py, weblate/trans/models/component.py, weblate/trans/tests/test_autofix.py, weblate/utils/classloader.py, weblate/vcs/base.py, weblate/vcs/git.py, weblate/vcs/mercurial.py
This spreads across several modules and is incomplete, but still provides a good starting point.
Issue #3703
=> chore: add type annotations to class loader

weblate/addons/tests.py, weblate/addons/views.py
Also adds tests for the error handling.
=> feat(add-ons): improve error messages for failed installation

.github/workflows/mypy.yml
- fail if mypy didn't produce any output
- generate summary from last mypy line
=> chore(ci): improve mypy handling

weblate/utils/celery.py
=> chore: log task in from celery

weblate/templates/addons/addon_logs.html
=> fix(add-ons): corrected displaying errors in the log

weblate/accounts/notifications.py
Exclude bot and inactive users at the dabase side rather than doing the filtering later in Python.
=> fix(notify): avoid fetching notifications we will not use

weblate/accounts/notifications.py, weblate/accounts/tasks.py, weblate/accounts/tests/test_notifications.py
Filter out subscription based on the project admins, not including all site users.
=> fix(notifications): avoid fetching all admins

weblate/trans/models/translation.py
This can be too noisy in some cases.
=> chore: remove sentry reporting for unit not found

docs/admin/addons.rst
Without that it can be a source of conflicts, see #15738.
=> docs: recommend configuring webhooks for squash add-on

.github/workflows/mypy.yml, weblate/trans/backups.py, weblate/trans/models/project.py, weblate/trans/tests/test_backups.py, weblate/trans/views/settings.py
- It now utilizes pathlib for simpler code.
- The listing is moved to the projectbackup code.
=> chore(backup): refactor project directory operations

docs/changes.rst, weblate/api/tests.py, weblate/formats/ttkit.py
=> feat(format): support starting from scratch with XLIFF

weblate/templates/js/git-status.html, weblate/trans/views/js.py
This makes it easier to browse past repository changes.
=> feat(repo): add link to browse all repository changes

weblate/accounts/apps.py, weblate/accounts/views.py, weblate/auth/models.py, weblate/auth/utils.py, weblate/middleware.py, weblate/utils/checks.py, weblate/utils/docs.py
It is easy to make this wrong, so let's add validation against actually enabled backends.
See #15769
=> feat: add validation of REGISTRATION_ALLOW_BACKENDS

docs/changes.rst, weblate/machinery/forms.py, weblate/machinery/openai.py, weblate/machinery/tests.py
- remove hardcoded model parameters, these might have worked for the early models, but now are not compatible and probably not reasonable
- update list of models
- corrected type annotations
Fixes #15772
=> feat(machinery): compatibility with latest models

weblate/accounts/views.py, weblate/auth/models.py, weblate/templates/auth/teams-projects.html
The queryset was performed without getting name attribute and Django failed to lazy load it what caused empty set being used.
See #11741
=> fix: corrected listing of projects in teams

weblate/trans/models/component.py, weblate/trans/models/translation.py
Annotates return value and add explicit str -> bool conversion.
=> chore: add type annotations for template checks

weblate/api/tests.py, weblate/api/views.py
Do not list any users for anonymous access and list only self for regular users.
=> fix(api): reduce users api visibility

docs/api.rst, docs/changes.rst
Followup for #15585 and #15881. I still didn't cover all the changes there...
=> docs: document impact on API users for autotranslate changes

weblate/static/styles/main.css
Fix https://github.com/WeblateOrg/weblate/issues/15902
=> fix(ui): use margin instead of padding for auth image in list

docs/specs/sbom/partial/python.json, docs/specs/sbom/sbom.json, pyproject.toml, uv.lock
The Docker container is now based on granian.
=> chore(deps): remove no longer needed dependency

weblate/api/tests.py, weblate/api/views.py
This is used in the front-end so it should work for authenticated users as well.
Fixes #15941
=> fix(api): allow username based lookup of users

weblate/machinery/weblatetm.py
The read-only strings can be possibly blank, so avoid these.
Issue #15969
=> fix(machinery): exclude blank strings from weblate backend

weblate/examples/celery-weblate.conf
In most situations this needs to be customized for the production environment, so provide some basic guidance and values to start with.
Fixes #15989
=> fix(examples): specify concurrency explicitely

pyproject.toml, weblate/trans/migrations/0001_squashed_weblate_5.py, weblate/trans/migrations/0032_remove_change_trans_chang_timesta_2565db_idx_and_more.py, weblate/trans/migrations/0046_component_file_format_params.py
These can contain manually written code so it is better to ignore few false positives than missing errors in the written code.
=> fix(ci): apply spell checking to migrations as well

docs/admin/install/docker.rst
This is followup to https://github.com/WeblateOrg/docker/pull/3603.
=> docs(docker): clarify WEB_WORKERS behavior

weblate/trans/forms.py
Suggested by @emmapeel2 in #15970
=> feat(glosary): add help text to glossary term options

docs/changes.rst, rundev.sh, weblate/addons/consistency.py, weblate/api/spectacular.py, weblate/settings_docker.py, weblate/settings_example.py
=> fix(api): typo in get_drf_standardized_errors_settings

docs/changes.rst, weblate/templates/dashboard/componentlist.html, weblate/templates/dashboard/user.html, weblate/trans/models/componentlist.py, weblate/trans/tests/test_dashboard.py, weblate/trans/views/dashboard.py, weblate/urls.py
This can be expensive to render, so do that only when user clicks on the tab.
Fixes #14663
=> feat(dashboard): lazily load componentlist content

docs/changes.rst, weblate/checks/markup.py, weblate/checks/tests/test_markup_checks.py
It is okay to localize it, only the target should be checked. The code was actually trying to do that, but forgot to strip the role before parsing.
=> fix(checks): correctly exclude reference label from the check

docs/changes.rst, weblate/api/tests.py, weblate/trans/util.py
Verify that format is bilingual update capable before trying source upload method.
See #16065
=> feat(api): improve file upload method validation

docs/admin/support.rst
The main purpose of this is to have a place where to document usage of the PGP key.
=> docs: describe contacting customer care

docs/changes.rst, weblate/formats/base.py, weblate/formats/exporters.py, weblate/formats/models.py, weblate/formats/tests/test_exporters.py
=> feat: add multivalue CSV exporter

weblate/auth/views.py
=> fix(auth): reject accepting invitations for different users

weblate/auth/models.py, weblate/trans/tests/test_acl.py
Adding to the team was credited to the user who was added based on the invitation, not to the user who created the invitation.
=> fix(auth): correctly track team add from invitation

weblate/sitemaps.py
=> fix(sitemap): use latest to get last timestamp

weblate/accounts/forms.py, weblate/templates/accounts/register-password.html, weblate/templates/accounts/register.html
Some users are confused that the password is not asked immediatelly.
=> feat(registration): make it clear that the password is set  later

weblate/trans/views/create.py
There is no need for this to survive the request, we only want effective filtering inside the request and that is better to achieve using local variable.
=> fix(create): avoid caching branches in lru_cache

docs/admin/auth.rst, docs/admin/install/docker.rst, docs/changes.rst, weblate/settings_docker.py
- make Docker defaults consistent with vanilla ones
- do not set attr_name which is not used by SAML backend
- update documentation
=> fix(auth): improve SAML integration

docs/vcs.rst
=> docs: add missing links to the VCS docs

docs/admin/continuous.rst
This should be really there for all the integrations, but start with GitLab and extend this later in #16257.
=> docs: add troubleshooting to GitLab integration

weblate/gitexport/views.py
Make sure thecommunication pipes are closed when no longer needed.
=> fix(gitexport): close pipes when done

docs/admin/install/docker.rst
- include REDIRECT_DOMAINS to avoid possible open redirect
- clarify generating private key
=> docs(docker): improve anubis integration instructions

docs/admin/languages.rst, docs/contributing/index.rst, docs/contributing/modules.rst
- move to the modules docs (where the repo points to)
- add more cross references
=> docs: clarify language definition contributions

weblate/trans/bulk.py, weblate/trans/models/unit.py, weblate/trans/views/js.py, weblate/trans/views/source.py
This way the check ignoring is properly tracked in the history.
=> fix(unit): use update_extra_flags to set flags

weblate/templates/accounts/user.html
Show it to self or to the site admin.
=> feat: show user expiry on profile

weblate/checks/tests/test_format_checks.py, weblate/trans/tests/test_workflowsetting.py
=> chore: fix and annotate typos

docs/admin/config.rst, docs/changes.rst, weblate/accounts/models.py, weblate/accounts/notifications.py, weblate/accounts/tests/test_notifications.py, weblate/accounts/tests/test_views.py, weblate/settings_example.py, weblate/utils/ratelimit.py, weblate/utils/tests/test_ratelimit.py
Followup for https://github.com/WeblateOrg/weblate/pull/15678 with fixes.
=> Multi-Level Rate Limiting for Notification E-Mails

weblate/checks/base.py, weblate/checks/chars.py, weblate/checks/consistency.py, weblate/checks/markup.py, weblate/checks/models.py, weblate/checks/tests/test_markup_checks.py, weblate/static/editor/full.js
This way we can correctly handle plurals in has been translated check.
Fixes #16358
=> feat(checks): add support for full string fixups

weblate/billing/models.py, weblate/billing/tasks.py
This avoids concurrency issues.
=> fix(billing): use select for update

weblate/templates/auth/team.html
=> fix: localize team name in breadcrumbs

weblate/addons/base.py, weblate/addons/cdn.py, weblate/addons/discovery.py, weblate/addons/flags.py, weblate/addons/generate.py, weblate/addons/gettext.py, weblate/addons/git.py, weblate/addons/models.py, weblate/addons/properties.py, weblate/addons/removal.py, weblate/addons/resx.py, weblate/addons/utils.py, weblate/addons/webhooks.py, weblate/formats/ttkit.py
=> chore(add-ons): extend type annotations

LICENSES/CC-BY-SA-4.0.txt, REUSE.toml, docs/contributing/code_of_conduct.rst, docs/contributing/index.rst, docs/index.rst
This Code of Conduct is adapted from the Contributor Covenant. Moved from .github repo to the docs to have a single place to store it.
=> docs: add code of conduct

README.rst, docs/contributing/communication.rst
We are not really available there, so it's not something we should promote.
=> docs: remove links to IRC

weblate/templates/snippets/info.html
This will make it easier to spot why some strings are not in VCS.
=> feat: show commit policy in the component info
