WeblateOrg/weblate

- weblate/trans/formats.py
Updated context fetching for XLIFF format
> Fixes #633

- weblate/trans/vcs.py
A quick and dirty fix for issue #639. It works for my setup, but I haven't tested it extensively.
OS: Debian Wheezy
Git: 1.7.10.4
> Change push.default to current (Fixes: #639).

- weblate/html/translate.html
Fixed login hint if user is authenticated but has no permission to save translation
> Fixed login hint if user is authenticated

- docs/admin/auth.rst
Documentation on how to get CAS working with Weblate (from #881).
I'm not sure how much of a disclaimer the section should get: while we're perfectly happy with our CAS setup it's hard to find mature CAS implementations and even proper, readable documentation about it. The whole CAS ecosystem feels ad-hoc and hacky. Also, using `django-cas-ng` with a CAS v3 server should work just fine but talking to a v2 server currently requires running `django-cas-ng` from git to extract the attributes (and the server needs to support the __right style__ of attributes. From my research there are at least 3 known ways of including them inside the XML).
> Document CAS authentication

- weblate/trans/aresource.py
- weblate/trans/tests/test_formats.py
Otherwise my editor and Weblate keep fighting each other.
> End JSON files with a newline

- weblate/trans/formats.py
Allow to add new languages with Qt TS files using lupdate command (similar to PO file handling)
> Allow to add new languages with Qt TS files using lupdate command

- README.rst
for other badges, see https://github.com/buildtimetrend/service#shield-badges
> add Buildtime Trend shield badge

- weblate/trans/models/translation.py
- weblate/trans/tests/data/cs-badplurals.po
- weblate/trans/tests/test_files.py
This fixes #900 by simply preventing the faulty upload.
> reject uploaded file with mismatched plural form

- weblate/trans/checks/angularjs.py
- weblate/trans/tests/test_angularjs_checks.py
This adds the highlighting for the angularjs check as promised in PR #982
> Angularjs check highlight

- docs/admin/access.rst
explain how multiple groupACLs on a single object interact
> clarify order of application of group ACLs

- docs/admin/access.rst
- weblate/trans/permissions.py
- weblate/trans/tests/test_permissions.py
the new documentation says it all
> limit project-level actions to project-specific groupACLs

- weblate/accounts/views.py
seealso `https://www.python.org/dev/peps/pep-3106/`
> Python 3 compatibility fix: dict_keys is not list type in python 3

- docs/admin/install.rst
Simple typing mistake I noticed whilst using this documentation for an install. :)
> Spelling correction.

- docs/admin/install.rst
* replaced python mysql package
* added missing django restframework
> Updated required Ubuntu/Debian packages

- examples/hook-json_restore_hierarchy
> Fix deeper hierarchies

- weblate/html/accounts/profile.html
> improve message

- weblate/settings_example.py
this is already done by [`weblate/requirements.py`](https://github.com/HassenPy/weblate/blob/master/weblate/requirements.py)
Do you prefer opening issues first for this kind of small changes?
> duplicate version checks

- weblate/trans/checks/consistency.py
> improve English text

- openshift/wsgi_install.py
> Typo-fix in openshift install messaging

- weblate/trans/vcs.py
Hi,
These are a couple of changes which are supposed to improve the state of Mercurial support in Weblate. I haven’t tested them yet, but I will and I also hope I will come with some real tests to test this functionality in more or less real situations, especially those when it’s failing for me at the moment.
Thanks for considering this PR.
> Improve hg support

- docs/admin/deployments.rst
See https://github.com/WeblateOrg/docker/pull/32 and https://github.com/WeblateOrg/docker/pull/32#issuecomment-278365934.
> Document docker hub setup

- weblate/accounts/views.py
This pull request automatically fixes all occurrences of the following issue:
Issue type: [Consider an iterator instead of materializing the list](https://www.quantifiedcode.com/app/issue_class/53lnAzfW)
Issue details: [https://www.quantifiedcode.com/app/project/gh:WeblateOrg:weblate?groups=code_patterns/%3A53lnAzfW](https://www.quantifiedcode.com/app/project/gh:WeblateOrg:weblate?groups=code_patterns/%3A53lnAzfW)
To adjust the commit message or the actual code changes, just [rebase](https://git-scm.com/docs/git-rebase) or [cherry-pick](https://git-scm.com/docs/git-cherry-pick) the commits.
For questions or feedback reach out to cody@quantifiedcode.com.
Legal note: We won't claim any copyrights on the code changes.
Cheers,
[Cody - Your code quality …
> Fix "Consider an iterator instead of materializing the list" issue

- weblate/trans/machine/apertium.py
> added mapping

- examples/hook-merge-pot-in-po
> Add a post-update hook to merge PO templates into PO.

- docs/admin/deployments.rst
Environment variable added to Docker image in
https://github.com/WeblateOrg/docker/pull/37
> Document WEBLATE_EMAIL_PORT.

- setup.py
> Include examples in data files.

- weblate/api/urls.py
> fix typo in screenshots api

- docs/api.rst
> Fix type on Screenshots

- weblate/api/tests.py
- weblate/api/views.py
> Allow updating screenshots

- examples/hook-merge-pot-in-po
Fixes #1553
As mentioned in #1553, I wont be able to test this before monday. So be sure to test this on your side if you're willing to merge.
Thanks, and sorry again for having written the broken hook in the first place. 😕
> Fix merge-pot-in-po hook. 

- weblate/trans/ssh.py
> use exec in ssh wrapper to free up os resources

- docs/admin/projects.rst
> Added note about shared repository recommendation

- docs/admin/deployments.rst
sorry about the syntax, .rst is foreign to me :)
> add ldap examples/doc

- weblate/templates/widgets.html
Signed-off-by: Marc Delisle <marc@infomarc.info>
> Improve English

- weblate/locale/it/LC_MESSAGES/djangojs.po
> Update Italian djangos.po (new string)

- docs/admin/deployments.rst
> Add YunoHost package in deployments documentation

- docs/admin/deployments.rst
Oups, I'm not used to restructuredtext...
> Convert makdown image to restructured text image

- weblate/trans/tests/test_files.py
- weblate/trans/views/helper.py
> Flush pending changes before exporting file

- CONTRIBUTING.md
All other references to the GPL indicate version 3, so this is probably old information
Signed-off-by: Isaac Bennetch <bennetch@gmail.com>
> Increase GPL to v3

- weblate/templates/base.html
when installing weblate in a subpath, favicon still uses root's one, which is a bug ;)
I hope I used the correct way to fix this, I won't mind seeing this PR canceled if you wish to use another way.
> add path for favicon

- weblate/trans/vcs.py
Signed-off-by: Hao Hu <hao.hu@neoxam.com>
> fix the git compatibility issue for git svn

- weblate/templates/legend.html
De-clutters the interface a bit.
> - "translations"

- weblate/templates/progress.html
> no "translations"

- weblate/templates/subproject_info.html
> suggestions made, not given

- examples/hook-merge-pot-in-po
I apologize for having pushed such clumsy code in the first place. I should have tested it first, seriously. 🙄  Still, I finally found some time to test it and it worked at least once.
> Fix merge-pot-in-po hook.

- docs/admin/config.rst
- docs/admin/machine.rst
- weblate/settings_example.py
- weblate/trans/machine/saptranslationhub.py
- weblate/trans/models/conf.py
- weblate/trans/tests/test_machine.py
A machine translation plugin for the SAP Translation Hub.
More infos at https://api.sap.com/shell/discover/contentpackage/SAPTranslationHub/api/translationhub
> add MT plugin for SAP Translation Hub

- weblate/templates/mail/new_contributor.html
- weblate/templates/mail/new_contributor.txt
I got one e-mail just now that had no username, from "Weblate/Application: Languages"…
> Spelling: Good news, The user, contribution to

- weblate/accounts/notifications.py
> Notifications for new logins only

- weblate/templates/addons/generate_help.html
> Fixed typo

- weblate/trans/machine/saptranslationhub.py
by providing the source language, SAP Translation Hub returns better search results
> Improved search results for SAP Translation Hub

- weblate/templates/accounts/reset.html
Signed-off-by: Jesper Hertel <jesper.hertel@gmail.com>
> e-mail → email for consistency

- weblate/wladmin/templates/admin/trans/change_form.html
As per https://ell.stackexchange.com/questions/99635/in-bold-letters-vs-in-bold
Not 100% sure about "the object". Could the sentence be explained, what happens?
> Spelling: in bold, the object, the Weblate interface,

- docs/changes.rst
- weblate/trans/vcs.py
We have no interest in past revisions, so fetch only latest one.
Fixes #1778
> Limit depth of svn clone

- weblate/addons/gettext.py
As per https://toolkit.translatehouse.org/
and https://www.gnu.org/software/gettext/
> Spelling: Marked noun, MO, PO, POT, package names

- docs/admin/addons.rst
- docs/admin/management.rst
- docs/admin/projects.rst
- docs/changes.rst
- docs/formats.rst
- weblate/addons/discovery.py
- weblate/addons/forms.py
- weblate/addons/management/commands/list_addons.py
- weblate/addons/models.py
- weblate/addons/tests.py
- weblate/settings_example.py
- weblate/templates/addons/discovery_help.html
- weblate/templates/addons/discovery_preview.html
- weblate/trans/discovery.py
- weblate/trans/management/commands/import_project.py
- weblate/trans/models/conf.py
- weblate/trans/models/subproject.py
- weblate/trans/tests/test_commands.py
- weblate/trans/tests/test_discovery.py
- weblate/utils/render.py
- weblate/utils/validators.py
It it close match to import_project, but it is performed on every
update.
Fixes #802
Tasks:
> WIP: Add addon for component discovery

- scripts/yarn-update
- scripts/yarn/package.json
- weblate/static/loader-bootstrap.js
Minor cleanup after https://github.com/WeblateOrg/weblate/pull/2054
> Datepicker PR minor cleanup

- weblate/addons/forms.py
- weblate/trans/forms.py
- weblate/trans/models/component.py
Also, https://github.com/WeblateOrg/website/pull/34
As per https://www.gnu.org/software/gettext/ and https://en.wikipedia.org/wiki/Gettext
> Mid sentence gettext

- .travis.yml
It seems to be more widely used choice, so stick with that for our tests
as well.
> Use MariaDB for MySQL tests

- docs/admin/install.rst
> Only mention PyYAML once

- docs/api.rst
(Adding here because I didn't know about needing to sign-off before I committed to my fork.)
Signed-off-by: William Yznaga <wyznaga@gmail.com>
> Update api.rst to fix typos and edit for clarity

- docs/admin/quick.rst
Sorry, the numbers changed after I had first written this - I had made a mental note to fix it, but forgot... :-/
> Fix reference to numbers in QuickStart guide

- weblate/checks/models.py
- weblate/trans/discovery.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/utils/invalidate.py
There should be no need to do that several times over object lifetime
(what is typically request).
> Invalidate caches just once per request

- docs/admin/checks.rst
- docs/admin/config.rst
- docs/user/checks.rst
- weblate/checks/format.py
- weblate/checks/tests/test_format_checks.py
- weblate/settings_example.py
- weblate/trans/models/conf.py
> Add string formatting checks for C# and Java

- docs/admin/checks.rst
- docs/user/checks.rst
Signed-off-by: Tyler Rupert <Tyler.Rupert@hyland.com>
I missed an area in documentation for #2175 and fixed a typo.
> Updating string formatting documentation

- docs/changes.rst
- weblate/api/tests.py
- weblate/checks/consistency.py
- weblate/trans/admin.py
- weblate/trans/management/commands/benchmark.py
- weblate/trans/models/__init__.py
- weblate/trans/models/component.py
- weblate/trans/models/source.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/tests/test_edit.py
- weblate/trans/tests/test_models.py
- weblate/trans/tests/test_search.py
- weblate/trans/views/edit.py
In my test environment this reduces time for importing Weblate translations from 1012 to 756 seconds.
> WIP: Translation import performance improvements

- weblate/api/serializers.py
- weblate/api/views.py
> updating Upload request serializers with two additional fields #1866

- weblate/wladmin/templates/admin/performance.html
I am sure that this works, whereas the old one I am unsure of.
> Spelling: Your setup seems to work.

- docs/admin/addons.rst
> Fix typo in docs

- docs/admin/config.rst
- weblate/trans/models/conf.py
- weblate/vcs/git.py
> pull request default title setting

- docs/formats.rst
> Documented supported format capabilities

- weblate/static/loader-bootstrap.js
- weblate/templates/list-translations.html
> Adding Comments column to overview

- README.rst
- docs/admin/config.rst
- docs/admin/install.rst
- docs/admin/machine.rst
- docs/admin/management.rst
- docs/admin/optionals.rst
- docs/api.rst
- docs/contributing.rst
- docs/devel/starting.rst
- docs/formats.rst
- docs/internals.rst
- docs/user/translating.rst
- weblate/utils/requirements.py
I have tested the updated links.
> HTTPS links

- weblate/screenshots/views.py
- weblate/static/loader-bootstrap.js
- weblate/templates/screenshots/screenshot_detail.html
> Improved screenshot managment search window, added context and location

- weblate/templates/user-activity.html
> Added uploaded screenshots count to profile

- weblate/templates/glossary-embed.html
- weblate/templates/translate.html
> Glossary shrinked to two columns

- docs/contributing.rst
How does one do this the correct way?
> Workable URLs

- docs/admin/checks.rst
- docs/changes.rst
- docs/user/checks.rst
- weblate/checks/format.py
- weblate/checks/tests/test_format_checks.py
- weblate/trans/autofixes/custom.py
- weblate/trans/models/conf.py
- weblate/trans/tests/test_autofix.py
> Java messageformat

- weblate/machinery/youdao.py
> Update Youdao machine translation

- weblate/templates/dictionary.html
- weblate/trans/forms.py
- weblate/trans/tests/test_dictionary.py
- weblate/trans/views/dictionary.py
> Textual searchbox for glossaries

- docs/admin/machine.rst
> Fixing typo in machine.rst

- docs/contributing.rst
> Fix link syntax in docs

- docs/internals.rst
> Minor typo in docs

- weblate/trans/models/suggestion.py
- weblate/trans/tests/test_suggestions.py
- weblate/trans/tests/test_views.py
- weblate/trans/tests/utils.py
> Vote suggestion up instead of adding the same

- docs/user/checks.rst
BBCode, as per https://en.wikipedia.org/wiki/BBCode
> Checks and fixups language reworked

- docs/devel/reporting.rst
Is "Units" really the word for string count?
How/is rendering done per language?
> Language Reworked

- docs/admin/addons.rst
- docs/changes.rst
- weblate/addons/forms.py
- weblate/addons/git.py
- weblate/addons/models.py
- weblate/addons/tests.py
- weblate/trans/tests/test_edit.py
- weblate/trans/tests/test_views.py
> New addon to squash all changes prior to push

- docs/admin/upgrade.rst
- docs/changes.rst
- requirements.txt
- weblate/trans/simplediff.py
- weblate/utils/requirements.py
Now uses diff-match-patch with semantic cleanup. This seems to produce
nicely readable output in most cases.
Fixes #1570
> Improved displaying of translation changes

- weblate/addons/base.py
Commit log from addons is not sufficiently descriptive for projects with linked components. For example, after updating POT files, I get 50 individual commits that only contain in log: "Update translation files".
The attach patch adds the name of the component and, if it is a component linked from another project, also the name of the project. This makes commit log more useful – for example: "Update translation files tdegraphics / tdeiconedit".
> Improve commit log in addons for linked components

- openshift3/ephemeral-sqlite.json
- openshift3/persistent-mysql.json
- openshift3/persistent-postgresql.json
- openshift3/persistent-sqlite.json
- weblate/trans/util.py
There where some leftovers from @GrahamDumpleton 's fork, so I started with some small fixes, since in [last openshift issue](https://github.com/WeblateOrg/weblate/issues/1523) he mentioned he is finished with this. 
Otherwise this MR is a start of issue https://github.com/WeblateOrg/weblate/issues/2476
> Openshift3 deployment fixes

- weblate/settings_openshift.py
I was a bit too fast with previous pull request #2501 - forgot to commit also missing function.
> Bugfix: fixed missing function for WEBLATE_REQUIRE_LOGIN

- .gitignore
There are already other editors config in gitignore, I've added also VScode.
> Added VScode configuration to .gitignore

- weblate/settings_openshift.py
Added possibility of using other auth providers via configuration.
> Enable social auth also for openshift enviroment

- weblate/accounts/models.py
The current form of method:name can be confusing (eg. Password:user), so
better describe it with words.
> Improve audit log messages for authenticating

- weblate/trans/validators.py
> Typo fixed

- weblate/checks/base.py
- weblate/checks/consistency.py
- weblate/trans/models/component.py
- weblate/trans/models/source.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/tests/test_edit.py
- weblate/utils/unitdata.py
Several improvements in the importing code making it both more consistent and faster.
> Improve import code

- docs/vcs.rst
* Pull-request configuration is confused, try to clarify a bit how it works.
Signed-off-by: nailyk-fr <nailyk_git@nailyk.fr>
> Doc: VCS: Clarify pull-request setting

- docs/admin/config.rst
- docs/user/profile.rst
- weblate/accounts/models.py
- weblate/accounts/strategy.py
- weblate/accounts/tasks.py
- weblate/accounts/tests/test_registration.py
- weblate/accounts/tests/test_utils.py
- weblate/accounts/tests/test_views.py
- weblate/accounts/urls.py
- weblate/accounts/views.py
- weblate/settings_example.py
- weblate/templates/accounts/profile.html
- weblate/trans/tests/test_selenium.py
This feature allows user to download his data in the JSON format. This 
is mostly good for GDPR compliance where such export has to be provided
to the user and having that automated is better than handling such
requests manually.
> User data download

- weblate/trans/models/component.py
This resolves regression from commit 44aae51b71.
> Fix 'branch' rendering to repoweb url for linked components

- weblate/trans/models/suggestion.py
- weblate/trans/tasks.py
- weblate/trans/tests/test_tasks.py
MySQL is by default case insensitive, what leads suggestion cleanup to remove suggestions differing only in capitalization what is wrong.
> Fix suggestions cleanup with MySQL

- docs/formats.rst
Just some fixes to the new docs on "App store metadata"
> Docs: use more accurate links and examples for "App store metadata"

- docs/changes.rst
- weblate/formats/base.py
- weblate/formats/ttkit.py
- weblate/trans/models/translation.py
This should address https://github.com/WeblateOrg/weblate/issues/2668, looking for feedback.
> Xliff editing fixes

- weblate/trans/models/project.py
- one generic implementation for both source and target checks
- remove language filtering as there should not be same named checks for
both source and target
- properly delete check objects, it could delete too much
> Project: Share code for batch check execution

- docs/changes.rst
- weblate/checks/format.py
- weblate/checks/tests/test_checks.py
- weblate/checks/tests/test_format_checks.py
Should address format string check concerns from https://github.com/WeblateOrg/weblate/issues/2749
> Improve plurals handling in checks

- weblate/formats/tests/test_formats.py
- weblate/formats/ttkit.py
- weblate/trans/tests/data/ids-edited.xliff
- weblate/trans/tests/data/ids-translated.xliff
- weblate/trans/tests/data/ids.xliff
- weblate/trans/util.py
See discussion on https://github.com/WeblateOrg/weblate/issues/2668
This code really deserves some tests.
> Xliff fixes

- weblate/legal/templates/legal/security.html
Missing taken spotted by @velitasali on Hosted Weblate :)
Where is this used btw?
> - is seriously, Best practices, - stores all, Please see

- weblate/langdata/locale/fi/LC_MESSAGES/django.po
> Locales: Update Finnish language names to match CLDR

- docs/admin/quick.rst
Correcting a very little typo in the documentation.
> Minor typo

- .s2i/action_hooks/deploy
- .s2i/action_hooks/run
- .s2i/environment
- openshift3/persistent-mysql.json
- openshift3/persistent-postgresql.json
- scripts/openshift-celery-runner.py
- weblate/settings_openshift.py
Covers issues https://github.com/WeblateOrg/weblate/issues/2808 and https://github.com/WeblateOrg/weblate/issues/372
> Run celery also on openshift instance

- docs/admin/install.rst
Fixes https://github.com/WeblateOrg/weblate/issues/2840
> Add optional dependency ruamel.yaml to install.rst

- docs/admin/projects.rst
- docs/changes.rst
- weblate/static/loader-bootstrap.js
- weblate/templates/trans/component_create.html
- weblate/templates/trans/component_form.html
- weblate/trans/forms.py
- weblate/trans/tests/test_create.py
- weblate/trans/tests/test_selenium.py
- weblate/trans/views/create.py
- weblate/urls.py
- weblate/vcs/base.py
- weblate/vcs/git.py
- weblate/vcs/tests/test_vcs.py
Better guidance when creating new components.
> Customize component creation

- docs/admin/deployments.rst
> Clarify the HTTP header name requirements

- weblate/trans/forms.py
Does
"Specify configuration manually" mean 
"Configure manually?
> Spelling: to copy configuration from

- weblate/templates/trans/component_create.html
> Improve wording

- docs/admin/deployments.rst
Please wait until https://github.com/WeblateOrg/docker/pull/291 get merged
> docs(port): document the WEBLATE_PORT env var

- docs/formats.rst
> tiny grammar correction

- weblate/trans/widgets.py
As per https://ogp.me/
Btw, what does "Legacy badge which used to render PNG" mean?
> Spelling: Open Graph

- weblate/wladmin/forms.py
> Typo fixed, anter -> enter

- docs/changes.rst
- weblate/auth/models.py
- weblate/lang/forms.py
- weblate/lang/models.py
- weblate/lang/tests.py
- weblate/lang/views.py
- weblate/templates/lang/create.html
- weblate/templates/lang/language_form.html
- weblate/templates/language.html
- weblate/templates/languages.html
- weblate/trans/util.py
- weblate/urls.py
> Languages management in app

- docs/admin/checks.rst
- docs/user/checks.rst
- weblate/checks/models.py
- weblate/checks/qt.py
- weblate/checks/ruby.py
- weblate/checks/same.py
- weblate/checks/tests/test_format_checks.py
- weblate/settings_example.py
Hi, please see the commit messages for details
> Add checks for Qt library and Ruby format strings

- weblate/templates/trans/component_create.html
- weblate/wladmin/forms.py
Is it always "ZIP", or should it be "compressed file"?
> Spelling: Reworked. -the, containing strings, create a ZIP

- docs/admin/install/venv-debian.rst
https://docs.weblate.org/en/latest/admin/install/venv-debian.html
> Missing Git in Documentations

- docs/index.rst
- docs/user/search.rst
- weblate/screenshots/views.py
- weblate/utils/search.py
- weblate/utils/tests/test_search.py
Query parser for advanced search (#2643, #2455)
Todo:
> Avanced search

- weblate/templates/manage/backups.html
Spotted by [@mesutakcan](https://hosted.weblate.org/user/mesutakcan/)
> backups: Fix typo in repository

- docs/admin/customize.rst
- docs/internals.rst
> rephrase a bit, remove trailing whitespace

- docs/admin/install/docker.rst
> Showing that "Enabled" variables should be set to 1

- docs/user/basic.rst
> Fix a typo in the project structure introduction document

- docs/admin/continuous.rst
Signed-off-by: Frans de Jonge <fransdejonge@gmail.com>
> Docs: fix a few typos

- docs/user/checks.rst
- weblate/checks/chars.py
- weblate/checks/models.py
- weblate/checks/tests/test_chars_checks.py
- weblate/settings_docker.py
- weblate/settings_example.py
> Adding doublespace check

- docs/admin/upgrade.rst
- docs/changes.rst
- docs/user/translating.rst
- requirements.txt
- setup.cfg
- weblate/accounts/notifications.py
- weblate/templates/list-comments.html
- weblate/trans/forms.py
- weblate/trans/models/comment.py
- weblate/trans/templatetags/translations.py
- weblate/utils/markdown.py
- weblate/utils/tests/test_markdown.py
> Comments: Add markdown support

- weblate/locale/id/LC_MESSAGES/django.po
> Update id language django.po

- weblate/vcs/mercurial.py
https://github.com/WeblateOrg/weblate/issues/3181
> Mercurial: Fixed processing of repositories with closed namesake heads

- weblate/static/bootstrap/css/bootstrap.css
Fixed #3172 (Reported by myself, thanks @nijel for explaining the right course of action! :tada:)
> Correctly aligned follow menu in RTL interface

- docs/changes.rst
As per https://en.wikipedia.org/wiki/XLIFF
docs.translatehouse.org/projects/amagama/en/latest/
https://python-zeep.readthedocs.io/en/master/
https://github.com/tesseract-ocr/tesseract
https://github.com/WeblateOrg/weblate/commit/fe83b5308161af0018f73b3d38ffaa935d55ffc3
> Changelog language reworked

- docs/admin/install/docker.rst
this documentation changes are related to: 
* https://github.com/WeblateOrg/docker/pull/489 to provide LAB in the docker images
* https://github.com/WeblateOrg/docker-compose/pull/13 to describe configuration in docker-compose
This is an additional change to support #3318
> Docs: add lab ENV variables for docker setup

- docs/api.rst
- docs/changes.rst
- weblate/api/tests.py
- weblate/api/views.py
Fix creation translation via REST API
Issue #3253
Signed-off-by: Aleksandr Loktionov <loktionovam@gmail.com>
> API: Creates new translation in the given component.

- docs/admin/install/docker.rst
- weblate/settings_docker.py
> Add ability to configure AWSTranslation via environment variables

- .travis.yml
This is mostly to see if everything is working as expected on Travis CI.
> Tests: Switch Travis CI to bionic

- weblate/checks/__init__.py
- weblate/trans/models/unit.py
Filter the checks once and use correct list on execution.
> Unit: Improve checks execution performance

- docs/changes.rst
- weblate/checks/base.py
- weblate/checks/format.py
- weblate/checks/models.py
- weblate/checks/placeholders.py
- weblate/checks/render.py
- weblate/checks/tests/test_models.py
- weblate/checks/views.py
- weblate/fonts/utils.py
- weblate/urls.py
> Show image from render check

- weblate/checks/tests/test_views.py
- weblate/checks/views.py
- weblate/templates/component.html
Hey,
I just added another query parameter to the component.html template, that then filters the component__slug field on the existing queryset.
Let me know if it's alright.
---
Signed-off-by: Burzo <miha.drofenik92@gmail.com>
> Added per component individual checks

- docs/contributing.rst
Signed-off-by: Burzo <miha.drofenik92@gmail.com>
Just some small tweaks to the docs that should help any newcommers.
> Add to docs

- docs/changes.rst
As per
https://en.wikipedia.org/wiki/Markdown
https://borgbackup.readthedocs.io/en/stable
https://en.wikipedia.org/wiki/Webhook
> Newer changelogs reworked

- docs/admin/config.rst
- weblate/trans/tasks.py
(True,False)-> (full,remote,none)
attempt to resolve #3341
> Settings: add more options to AUTO_UPDATES

- weblate/templates/base.html
> use `default` filter

- .github/workflows/migrations.yml
- .github/workflows/setup.yml
- .github/workflows/test.yml
- ci/docker-compose-postgresql.yml
- ci/postgres/postgres-nondurable.sh
- ci/services-down
- ci/services-up
It should bring additional performance at rist of losing data,
what we do not care about in the tests.
> CI: Use non-durable settings for postgres

- weblate/templates/accounts/redirect.html
Could be this is meant to be there.
> Spelling: Whitespace removed

- setup.cfg
- setup.py
- weblate/accounts/tests/test_avatars.py
- weblate/accounts/tests/test_registration.py
- weblate/machinery/tests.py
- weblate/wladmin/tests.py
Attemptedly fixes: #3536
https://github.com/gabrielfalcao/httpretty
https://github.com/getsentry/responses
> Replace HTTPretty with Responses

- docs/admin/config.rst
- docs/admin/machine.rst
- weblate/machinery/microsoft.py
- weblate/machinery/models.py
- weblate/machinery/tests.py
- weblate/settings_example.py
> patch for #3526 Change Microsoft API to V3

- weblate/checks/same.py
- weblate/checks/tests/test_same_checks.py
> Checks: Unchanged translation incorporate placeholders flag

- weblate/checks/base.py
> Checks: simplify check_chars method

- docs/devel/index.rst
This needs a lot of work it seems(?)
> Application developer guide documentation reworked

- docs/admin/projects.rst
Just skimmed through this one.
> Translation projects documentation reworked

- docs/admin/checks.rst
https://docs.weblate.org/en/latest/admin/checks.html and https://docs.weblate.org/en/latest/user/checks.html are both called "Checks and fixups", that isn't ideal.
> Checks and fixups documentation reworked

- docs/admin/addons.rst
A bit tired, but I don't get all the "This way you can easily filter" in the
"Flag * as “Needs editing" sections.
Edit: In case anyone wants the web admin panel to review:
> Addons documentation reworked

- docs/admin/backup.rst
Minor typos and language improvements
> Backup documentation

- docs/admin/backup.rst
Suggests a command line using tar and xz to do the backup with a cron task.
> Command line for manual backup

- docs/admin/whiteboard.rst
@orangesunny Looks good to me now.
> Whiteboard messages documentation reworked

- weblate/vcs/base.py
> VCS: Set path to SSH wrapper for Subversion

- docs/api.rst
- weblate/api/serializers.py
- weblate/api/tests.py
> Allows source language to be added in the project API

- docs/changes.rst
- docs/user/files.rst
- weblate/api/serializers.py
- weblate/api/views.py
- weblate/auth/permissions.py
- weblate/formats/ttkit.py
- weblate/trans/forms.py
- weblate/trans/models/translation.py
- weblate/trans/tests/test_create.py
- weblate/trans/tests/test_files.py
- weblate/trans/util.py
> Msgmerge upload

- docs/api.rst
- docs/changes.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/urls.py
- weblate/api/views.py
- weblate/auth/data.py
> API: Add component lists API

- docs/user/profile.rst
- weblate/templates/base.html
- weblate/templates/dashboard/user.html
- weblate/trans/tests/test_selenium.py
Remove Tools menu from the dashboard - project and languages are in top menu, search can be directly accessible.
> Flatten menu

- docs/user/checks.rst
> Usage of "Use this string" button

- docs/api.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/urls.py
- weblate/api/views.py
- weblate/auth/data.py
Currently Done:
- Adds basic endpoint for User to create, patch, list and delete user
- Adds basic endpoint for Group to create, patch, list and delete Group based on the non-relational fields.
Needs to be done:
Fixes #3607
> Creates basic API endpoints for users and groups

- weblate/accounts/views.py
- [✓] Every commit has a message which describes it
- [✓] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them
- [✓] Any code changes come with test case
- [✓] Any new functionality is covered by user documentation
> Add missing whitespace character

- docs/api.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/views.py
- Adds Role API to create roles with permissions, edit roles, add permission codenames to roles and remove roles.
- Assign roles to a group
- Assign projects, components, componentlist to a group
Fixes #3647
> Adds basic API endpoints for roles and assign roles to groups

- weblate/trans/models/change.py
Spotted and researched by @tjhietala at https://hosted.weblate.org/user/tjhietala :)
https://hosted.weblate.org/translate/weblate/master/en/?checksum=b1e9ab85c10bfb1e
> Spelling: "Added to glossary"

- weblate/machinery/tests.py
- weblate/memory/tests.py
- weblate/screenshots/tests.py
- weblate/trans/tests/test_autotranslate.py
- weblate/trans/tests/test_dictionary.py
- weblate/trans/tests/test_search.py
- weblate/trans/tests/test_views.py
We should try to address individual test cases.
> Tests: Remove MySQL workaround

- weblate/utils/checks.py
However cute this is,
[The Celery does not process tasks](https://github.com/WeblateOrg/weblate/blob/159c4574b74b7d61feb29344211b352f097d66fb/weblate/utils/checks.py#L200)
[The Celery is not configured](https://github.com/WeblateOrg/weblate/blob/159c4574b74b7d61feb29344211b352f097d66fb/weblate/utils/checks.py#L208)
Celery queue, worker?
> Spelling: Checks.py error messages reworked

- docs/admin/install/docker.rst
- weblate/settings_docker.py
- [-] Any code changes come with test case
> Expose SENTRY_ENVIRONMENT as environment variable for docker

- docs/admin/install/venv-macos.rst
i followed Installing on macOS and successfully installed and used weblate on my device. so no need for warning message
> tested macos installation

- weblate/static/loader-bootstrap.js
- weblate/static/style-bootstrap.css
- weblate/templates/paginator.html
- weblate/templates/translate.html
- weblate/trans/views/search.py
Addresses inline editing of position in #3308
> Adds inline editing of position in translate page

- docs/admin/deployments.rst
> Add information about the helm chart

- docs/admin/deployments.rst
> Adjust helm repo location

- docs/admin/install/docker.rst
> Updated port change message

- docs/admin/install/venv-macos.rst
> Docs: clarify Mac dependencies

- docs/admin/install.rst
Fixes some minor issues found while reading through docs.
> Docs: installation fixes

- docs/changes.rst
- docs/user/checks.rst
- weblate/checks/base.py
- weblate/checks/chars.py
- weblate/checks/consistency.py
- weblate/checks/duplicate.py
- weblate/checks/format.py
- weblate/checks/markup.py
- weblate/checks/models.py
- weblate/checks/placeholders.py
- weblate/checks/render.py
- weblate/checks/same.py
- weblate/checks/source.py
- weblate/checks/tests/test_models.py
- weblate/checks/tests/test_views.py
- weblate/checks/views.py
- weblate/templates/check.html
- weblate/templates/check_component.html
- weblate/templates/check_project.html
- weblate/templates/checks.html
- weblate/templates/component.html
- weblate/templates/language-project.html
- weblate/templates/language.html
- weblate/templates/snippets/project-nav.html
- weblate/trans/templatetags/translations.py
Also show dismissed or translated counts to get better overview. This
removes need to have separate view for ignored checks and makes the
check pages more useful to see how big problem it is.
Fixes #1368
> Checks: Show more detailed check status

- weblate/templates/snippets/query-field.html
- weblate/trans/models/unit.py
- weblate/trans/tests/test_models.py
- weblate/utils/views.py
Adds the following sortings:
- Labels
- Age of string
- Number of failing checks
- Number of comments
Refs #3710
> Adds additing string ordering in the query tool

- docs/user/translating.rst
These were not in sync with actual functionality.
> Docs: fix shortcuts reference

- docs/changes.rst
- docs/formats.rst
- requirements-optional.txt
- weblate/formats/models.py
- weblate/formats/tests/test_formats.py
- weblate/formats/ttkit.py
- weblate/trans/tests/data/cs.ini
- weblate/trans/tests/data/cs.joomla.ini
- weblate/trans/tests/test_component.py
- weblate/trans/tests/utils.py
> Formats: Add support for generic INI files

- weblate/static/loader-bootstrap.js
> Cleanup: remove dead code

- requirements.txt
There seems to be some issue older lxml versions causing breakage in the xliff, trying to find minimal version that will work.
> Deps: Increase minimal lxml version

- docs/admin/config.rst
- docs/admin/install/docker.rst
- weblate/machinery/microsoft.py
- weblate/machinery/models.py
- weblate/settings_docker.py
> MT: Support for Azure China

- weblate/trans/models/unit.py
- weblate/trans/tests/test_models.py
> Fixes label sort failure in descending order

- weblate/machinery/microsoft.py
Microsoft Translator supported languages: 
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/language-support
> MT: Update language map for Chinese

- docs/admin/auth.rst
- weblate/settings_docker.py
- weblate/settings_example.py
See e.g. https://blog.fleetsmith.com/password-security-guide/
> Increase minimum password length to 10

- docs/make.bat
As per
https://en.wikipedia.org/wiki/EPUB
https://doc.qt.io/archives/qt-4.8/qthelp-framework.html
https://doc.qt.io/qt-5/qthelp-index.html
> Spelling: EPUB, https://, Qt help

- docs/admin/install/docker.rst
- weblate/settings_docker.py
- weblate/utils/environment.py
- weblate/utils/tests/test_environment.py
Fixes https://github.com/WeblateOrg/docker/issues/645
> Docker: Allow to configure default access control

- docs/changes.rst
- docs/formats.rst
- weblate/addons/properties.py
- weblate/formats/models.py
- weblate/formats/tests/test_formats.py
- weblate/formats/ttkit.py
- weblate/trans/tests/data/gwt.properties
Depends on https://github.com/translate/translate/pull/4030
Fixes #2661
> Formats: Add support for GWT

- weblate/machinery/microsoft.py
- weblate/machinery/mymemory.py
https://docs.microsoft.com/ko-kr/azure/cognitive-services/translator/language-support
https://mymemory.translated.net/doc/spec.php
- [o] Every commit has a message which describes it
- [o] Every commit is needed on its own, if you have just minor fixes to previous commits, you can squash them
> [machine translation] fix microsoft cognitive, and mymemory to use language sub-code

- weblate/utils/requirements.py
> Added database(PostgreSQL/MySQL)/ cache(Redis) server versions

- docs/api.rst
> Adds better API docs to create HyperLinked POST requests

- weblate/machinery/base.py
- weblate/machinery/tests.py
> Machinery: Rewrite tests

- docs/admin/projects.rst
- weblate/trans/models/component.py
- weblate/vcs/base.py
- weblate/vcs/git.py
> VCS push with blank URL

- weblate/static/editor.js
While going through the code for giving it some structure, I spotted some unnecessary checks and naming inconsistencies.
> Editor: cleanup nesting and variable names

- docs/contributing/frontend.rst
> Docs: fix typos

- docs/api.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/views.py
> Adds API for monolingual languages

- weblate/static/editor/base.js
* Makes highlight initialization explicit
* Factors out its selectors
> Editor: factor out selectors

- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/trans/models/project.py
- weblate/trans/models/translation.py
- weblate/trans/views/api.py
> Get stats cleanup

- docs/api.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/views.py
> Allows PATCH and PUT request to edit components

- docs/api.rst
- weblate/api/tests.py
- weblate/api/views.py
> Componentlists disassociate

- weblate/static/editor/base.js
Or should we rather inline it?
> getNumericKey: simplify implementation

- docs/admin/management.rst
I also have a question relating to auto translation:
In the GUI i cannot find a button to auto translate a **whole project** (all components) using machine translation for a given language.
Can this management command be used for this purpose?  If yes, how?
Components seems to be a mandatory argument, even if `--mt` is specified.
> management command missing from example

- docs/api.rst
- weblate/api/tests.py
- weblate/api/views.py
> Automatic translation trigger via API

- requirements.txt
- weblate/addons/yaml.py
- weblate/formats/convert.py
Drop compatibility code with older releases.
> Deps: Require translate-toolkit 3.0.0

- weblate/static/editor/full.js
* Refactors machinery-related code
* Converts success/error processing logic into methods to further reuse cached objects
* Fixes machinery keyboard shortcut bugs (#3911)
@nijel please make sure to check the rendering of MT & TM results — I didn't touch the code to render machinery result rows but I wouldn't be surprised if other changes broke something related to it because it's pretty fragile in its current shape.
> Editor: refactor machinery code

- weblate/addons/base.py
- weblate/addons/tests.py
- weblate/formats/ttkit.py
- weblate/gitexport/utils.py
- weblate/utils/backup.py
- weblate/utils/tasks.py
- weblate/vcs/base.py
- weblate/vcs/gpg.py
- weblate/vcs/ssh.py
- weblate/vcs/tests/test_gpg.py
Avoid manually decoding or coping with mixed output when we
can now rely on Python 3.5+ features.
> Use Python 3.5 subprocess features

- docs/api.rst
- weblate/formats/exporters.py
- weblate/formats/tests/test_exporters.py
Right now JSON, Android and iOS are supported.
Fixes #3462
> Formats: Add monolingual exporters

- docs/api.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/views.py
> Adds subscriptions API associated with User

- docs/admin/auth.rst
- weblate/api/views.py
- weblate/formats/exporters.py
- weblate/formats/models.py
- weblate/glossary/views.py
- weblate/templates/glossary.html
- weblate/trans/forms.py
- weblate/trans/views/basic.py
- weblate/utils/views.py
Added EXPORTERS under formats/models.py, which can be customized to enable/disable certain exporter.
> Register Exporters in Settings

- docs/admin/install/docker.rst
> Docs: Expand how to use HTTPS in docker installations

- requirements.txt
> methodtools version >=0.4.2 to avoid setup errors

- docs/changes.rst
- weblate/accounts/urls.py
- weblate/accounts/views.py
- weblate/api/urls.py
- weblate/memory/tests.py
- weblate/memory/views.py
- weblate/templates/memory/index.html
- weblate/trans/views/hooks.py
- weblate/urls.py
- weblate/utils/urls.py
- weblate/wladmin/templates/admin/weblate-index.html
- weblate/wladmin/views.py
- switch to modern Django way of specifying patters using path/re_path
- drop some legacy redirects
- simplify handling of global memory manage pages
- deal with missing hooks handlers in hooks code
> URL: Remove legacy code

- weblate/trans/forms.py
- weblate/trans/models/component.py
Unsure what "Remove add as translation choice." means.
> Spelling: Conflict handling, the option

- .github/ISSUE_TEMPLATE/bug_report.md
> bug_report.md: typo

- docs/admin/addons.rst
- docs/admin/admin.rst
- docs/admin/config.rst
- docs/admin/install.rst
- docs/admin/install/source.rst
- docs/admin/projects.rst
- docs/changes.rst
- docs/contributing/tests.rst
- docs/formats.rst
More misspellings in Weblate Documentation spotted by the eagle-eyed @yurchor 
> Fix more misspellings

- docs/admin/access.rst
- docs/admin/checks.rst
- docs/admin/config.rst
- docs/admin/continuous.rst
- docs/admin/install.rst
- docs/admin/memory.rst
- docs/changes.rst
- docs/contributing/code.rst
- docs/contributing/debugging.rst
- docs/contributing/index.rst
- docs/devel/starting.rst
- docs/user/checks.rst
- docs/user/search.rst
- docs/user/translating.rst
- docs/vcs.rst
Errors spotted by @yurchor and @rffontenelle, and created by @comradekingu :)
> Spelling: Repeated words

- docs/admin/access.rst
- docs/admin/config.rst
- docs/admin/install/docker.rst
- docs/admin/machine.rst
- docs/contributing/code.rst
As per https://amagama.translatehouse.org/
> Spelling: Various fixes and cleanup

- docs/admin/access.rst
- docs/admin/addons.rst
- docs/admin/auth.rst
- docs/admin/backup.rst
- docs/admin/checks.rst
- docs/admin/componentlists.rst
- docs/admin/config.rst
- docs/admin/install.rst
- docs/admin/install/docker.rst
- docs/api.rst
- docs/contributing/release.rst
- docs/formats.rst
- docs/legal.rst
- docs/user/checks.rst
- docs/user/translating.rst
- weblate/fonts/views.py
> Fix minor issues in strings

- docs/admin/config.rst
- docs/admin/management.rst
Many thanks in advance for reviewing.
> Fix minor typos in docs

- docs/user/files.rst
- docs/user/profile.rst
- docs/workflows.rst
> Some small fixes to docs

- docs/admin/config.rst
- docs/admin/customize.rst
- docs/api.rst
> Fix two minor typos in docs

- docs/admin/checks.rst
- docs/admin/customize.rst
- docs/admin/projects.rst
- docs/admin/upgrade.rst
Another bunch of minor typo fixes. Thanks in advance for reviewing.
> Fix minor typos

- docs/faq.rst
Thanks in advance for fixing the typo.
> Fix typo: Weblte -> Weblate

- docs/admin/install/docker.rst
As per
https://en.wikipedia.org/wiki/UWSGI
https://github.com/docker/machine
> Spelling: Back-end, except, uWSGI, Docker Machine, the, container

- docs/admin/componentlists.rst
Spotted by @tonywang5 on Weblate :)
> Spelling: Missing text added "you want to have …"

- docs/admin/install/docker.rst
> Spelling: E-mail, in the header

- docs/admin/config.rst
- docs/admin/install.rst
- docs/admin/install/docker.rst
- docs/admin/languages.rst
- docs/admin/machine.rst
- docs/admin/management.rst
- docs/admin/optionals.rst
- docs/api.rst
- docs/formats.rst
- docs/user/translating.rst
- docs/vcs.rst
> Fix various issues found by translators

- docs/faq.rst
- docs/user/translating.rst
Many thanks in advance for reviewing.
> Various minor fixes by Weblate translators

- dev-docker/README.rst
> Docs: Fix dev-docker broken link

- weblate/templates/mail/billing_expired.html
> Fix typo found by Rafael Fontenelle

- docs/admin/auth.rst
- docs/admin/config.rst
- docs/admin/translating.rst
- docs/devel/community.rst
- docs/user/translating.rst
> Various fixes by Weblate translators

- weblate/accounts/views.py
Fix user list sorting issue. Retain search term and sort order in URL query string on click on page navigation buttons.
Related issue: https://github.com/WeblateOrg/weblate/issues/4452
> User List Sorting Fix

- docs/admin/config.rst
> Fix typo found by Weblate translator

- docs/api.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/urls.py
- weblate/api/views.py
- weblate/glossary/models.py
> Adds glossary API

- docs/admin/install/docker.rst
- weblate/settings_docker.py
Ref https://github.com/WeblateOrg/docker/issues/827
> Adds support for Apertium-APy in Docker

- docs/api.rst
- docs/changes.rst
- weblate/addons/cleanup.py
- weblate/api/tests.py
- weblate/api/views.py
- weblate/auth/data.py
- weblate/auth/permissions.py
- weblate/formats/base.py
- weblate/formats/ttkit.py
- weblate/formats/txt.py
- weblate/templates/translate.html
- weblate/trans/models/translation.py
- weblate/trans/tests/test_edit.py
- weblate/trans/views/edit.py
- weblate/urls.py
It used recently introduced removeunit API in the translate-toolkit.
Issue #1974
> Add support for unit removal 

- weblate/addons/gettext.py
- weblate/auth/permissions.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/templatetags/translations.py
- weblate/trans/tests/test_component.py
- weblate/trans/tests/test_templatetags.py
This allows it to report proper location or load additional metadata from it.
> Load pot when parsing files

- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/utils/stats.py
This heavily reduces amount of cache calls for deep invalidations.
> Stats: Use delete_many for invalidating stats

- docs/api.rst
> Fix minor typo found by Mingun

- weblate/auth/permissions.py
- weblate/screenshots/views.py
- weblate/templates/translate.html
- weblate/trans/views/edit.py
- weblate/trans/views/js.py
> Unitdata permission

- docs/admin/customize.rst
> Fix typo found by Kyotaro Iijima

- ci/run-migrate
> CI: Use new pip resolver to better detect problems in deps

- docs/admin/install/docker.rst
I think this is a typo because it refers to the file mentioned above.
> Dash instead of a dot

- docs/api.rst
> Fix minor typo

- weblate/memory/migrations/0008_adjust_similarity.py
It could contain special chars.
Fixes #4664
> Migrations: Quote username before using it in a query

- weblate/templates/addons/js/weblate.js
This avoids need to fetch them again in case of multi page app.
> Addons: Cache translations in CDNJS in session storage

- weblate/trans/models/unit.py
There is no need to do full row update here.
> Unit: Save only affected field on translate

- .github/workflows/test.yml
- docs/changes.rst
- requirements-test.txt
- setup.py
> CI: Test Python 3.9

- .github/ISSUE_TEMPLATE/config.yml
> rewording issue reporting topics

- .github/ISSUE_TEMPLATE/bug_report.md
> clarification of bug report template

- .github/ISSUE_TEMPLATE/feature_request.md
> small rewording of feature request template

- .github/ISSUE_TEMPLATE/support_question.md
> rewording, additions to support question template

- .github/PULL_REQUEST_TEMPLATE.md
got irritated as I saw it multiple times :)
> adding articles and semicolon

- docs/admin/install/openshift.rst
> udpate installing on openshift documentation

- .github/workflows/openshift.yml
> CI: Add basic test for OpenShift integration

- docs/changes.rst
> Fix minor typo found by Tony Wang

- docs/admin/access.rst
several Libre project admins asked about the permissions, so I made the documentation clearer for them
> adding notes to prevent Libre admins asking permissions

- weblate/addons/tasks.py
- weblate/api/views.py
- weblate/trans/models/translation.py
- weblate/trans/tests/test_shaping.py
- weblate/trans/views/edit.py
Use dictionary based args to add single unit as well. This
simplifies the code.
> Translation: Simplify interface to add units

- requirements.txt
- weblate/lang/data.py
- weblate/lang/models.py
It contains it in the new release, so let's utilize it.
> Lang: Use RTL data from language-data

- docs/changes.rst
- scripts/yarn-update
- scripts/yarn/package.json
- scripts/yarn/yarn.lock
- weblate/static/editor/base.js
- weblate/static/editor/full.js
- weblate/static/editor/zen.js
- weblate/static/loader-codemirror.js
- weblate/templates/base.html
- weblate/trans/tests/test_selenium.py
* Replace textarea by CodeMirror
* Make the length restriction softer (fixes #3662)
* Improved handling of fuzzy toggler (fixes #3910)
* Remove autosizer dependency as this is now done by CodeMirror
> Translate: Use CodeMirror to edit translations

- .github/workflows/docs.yml
- .readthedocs.yml
- ci/apt-install
- docs/conf.py
- weblate/trans/models/_conf.py
Use mocking instead of installing all deps.  We really do not need them and installing on readthedocs.org is not possible.
> Docs build fixes

- weblate/templates/accounts/hosting.html
Added points about repository and README file. 
Reworded approval point.
> clarification

- docs/admin/projects.rst
- docs/changes.rst
- docs/formats.rst
- weblate/formats/base.py
- weblate/formats/tests/test_formats.py
- weblate/trans/models/component.py
- weblate/trans/models/project.py
- weblate/trans/tests/test_component.py
- weblate/trans/tests/test_newlang.py
- weblate/trans/tests/test_views.py
- store filename language in the database to avoid need to change this
when aliases are changed
- apply aliases when creating new languages
- avoid double calculation of language code when adding new file
> Component: Improved support for non standard language codes

- weblate/templates/accounts/hosting.html
> Fix typo: finnish -> finish

- weblate/addons/base.py
- weblate/addons/discovery.py
> Fix minor typo: for for -> form for

- weblate/auth/permissions.py
- weblate/lang/views.py
- weblate/templates/language-project.html
- weblate/templates/trans/delete-project-language.html
- weblate/trans/forms.py
- weblate/trans/tests/test_manage.py
- weblate/trans/views/basic.py
- weblate/trans/views/settings.py
- weblate/urls.py
- weblate/utils/stats.py
- weblate/utils/views.py
It is sometimes handy to remove translation added to all components
thanks to language consistency addon.
> Project: Add support for removing language

- weblate/templates/accounts/hosting.html
> rewording of the complicated sentence

- weblate/trans/tests/test_hooks.py
- weblate/trans/views/hooks.py
This PR should fix #4894 and also enables structured branch names (e.g. feat/localization). I tried to support as many possible URL combinations that I am aware of. What I didn't add yet is unit test but would be nice to get a first feedback on the change even without tests. I'll add them with another commit soon.
> Improve support for Azure Repositories

- docs/admin/checks.rst
> Fix typo: provide -> provides

- docs/admin/install/steps/hw.rst
> Fix typo: swallow -> shallow

- docs/devel/integration.rst
> Fix typo: acces -> access

- weblate/checks/tests/test_checks.py
- weblate/examples/mt_service.py
- weblate/machinery/apertium.py
- weblate/machinery/aws.py
- weblate/machinery/baidu.py
- weblate/machinery/base.py
- weblate/machinery/deepl.py
- weblate/machinery/dummy.py
- weblate/machinery/glosbe.py
- weblate/machinery/google.py
- weblate/machinery/googlev3.py
- weblate/machinery/microsoft.py
- weblate/machinery/microsoftterminology.py
- weblate/machinery/modernmt.py
- weblate/machinery/mymemory.py
- weblate/machinery/netease.py
- weblate/machinery/saptranslationhub.py
- weblate/machinery/tests.py
- weblate/machinery/tmserver.py
- weblate/machinery/weblatetm.py
- weblate/machinery/yandex.py
- weblate/machinery/youdao.py
- weblate/memory/machine.py
- weblate/memory/models.py
- weblate/memory/tests.py
- weblate/trans/autotranslate.py
- weblate/trans/models/unit.py
Introduce batch interface to machinery to allow more effective lookups with some backends.
Fixes #3393
> Machinery batching

- weblate/accounts/notifications.py
- weblate/accounts/pipeline.py
- weblate/accounts/tests/test_views.py
- weblate/api/views.py
- weblate/checks/tests/test_models.py
- weblate/formats/tests/test_formats.py
- weblate/gitexport/views.py
- weblate/glossary/views.py
- weblate/lang/models.py
- weblate/lang/tests.py
- weblate/machinery/microsoftterminology.py
- weblate/machinery/weblatetm.py
- weblate/memory/models.py
- weblate/memory/views.py
- weblate/trans/forms.py
- weblate/trans/models/alert.py
- weblate/trans/models/change.py
- weblate/trans/models/component.py
- weblate/trans/stats.py
- weblate/trans/templatetags/translations.py
- weblate/trans/tests/test_autofix.py
- weblate/trans/util.py
- weblate/trans/views/edit.py
- weblate/trans/views/files.py
- weblate/trans/widgets.py
- weblate/utils/errors.py
- weblate/utils/forms.py
- weblate/utils/request.py
- weblate/vcs/ssh.py
These mostly come from Python 2 time and should not be needed now.
> Misc: Remove not used force_str invocations

- weblate/templates/trans/alert/nolibreconditions.html
This project**s** does not -> this project does not
> Fix wrong plural in projects

- docs/changes.rst
- weblate/trans/views/files.py
- weblate/utils/views.py
Fixes #5021
Generate context aware filename for downloads.
> Files: Improved naming of ZIP downloads

- weblate/trans/models/unit.py
- weblate/trans/tests/test_edit.py
The code was over-optimized and did not run propagated checks at all in
some cases.
Fixes #5025
> Unit: Fix triggering checks on propagation

- docs/admin/translating.rst
Spotted by @Fat-Zer over at Weblate :)
> Spelling: one signed-in, .

- weblate/trans/models/component.py
this clarification is based on the suggestion from @pierotofy. Thanks!
> clarification of suggestion settings

- docs/admin/upgrade.rst
- docs/changes.rst
- weblate/formats/ttkit.py
Sometimes both are used and needed to differentiate scope of the
translation.
Fixes #4130
> Formats: Extract both context and source from monolingual PO files

- weblate/trans/tests/test_util.py
- weblate/trans/util.py
Add conversion of unicode surrogates when parsing translation files.
Fixes #5041
> Fixed handling of unicode surrogates

- docs/changes.rst
subj; just add missing dots on the end of the changelog entries for similarity.
> Docs: minor fixup of dots on the changelogs

- weblate/auth/models.py
> Models.py page language reworked

- docs/changes.rst
In my head "administering users" means sending them places.
> Changelog list reworked

- docs/changes.rst
- weblate/formats/base.py
- weblate/formats/convert.py
- weblate/formats/ttkit.py
- weblate/formats/txt.py
- weblate/trans/models/component.py
- weblate/trans/views/basic.py
- weblate/trans/views/dashboard.py
This is expensive operation and should be done only when needed and not
when just browsing pages to figure out whether user can add language or
not.
Fixes #5152
> Component: Avoid parsing new base when checking for add permission

- requirements-optional.txt
- requirements.txt
Bumps [social-auth-core](https://github.com/python-social-auth/social-core) from 3.3.3 to 4.0.2.
- [Release notes](https://github.com/python-social-auth/social-core/releases)
- [Changelog](https://github.com/python-social-auth/social-core/blob/master/CHANGELOG.md)
- [Commits](https://github.com/python-social-auth/social-core/compare/3.3.3...4.0.2)
Signed-off-by: dependabot[bot] <support@github.com>
> Bump social-auth-core from 3.3.3 to 4.0.2

- docs/devel/integration.rst
> Integration documentation reworked

- docs/api.rst
- docs/changes.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/api/urls.py
- weblate/api/views.py
Adds API endpoint for addons.
Fixes #3948
> API: Add addons

- docs/changes.rst
- weblate/checks/base.py
- weblate/checks/consistency.py
- weblate/checks/tasks.py
- weblate/trans/models/change.py
- weblate/trans/models/component.py
These are expensive and most units will not have any hits. Offloading
this to background task will make the visual performance much better
while keeping the ability of the check to highlight potential issues.
> Checks: Batch consistency checks execution on update

- docs/changes.rst
- weblate/machinery/weblatetm.py
- weblate/memory/machine.py
- weblate/memory/models.py
- weblate/utils/db.py
While there is a good reason in having small similarity for short
strings, it is not that useful for huge ones.
> db: Dynamically scale search similarity

- requirements.txt
- weblate/settings_example.py
Enable early testing in latest deps CI.
> Test with Django 3.2

- weblate/utils/stats.py
Let the database server do the join instead of doing it on Python side.
This should perform better in most situations.
> Stats: Reduce amount of database queries

- docs/admin/projects.rst
> Fix typo: enfornce -> enforce

- docs/user/translating.rst
> Translating documentation reworked

- docs/admin/projects.rst
> Fix minor typo: define -> defined

- docs/changes.rst
- docs/user/glossary.rst
- weblate/checks/flags.py
- weblate/glossary/tests.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/tasks.py
> Glossary: Add terminology support

- weblate/formats/auto.py
- weblate/formats/base.py
- weblate/formats/ttkit.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
Some formats need to know this, so pass the info from Weblate.
> Formats: Store source language

- weblate/glossary/tasks.py
- weblate/glossary/tests.py
- weblate/trans/migrations/0116_migrate_glossaries.py
- weblate/trans/models/component.py
- weblate/trans/tasks.py
The glossary should be present even in case it is empty.
Issue #4903
> Glossary: Make it automatically available for all project languages

- .pre-commit-config.yaml
With reduced amount of plugins it might fit into the limit.
> CI: Try running flake8 on pre-commit.ci

- weblate/templates/translate.html
- weblate/trans/models/unit.py
- weblate/trans/views/source.py
> Flags: Allow toggling glossary flags on translation units

- weblate/auth/permissions.py
- weblate/templates/translate.html
- weblate/trans/views/source.py
See https://github.com/WeblateOrg/weblate/pull/5392#discussion_r574595852
> Unit: Loosen flag edit permission on glossary

- docs/admin/config.rst
> Fix minor typo: autonmatic -> automatic

- docs/user/glossary.rst
> Fix typo: tranlations -> strings

- weblate/formats/ttkit.py
Not 100% sure all dashes are correct, but better anyhow.
> ttkit.py langauge reworked

- docs/admin/backup.rst
> Backup documentation reworked

- docs/changes.rst
> typos, terms and clarification

- docs/admin/checks.rst
> Fix minor typo: the -> they

- docs/devel/translations.rst
Adding words to create search hit for the terms users asked about.
> adding abbreviations search hit

- docs/devel/translations.rst
Reorder list items so it would be obvious that only one of those was added in the specified version
> Docs: a minor reorder

- weblate/templates/accounts/contact.html
Rewording and adding a descriptive sentence to prevent support spammed by lost translators trying to contact translation project maintainers.
> changing description

- weblate/templates/mail/account_activity.html
I reworded the button and text of the message body, trying to prevent users’ scares and asking questions in the wrong place.
> preventing button misuse

- docs/changes.rst
- weblate/checks/models.py
- weblate/trans/models/comment.py
- weblate/trans/models/suggestion.py
- weblate/trans/tests/test_models.py
- weblate/utils/db.py
This should heavily improve performance of project/component removal.
> Unit: Allow fast deletion

- ci/lib
This is avoids warnings in CI environment. Security wise it is not relevant
as the password is hardcoded for CI anyway.
> CI: Pass MySQL password in environment

- weblate/templates/mail/account_activity.html
> Fix minor typo: bellow -> below

- docs/contributing/start.rst
Commented one change in need of review, and
@nijel
> About the settings, you could use the :file:`weblate/settings_test.py` from the
repository, but you could create your own setting and set it there.
I don't know what that does. What is going on there?
> Contributing code docs reworked

- weblate/api/serializers.py
- weblate/api/views.py
- weblate/formats/tests/test_formats.py
- weblate/formats/ttkit.py
- weblate/trans/forms.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/tests/test_edit.py
- weblate/trans/views/edit.py
Create a in-memory storage and validate the string would be added
correctly. This covers most common failures when adding strings, but
does not catch things like incompatibility with already existing data.
Issue #5418
> Translation: Add validation when adding new unit

- weblate/checks/models.py
- weblate/trans/models/unit.py
Improved handling of propagation checks.
> Check optimalizations

- weblate/trans/autotranslate.py
This should increase performance when translating a lot of strings.
Maybe also related to #5645, but I am not sure here.
> Autotranslate: Use batch mode

- weblate/trans/bulk.py
- weblate/trans/models/__init__.py
- weblate/trans/models/unit.py
This should improve performance and reduce comlexity as it uses same code path as import.
> Bulk edit: Use batch mode

- docs/user/glossary.rst
Used suggestion by @Fat-Zer in https://hosted.weblate.org/translate/weblate/documentation/en/?checksum=c1b84091706c12b1 :)
> Docs: Glossary documentation reworked

- weblate/templates/trans/alert/occurrences-limit.html
Is one supposed to be actively singular here?
> Spelling: occurrences

- docs/admin/support.rst
Rephrasing of the Discover docs.
@nijel 
Not sure what steps the
*2. Register your Weblate server in the discovery database*
means.
I think it needs a more detailed description, but I don’t know the process.
> Discover Weblate docs update

- docs/contributing/index.rst
Trying to propose guidelines for contributing to the docs
@nijel 
Please give feedback and suggest other places where this should be visible.
> adding guidelines for docs contributing

- weblate/addons/tasks.py
- weblate/api/views.py
- weblate/checks/tests/test_glossary_checks.py
- weblate/formats/base.py
- weblate/formats/tests/test_formats.py
- weblate/glossary/views.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/tests/test_edit.py
- weblate/trans/tests/test_selenium.py
- weblate/trans/tests/test_variants.py
- weblate/trans/views/edit.py
- weblate/utils/tests/test_search.py
- This makes adding units cheap - they are only added to the database
- Units are written when commit is needed together with other pending changes
Fixes #5418
> Translation: Add new units as pending first

- weblate/templates/snippets/unit-readonly-badge.html
Alternative, "uneditable source string …"
> Spelling: The source x2

- .github/ISSUE_TEMPLATE/config.yml
I feel the docs should have a priority.
> putting docs in the pole position

- weblate/templates/mail/account_activity.html
> Spelling: Support answers

- weblate/templates/mail/account_activity.html
the word was missing so the phrase was incorrect
> `good` added to be correct

- weblate/wladmin/forms.py
the form can search by both so I projected it into the description
> added `username` in the form

- docs/contributing/index.rst
- docs/contributing/issues.rst
- rephrasing and adding information
- thanks @comradekingu for some inspiration
- slightly improved issue submission part
> improvements of contributing docs

- weblate/templates/accounts/email-sent.html
> small simplification

- docs/api.rst
Adresses #5716
Document other "success" status codes than 200 OK
I didn't dig deeper to find more. These were the missing ones that I came across during my tests.
> Document other "success" status codes than 200 OK

- docs/contributing/security.rst
> Docs: Security and privacy documentation reworked

- docs/contributing/security.rst
> Fix minor typo: uppdated -> updated

- ci/apt-install
Use whatever is shipped in the image. That should be faster and more reliable as that version is widely tested.
> CI: Avoid installing newer Chromium

- docs/changes.rst
Adding milestones links to all versions since 4.3. It helps admins to check the details before updates.
> adding milestones links

- weblate/legal/tests.py
- weblate/templates/accounts/contact.html
> Contact form: adding article, corrections, clarification

- requirements.txt
- weblate/formats/tests/test_formats.py
- weblate/formats/ttkit.py
This depends on recent changes in the translate-toolkit.
> Formats: Simplify handling of properties storage

- docs/admin/install/docker.rst
Updated docs for docker environment variables. Specifically added references for `POSTGRES_PASSWORD_FILE`, `WEBLATE_ADMIN_PASSWORD_FILE` and `WEBLATE_EMAIL_HOST_PASSWORD_FILE`.
> doc(docker): update docs for docker env vars

- docs/api.rst
Fixes a typo (braino?) introduced in #5721
> Fix typo in api doc

- docs/admin/backup.rst
making a few changes in the sentences and wording for comfortable reading
> smoothing English in remote backups article

- docs/admin/machine.rst
Spotted by @rffontenelle.
Didn't look through the page more than the once I read through it.
> Docs: Machine.rst language reworked

- docs/user/glossary.rst
> Fix minor typo found by Fred Maranhão

- weblate/templates/500.html
Improving the message on the error page.
> error page: Differentiate message when Sentry is in use

- docs/admin/addons.rst
> hinting the alternative use of pseudolocale

- weblate/machinery/base.py
Instead of supporting only en_devel, we are now allow user to create any other *_devel
> Support any developer style language

- docs/admin/config.rst
- docs/admin/install/docker.rst
- docs/admin/machine.rst
- docs/changes.rst
- weblate/machinery/libretranslate.py
- weblate/machinery/models.py
- weblate/machinery/tests.py
- weblate/settings_docker.py
- weblate/settings_example.py
Adds [LibreTranslate](https://libretranslate.com/) as a Machine Translation option.
I pretty much just tried to copy DeepL where I could to implement this, hopefully it's fine. ^-^'
Closes https://github.com/WeblateOrg/weblate/issues/5830
PR-ing this already, but in a draft state as I'm struggling to run the tests in Docker.
I have run Weblate in general with the changes though, and can vouch LibreTranslate is working.
Discussion here: https://github.com/WeblateOrg/weblate/discussions/6200
> feat: add and document libretranslate

- docs/faq.rst
> Fix awkward sentence

- weblate/settings_docker.py
Small fix for the Docker configuration so that setting `WEBLATE_SOCIAL_AUTH_FEDORA`, `WEBLATE_SOCIAL_AUTH_OPENSUSE` and `WEBLATE_SOCIAL_AUTH_UBUNTU` actually work.
> Fixed Docker configuration for Linux vendor auth

- docs/user/glossary.rst
Don't know what this in-between
https://github.com/WeblateOrg/weblate/blob/c96d105cb4836991dbbeb85dab3c769fa4a9ddf2/weblate/trans/forms.py#L633
_Update only non translated strings_ (should be non-)
Could be "Update only untranslatable strings" or "Update only untranslated strings"
https://hosted.weblate.org/translate/weblate/application/nb_NO/?checksum=37b1bf47e4257ced
is "not translated strings."
I think that must have been "not translated" at some point, and then "strings" added on, because it is sub-par.
> Docs: Glossary spelling "Untranslatable strings"

- weblate/formats/base.py
- weblate/formats/convert.py
- weblate/formats/external.py
- weblate/formats/ttkit.py
- weblate/formats/txt.py
Switch to normal methods from class ones to be able to use attributes during fixup.
> Adjust formats api

- docs/changes.rst
Congratulations on the new version :)
> Changelog fixes

- docs/admin/install/venv-debian.rst
Changed `libapache2-mod-wsgi` to `libapache2-mod-wsgi-py3`
> Changed "Web Server Option 2" (Apache2)

- docs/changes.rst
- weblate/trans/forms.py
This could get super heavy on large sites with enabled TM.
> translation: Avoid listing all available components

- weblate/accounts/views.py
- weblate/api/views.py
- weblate/lang/views.py
- weblate/trans/feeds.py
- weblate/trans/models/change.py
- weblate/trans/views/basic.py
- weblate/trans/views/changes.py
- weblate/trans/views/edit.py
Rely on relations being correct and fill the missing objects in Python instead
of fetching them repeatedly from the database.
> changes: Avoid fetching same info multiple times

- docs/admin/access.rst
- docs/changes.rst
- weblate/api/tests.py
- weblate/api/views.py
- weblate/auth/data.py
- weblate/auth/permissions.py
- weblate/trans/views/files.py
> translation: Added support for restricting translation file download

- .github/workflows/test.yml
- docs/changes.rst
- setup.py
> ci: Test using Python 3.10

- docs/changes.rst
- weblate/trans/models/translation.py
Otherwise the uploaded monolingual files might not be matched.
> translation: Commit pending changes in template prior upload

- docs/changes.rst
> 4.9 milestone link added

- docs/admin/languages.rst
- weblate/formats/base.py
- weblate/formats/convert.py
- weblate/formats/txt.py
- weblate/templates/new-language.html
- weblate/trans/models/component.py
* Describe document based translations in the docs
* Add short description when creating new translation
Preview:
> docs: Clarify how new translations are created

- weblate/vcs/git.py
- weblate/vcs/tests/test_vcs.py
Adds support for the pull request workflow on GitHub Enterprise Server which uses a different API endpoint base.
Implements #6853
> Support pull request workflow on GitHub Enterprise Server

- docs/changes.rst
automatic translation privilege fix added to 4.10 changes list
> automatic translation fix added

- docs/admin/install/docker.rst
Based on comment in weblate/settings_docker.py
Makes install a bit easier.
> Add docs on WEBLATE_SERVER_EMAIL

- weblate/formats/ttkit.py
> formats: Delete empty <target/> tags when creating new translation

- docs/changes.rst
> automatic translation privilege changes

- weblate/accounts/tests/test_views.py
> Profile password warning test

- docs/faq.rst
Simple proofreading of the docs added in 44aa2b39aa5a4c606203d89b8c48cfe90580f38a.
> docs: Proofreading FAQ entry on safe file moves

- weblate/accounts/models.py
> small typo fixing in models.py

- README.rst
> Added a note about live chat as per issue #6102

- weblate/trans/tests/test_edit.py
- weblate/trans/tests/test_views.py
- weblate/trans/views/edit.py
Delay lock checking to permission check, this is where it happens anyway.
Fixes #7255
> translate: Delay lock checking to permission check

- docs/admin/projects.rst
- fixing typo
- trying to describe merge style differences in better detail
> merge styles typo fixes and clarification

- docs/api.rst
added the new attribute "definining_project" to the response json
the new attribute that has been introduced in 4.11 is missing in the API Documentation
> update response json for GET /api/groups/<id>/

- weblate/vcs/mercurial.py
Make sure that all user provided input is handled as expected.
> vcs: Improve mercurial parameters handling

- docs/admin/config.rst
- docs/vcs.rst
- weblate/addons/git.py
- weblate/checks/data.py
- weblate/gitexport/models.py
- weblate/settings_docker.py
- weblate/trans/forms.py
- weblate/vcs/git.py
- weblate/vcs/models.py
- weblate/vcs/tests/test_vcs.py
Add Gitea VCS backend similar to GitHub and GitLab.
Fixes #7099
Supersedes #7326
> vcs: Add support for Gitea pull requests

- docs/devel/thirdparty.rst
> Update names to WeblateFX, JWeblate

- weblate/trans/models/component.py
- weblate/trans/models/translation.py
Improve performance of add upload by using batch checks.
> translation: Batch checks in add upload

- weblate/templates/translate.html
- weblate/trans/views/edit.py
This saves time and a bit of bandwidth on performing a redirect request
Again, did not test properly, but tried the equivalent of this in browser's dev tools — looks fine.
> perf: `/translate`: replace the "Skip" button with a link

- weblate/templates/base.html
It is defined above, also `index` and `follow` are the default anyway
> fix: remove the duplicate `<meta name="robots"` element

- weblate/templates/paginator.html
> improvement: add `rel="(next|prev)"` for `<a>`s in `paginator.html`

- weblate/templates/snippets/libre-basic.html
> improvement: add links for OSI and FSF references

- docs/admin/management.rst
> Docs: Add celery tasks prerequisite for import_data command

- docs/admin/install/docker.rst
Update documentation needed for WeblateOrg/docker#1484
> Update documantation about Redis password and LDAP bind password files

- weblate/formats/base.py
Headers or comments are not needed here and might cause problems.
> formats: Include only content units in the index

- weblate/templates/translate.html
> fix: `/translate`: translation file string position not showing when no `filename`

- weblate/billing/models.py
- weblate/trans/context_processors.py
- weblate/trans/models/label.py
- weblate/trans/templatetags/translations.py
- weblate/trans/views/basic.py
- weblate/trans/views/dashboard.py
- weblate/trans/views/widgets.py
This should make it easier to maintain the code without introducing security vulnerabilities.
> refactor: use `mark_safe` more sparsely, replace `format` with `format_html`

- weblate/templates/snippets/plural-formula.html
> improvement: wrap plural formula into `<code>` so it's more readable

- weblate/templates/translate.html
- weblate/trans/views/edit.py
Do we need to update the localization files in this MR?
> improvement: don't show "things to check: comments" if all comments are resolved

- weblate/static/editor/base.js
- weblate/static/editor/full.js
- weblate/static/loader-bootstrap.js
Part of #7699. We're still a long way there, but it's something.
> refactor: rewrite a couple of unsafe lines

- weblate/formats/tests/test_formats.py
- weblate/formats/ttkit.py
- weblate/trans/tests/data/cs-webext.json
> fix: WebExtension placeholders not being recognized when typed non-uppercase

- docs/changes.rst
- docs/formats.rst
- docs/user/translating.rst
- weblate/checks/consistency.py
- weblate/checks/tests/test_checks.py
- weblate/formats/base.py
- weblate/formats/models.py
- weblate/formats/multi.py
- weblate/formats/tests/test_formats.py
- weblate/formats/tests/test_multi.py
- weblate/formats/ttkit.py
- weblate/formats/txt.py
- weblate/static/editor/full.js
- weblate/templates/translate.html
- weblate/trans/forms.py
- weblate/trans/models/component.py
- weblate/trans/models/unit.py
- weblate/trans/templatetags/translations.py
- weblate/trans/tests/data/fr-multi-mono.csv
- weblate/trans/tests/data/fr-multi.csv
- weblate/trans/tests/test_templatetags.py
- weblate/trans/util.py
- weblate/trans/views/edit.py
- it effectively merges duplicate strings into multi unit
- implementation is generic, but applied to CSV for now
Fixes #7546
> formats: Add support for multi value CSV file

- weblate/formats/ttkit.py
There is no good reason to have the logic twice.
Fixes #7708
> formats: Share code for JSON placeholders

- weblate/trans/forms.py
Helps fix https://hosted.weblate.org/translate/weblate/application/en/?checksum=4bbb4433f8abbecd#comments and currently makes assumptions about specifics
> Forms.py langugage reworked

- docs/changes.rst
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
This avoids getting edits which we can not save.
> alerts: Make parse error lock a component from translating

- weblate/addons/cdn.py
- weblate/templates/addons/js/weblate.js
Related: #7683
This makes tests fail though because it's invalid JS (in the template form, I mean)
> refactor: make `CDNJSAddon` a little safer from outputting unsafe code

- docs/api.rst
- weblate/api/tests.py
- weblate/api/views.py
> api: add delete user from group

- docs/admin/config.rst
- docs/admin/install.rst
- weblate/settings_docker.py
- weblate/settings_example.py
- weblate/settings_test.py
- weblate/trans/models/_conf.py
- weblate/trans/tests/test_selenium.py
- weblate/utils/checks.py
- weblate/utils/files.py
This is not intended for the production setup, so let people configure
this.
This is followup for  #7740
> config: Remove calculated default for DATA_DIR

- weblate/middleware.py
- weblate/trans/tests/test_views.py
> middleware: made 404 info more useful 

- weblate/formats/convert.py
This affects at least RC files.
> formats: Fixed parsing of source strings for converted formats

- weblate/memory/views.py
> Spelling: Deleted entries, translation memory

- weblate/trans/templatetags/translations.py
- weblate/trans/tests/test_templatetags.py
Implements the change proposed in #7960 (closes #7960)
> add absolute links for source locations

- weblate/formats/base.py
This happens too early and effectively hides duplicate string error from
users. On the other side, the id_hash conflict never really happened.
Fixes WEBLATE-9R5
> formats: Remove id_hash validation

- requirements.txt
- setup.cfg
- weblate/trans/models/change.py
- weblate/utils/requirements.py
- weblate/utils/search.py
- weblate/utils/tests/test_search.py
This reduces the memory usage from O(N*M) to O(N). In addition this implementation is faster as well.
> reduce memory usage of damerau levenshtein

- docs/admin/install/steps/install-configure.rst
The seemingly missing "2." looks good in https://docs.weblate.org/en/latest/admin/install/venv-redhat.html?highlight=example%20settings%20use%20PostgreSQL#configuring-weblate if that is the only place it is used.
> install-configure.rst language reworked

- docs/wlc.rst
> Fix typo command in wlc.rst

- weblate/static/loader-bootstrap.js
Revert 0943c4436e and add `bubbles`.
And that commit did not fully fix_ #8066,
it only made it update the counter.
> fix(edit): text not updating when cloning

- weblate/static/loader-bootstrap.js
> fix: string not saving on button-caused changes in Zen mode

- docs/admin/install.rst
The section is no longer relevant as django defaults are now exactly what this was proposing.
Closes #8087
> docs: remove section about template loaders in install docs

- weblate/memory/machine.py
- weblate/memory/tests.py
- weblate/static/editor/full.js
- weblate/templates/translate.html
closes #6440 
- Added a Delete entry button for removing translation suggestion from Automatic Suggestions
> memory: implement delete entry from automatic suggestions

- weblate/trans/models/change.py
Intends to fix: https://github.com/WeblateOrg/weblate/issues/8211
The following change introduced in 4.11.0 release resulted in some messages not being emitted:
https://github.com/WeblateOrg/weblate/commit/38bc49fa732378148f7c220df7487385101c3e99
This is due to the fact that bulk_create does not call the save() method nor the post_save signals when Changes are parsed into it.
These post_save signals are required for fedora_notify_change to receive said signal and emit the appropriate message.
This fixes this issue by over-riding the bulk_create method in the ChangeQuerySet class to ensure the post_save signal is always sent after creation.
- [ x] I have added tests that prove my fix is effective or that my feature works.
- [ x] I have added documentation to describe my feature.
- [ x] I …
> Ensure post save is triggered upon executing bulk_create

- ci/apt-install
To be compatbile with 15 server.
> ci: Install postgresql-client-15

- docs/admin/continuous.rst
- docs/vcs.rst
> document gitea push workflow

- .github/workflows/docs.yml
- .github/workflows/licenses-update.yml
- .github/workflows/schema-update.yml
- .github/workflows/setup.yml
- .github/workflows/test.yml
- docs/changes.rst
- setup.py
Test with Python 3.11 and list it as supported version.
> ci: Test with Python 3.11

- weblate/formats/base.py
This leads to huge memory consumption in case where multiple units need to be clone (each one gets its own copy of the storage).
> formats: Avoid using deep copy when creating unit from template

- weblate/formats/ttkit.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
> translation: Gracefully handle errors when serializing file

- weblate/accounts/notifications.py
- weblate/trans/models/component.py
- weblate/trans/tests/test_component.py
- Default (infer) "Repository browser" link template from "Source code repository"
- closes #7865
> trans: generate repo based url template links

- weblate/templates/addons/discovery_help.html
Following the answer on #8407 I felt like it could be useful to have another example in the discovery help for this kind of usecase.
- ~~[ ] Lint and unit tests pass locally with my changes~~ (doesn't apply, only doc PR)
- ~~[ ] I have added tests that prove my fix is effective or that my feature works.~~ (doesn't apply, only doc PR)
> Add example in discovery_help.html

- weblate/static/loader-bootstrap.js
- weblate/templates/base.html
- weblate/templates/screenshots/screenshot_show.html
- weblate/templates/translate.html
See commit messages.
Did not test lol.
> improvement: improve screenshot-related links

- docs/changes.rst
- weblate/formats/multi.py
- weblate/formats/ttkit.py
Use our wrapper classes to get consistent behavior. Otherwise the untranslate path would need to duplicate all the workarounds we do in the regular code.
> formats: Rewrite store untranslating

- docs/admin/install/docker.rst
The postgres  data volume name has apparently changed from  when these instructions were originally written.
> fix docker postgres upgrade instructions

- weblate/checks/format.py
Currently, linked messages like `@:error-try-again` is not matched by Weblate. I looked into Vue-I18n code to find the correct regexp.
I'm a bit sorry, it's difficult in my environment (corporate proxy) to clone and push. So I've made a quick'n'dirty edit.
Please let me now if this is can merged like this or not. I'll try to find more time to this in a proper way.
> Update vue-i18n linked reference

- docs/admin/upgrade.rst
- docs/changes.rst
- weblate/api/pagination.py
- weblate/api/views.py
- weblate/settings_docker.py
- weblate/settings_example.py
- Make the default page size differ per scope
- Allow to customize it via page_size param
> api: Allow to override page size

- weblate/accounts/models.py
Changed the linkedIn model attributes to allow non-ASCII characters. 
Solves #8498 
https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.TextField
> LinkedIn profile name field updated

- weblate/addons/base.py
- weblate/addons/generate.py
- weblate/addons/git.py
- weblate/addons/models.py
- weblate/api/views.py
- weblate/gitexport/views.py
- weblate/machinery/views.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/tasks.py
- weblate/trans/views/files.py
- weblate/trans/views/git.py
- weblate/utils/errors.py
- weblate/utils/views.py
This makes it easier to spot which projects are affected.
> utils: Include project slug in Sentry tags

- weblate/trans/models/component.py
Add separate validation to avoid doing the failure on every translation.
> component: Validate template store before comitting

- docs/admin/config.rst
- docs/admin/install/docker.rst
- weblate/settings_example.py
- weblate/settings_test.py
- weblate/trans/models/_conf.py
- weblate/utils/data.py
This setting was already used in Docker, now it is extended to general.
See #2984
> utils: Allow to define cache directory separately

- docs/workflows.rst
Reviews are no longer limited for the Libre plan so the note is removed.
> deprecated note removed

- weblate/trans/models/translation.py
It is no longer necessary as upload uses regular Unit.translate now.
Fixes #8682
Fixes WEBLATE-7
> translation: Do not hold component lock for upload

- docs/admin/config.rst
- docs/admin/install/docker.rst
- docs/admin/upgrade.rst
- docs/changes.rst
- docs/vcs.rst
- weblate/settings_docker.py
- weblate/utils/checks.py
- weblate/utils/environment.py
- weblate/utils/tests/test_environment.py
- weblate/vcs/apps.py
That has security implications and users were warned for two releases, that should give everybody enough time to migrate.
> vcs: Drop support for deprecated VCS configuration

- docs/requirements.txt
This will give us Sphinx 6 compatibility.
> deps: Use rc version of sphinx-rtd-theme

- .github/workflows/migrations.yml
- ci/pip-install
- ci/run-migrate
> ci: Install only runtime deps for migration tests

- ci/run-migrate
> ci: Reuse CI virtualenv instead of building it again

- weblate/templates/language-project.html
- weblate/templates/language.html
Solving https://hosted.weblate.org/translate/weblate/application/en/?checksum=bd769ef3e26ca3ce
Could be "Browse all/only {language name} changes.
Don't really know where it is used.
> Spelling: Browse alle changes for this language.

- weblate/trans/models/component.py
Otherwise loading of non-English source strings might be messed up.
Fixes #8752
> component: Set target language when loading template

- weblate/vcs/base.py
- weblate/vcs/git.py
- weblate/vcs/mercurial.py
> vcs: fix typo in base class

- weblate/trans/models/change.py
- weblate/utils/models.py
- weblate/utils/stats.py
- update cache on transaction commit, otherwise we might be trying to fetch non-existing entries from the changes table
- store only last change from bulk create to improve performance
> change: Consolidate storing last change ID

- docs/admin/continuous.rst
Gitea was missing in the list so it was easy to miss it being there in the content below.
> docs: add gitea to common services for webhooks

- docs/api.rst
- docs/changes.rst
- weblate/api/serializers.py
- weblate/api/tests.py
- weblate/trans/models/translation.py
> api: Added support for defining strings state when adding

- weblate/accounts/models.py
- weblate/auth/admin.py
- weblate/billing/admin.py
- weblate/billing/models.py
- weblate/trans/admin.py
Found via https://github.com/adamchainz/django-upgrade
> chore: Use admin.display for descriptions in the Django admin

- weblate/accounts/middleware.py
- weblate/gitexport/views.py
- weblate/lang/models.py
- weblate/trans/views/error.py
- weblate/trans/views/hooks.py
Found via https://github.com/adamchainz/django-upgrade
> chore: Utilize request.headers instead of request.META

- weblate/machinery/forms.py
I found this typo and simply want it to be fixed. ^_^
> Fix typo in weblate/machinery/forms.py

- docs/changes.rst
- weblate/formats/ttkit.py
This is needed to get correct plural tags for some of the formats.
Fixes #8752
> formats: Set language prior to parsing

- docs/admin/install/venv-macos.rst
`pip install "Weblate"` command fails because it could not find homebrew version of openssl lib
Fixes #7358  on macOS
> docs: Update macOS installation instructions

- weblate/machinery/microsoft.py
When using Microsoft's translation interface, Mongolian requires the conversion of the language code mn to mn-Mong.
- [ x ] Lint and unit tests pass locally with my changes.
> machinery: mn need transform to mn-Mong for microsoft machinery.

- weblate/addons/base.py
- weblate/addons/generate.py
- weblate/addons/tasks.py
- weblate/addons/tests.py
- weblate/trans/models/component.py
- consistently handle changed repo after installing add-on
- trigger add-on execution in the background to avoid slowing down installation response
> Addons post-configure trigger changes

- weblate/trans/models/component.py
We now copy implementation of get_or_create to get the same logic, but without need to evaluate source_language when using the fast path.
Fixes #8945
> component: Better handle concurrent creation of source translation

- docs/_templates/layout.html
- docs/conf.py
- docs/requirements.txt
Improve social media presentation of documentation links.
> docs: Add opengraph extension

- weblate/accounts/forms.py
- weblate/accounts/password_validation.py
- weblate/addons/properties.py
- weblate/checks/consistency.py
- weblate/checks/format.py
- weblate/formats/ttkit.py
- weblate/trans/forms.py
- weblate/trans/migrations/0123_fix_enforced_checks.py
- weblate/trans/models/component.py
- weblate/trans/models/unit.py
- weblate/trans/views/edit.py
- weblate/utils/docs.py
- weblate/vcs/git.py
- weblate/vcs/mercurial.py
- weblate/vcs/tests/test_vcs.py
> chore: Simplify empty string conditions (ruff PLC1901)

- docs/admin/access.rst
Make it more obvious what should be chosen.
> docs: Add guidance to access control choices

- weblate/trans/management/commands/cleanuptrans.py
- weblate/trans/models/component.py
- weblate/trans/tasks.py
It is no longer needed to have it at project scope since using foreign key to reference unit data and no need for garbage collecting stale unit data.
Fixes #9031
> component: Re-scope cleanup to a component level

- docs/changes.rst
- docs/vcs.rst
- weblate/templates/about/keys.html
- weblate/templates/manage/ssh.html
- weblate/templates/snippets/ssh-key.html
- weblate/templates/trans/project-access.html
- weblate/trans/views/about.py
- weblate/trans/views/acl.py
- weblate/vcs/ssh.py
- weblate/wladmin/tests.py
- weblate/wladmin/views.py
* List both key types
* Generate ed25519 if missing
* Recommend users to use ed25519
> Add ed25519 SSH key support

- docs/admin/access.rst
- docs/snippets/not-hosted-libre.rst
Make it clear what is the setting and how to lift that limitation.
> docs: Clarify access control limitation for libre hosting

- docs/admin/languages.rst
- docs/admin/projects.rst
- docs/devel/translations.rst
- docs/faq.rst
- merge two sections about this topic
- move more documentation to the fields documentation
- added guidance on how to fill the Template for new translations
> doc: consolidate "Adding new translations"

- weblate/api/views.py
- weblate/auth/permissions.py
- weblate/templates/translate.html
- This moves the logic to single place instead of duplicating it in the template to get the verbose message.
- The detailed message is now used in the API as well.
Fixes #9073
> auth: Provide more detailed feedback on permission checks

- weblate/utils/xml.py
This improves performance of the XML based checks.
> utils: Cache XML parsing results

- .github/workflows/codeql-analysis.yml
- .github/workflows/docs.yml
- .github/workflows/licenses-update.yml
- .github/workflows/migrations.yml
- .github/workflows/rundev.yml
- .github/workflows/schema-update.yml
- .github/workflows/setup.yml
- .github/workflows/test.yml
- ci/apt-install
> ci: Upgrade base test system

- weblate/accounts/middleware.py
- weblate/auth/models.py
- weblate/trans/tests/test_views.py
This heavily speeds up operations where anoymous user did many suggestions, or doing a lot of commits wihout an user.
> auth: Cache anonymous user

- weblate/machinery/googlev3.py
> Specify text format for Google Translate V3

- weblate/trans/util.py
There is no good reason to be inconsistent here.
> utils: Make render API match Django one

- weblate/trans/models/translation.py
This heavily reduces number of update queries.
See #9128
> translation: Bulk pending/details update on commit

- weblate/trans/models/component.py
Fetch all alerts at once and operate on cached list. This way we hit the database just once per component when there are no updates to alerts.
Fixes #9139
> alerts: Minimize database queries on no-change alert update

- docs/admin/auth.rst
Azure provide way more IDs than needed and that causes quite some confusion during the setup.
> docs: Clarify what is needed for Azure AD authentication

- weblate/api/views.py
- weblate/trans/autotranslate.py
- weblate/trans/forms.py
- weblate/trans/tests/test_autotranslate.py
- weblate/trans/views/basic.py
- weblate/trans/views/edit.py
> Add auto translation as "approved" (Closes: #9048)

- .pre-commit-config.yaml
- weblate/accounts/tests/test_views.py
- weblate/api/tests.py
- weblate/settings_docker.py
- weblate/settings_example.py
- weblate/trans/tests/test_dashboard.py
- weblate/trans/tests/test_hooks.py
- weblate/trans/tests/test_projecttoken.py
> chore: django-upgrade to 4.2

- weblate/templates/accounts/user.html
Solves https://hosted.weblate.org/translate/weblate/application/en/?checksum=2002e6a7d5bcf841
> Spelling: Translations contributed to, "No project assoc"

- docs/admin/install/venv-redhat.rst
Update dependencies on Fedora 37
> Update dependencies on Fedora 37

- weblate/templates/translate.html
> Spelling: differing sources and/or context

- weblate/vcs/git.py
- consolidate different errors from different VCS backends
- do not include trailing : if no detailed message is available
Issue #9177
> vcs: Improve error message on failed fork creation

- weblate/trans/models/component.py
- weblate/trans/tasks.py
Many of these can be fired in some situations (removing components from a huge project), so execute only the latest scheduled one.
Fixes #9207
> component: Only run latest scheduled checks update

- docs/_ext/djangodocs.py
- docs/admin/access.rst
- docs/admin/addons.rst
- docs/admin/auth.rst
- docs/admin/backup.rst
- docs/admin/config.rst
- docs/admin/continuous.rst
- docs/admin/install.rst
- docs/admin/languages.rst
- docs/admin/management.rst
- docs/admin/memory.rst
- docs/admin/projects.rst
- docs/admin/upgrade.rst
- docs/contributing/debugging.rst
- docs/contributing/schemas.rst
- docs/contributing/start.rst
- docs/faq.rst
- use different role for Weblate and Django commands
- render Weblate commands with weblate prefix so that full command is show
- add migrate documentation to cover differences from Django
Fixes #9253
> docs: Improve management commands documentation

- docs/changes.rst
- docs/user/profile.rst
- docs/user/search.rst
- weblate/accounts/forms.py
- weblate/accounts/views.py
- weblate/auth/models.py
- weblate/trans/forms.py
- weblate/utils/forms.py
- weblate/utils/search.py
- weblate/utils/tests/test_search.py
- weblate/wladmin/forms.py
- weblate/wladmin/tests.py
- weblate/wladmin/views.py
It is based on the same parser as searching for strings.
Issue #2241
> auth: Add user searching support

- docs/admin/checks.rst
- docs/admin/machine.rst
> adding terminology flag description, changing IBM link

- requirements-optional.txt
- requirements.txt
Drop package versions older than two years making the ranges less broad.
> deps: Tigthen dependency ranges

- docs/changes.rst
> changelog phrasing a wording update

- weblate/addons/tests.py
- weblate/api/tests.py
- weblate/checks/tests/test_glossary_checks.py
- weblate/checks/tests/test_same_checks.py
- weblate/glossary/tests.py
- weblate/trans/models/_conf.py
- weblate/trans/models/component.py
- weblate/trans/tests/test_autotranslate.py
- weblate/trans/tests/test_backups.py
- weblate/trans/tests/test_commands.py
- weblate/trans/tests/test_component.py
- weblate/trans/tests/test_create.py
- weblate/trans/tests/test_dashboard.py
- weblate/trans/tests/test_discovery.py
- weblate/trans/tests/test_manage.py
- weblate/trans/tests/test_models.py
- weblate/trans/tests/test_remote.py
- weblate/trans/tests/test_search.py
- weblate/trans/tests/test_views.py
- weblate/trans/tests/utils.py
- weblate/utils/tests/test_search.py
This makes the tests unnecessarily slow without a good reason.
> tests: Avoid creating glossary components during tests

- docs/admin/checks.rst
- docs/changes.rst
- docs/user/checks.rst
- weblate/checks/consistency.py
- weblate/checks/models.py
- weblate/checks/tests/test_consistency_checks.py
- weblate/settings_docker.py
- weblate/settings_example.py
- weblate/trans/models/unit.py
> checks: Added check for reused translation

- docs/changes.rst
- weblate/machinery/views.py
- weblate/static/editor/full.js
- weblate/templates/translate.html
- weblate/utils/diff.py
> machinery: Highlight differences

- docs/admin/config.rst
- docs/snippets/vcs-credentials.rst
> docs: Clarify VCS credentials documentation

- weblate/auth/permissions.py
Strictly more correct (?), and cuts down on the self-referencing
> Spelling: E-mail address, agreeing

- weblate/vcs/git.py
Not sure why it is "failed to" vs. "could not" (used elsewhere) here.
> Spelling: the, a, etc. in git.py

- docs/admin/install/docker.rst
I had an issue using this default sample, turns out it's missing an ssl after the listen statement.
> Add ssl tag to listen statement in NGINX sample

- docs/api.rst
This PR fixes a grammatical issue in the API reference.
> docs: fix grammar

- weblate/addons/resx.py
- weblate/api/views.py
- weblate/trans/models/component.py
- weblate/trans/tests/test_edit.py
> chore: Utilize dict comprehensions for lookups

- docs/admin/projects.rst
> screenshots: update documentation

- docs/admin/upgrade.rst
The process is always the same and will be the same for 5.0 as well, so let's document it just once.
> docs: merge instructions for upgrading from older releases

- docs/admin/install/steps/install-configure.rst
The main admin account is named "admin". It is better to emphasize this.
this follows my issue https://github.com/WeblateOrg/weblate/issues/9531 and subsequent fixes
> subsequent line update to "install-configure.rst" following #9531

- docs/contributing/communication.rst
Weblate’s contributors communicate on GitHub discussions, via comments within
GitHub Issues, and on the IRC network Libera.Chat, but a documentation page that specifies what types of communication are appropriate for each of these platforms does not exist. I have created a documentation page that attempts to address this.
> Docs: Added Contributor Communication Guidelines

- weblate/machinery/microsoft.py
Add the mapping "sr" -> "sr-Latn" to the language map.
Fixes #9565
> fix: Serbian translation with Microsoft translator

- docs/devel/reporting.rst
> Docs: Reporting reworked

- docs/admin/install.rst
- docs/changes.rst
- requirements-optional.txt
- requirements.txt
- weblate/formats/apps.py
- weblate/formats/models.py
- weblate/formats/tests/test_convert.py
- weblate/formats/tests/test_external.py
- weblate/formats/tests/test_formats.py
- weblate/formats/tests/test_multi.py
- weblate/formats/tests/test_txt.py
- having optional deps complicates the code
- most deployments are Docker based which has all the deps anyway
- this makes releases more reliable becase it is not possible to test combinations of all optional dependencies
> formats: Make all format dependencies required

- weblate/addons/autotranslate.py
- weblate/addons/tasks.py
- weblate/addons/tests.py
- weblate/trans/tasks.py
This helps distributing system load on larger sites.
> tasks: distribute expensive tasks equally during the day

- weblate/templates/last-changes-content.html
- weblate/templates/mail/changed_translation.html
- weblate/templates/mail/new_suggestion.html
- weblate/templates/mail/snippets/source-string.html
- weblate/templates/matrix-table.html
- weblate/templates/replace.html
- weblate/templates/snippets/embed-units.html
- weblate/templates/snippets/glossary.html
- weblate/templates/snippets/suggestions.html
- weblate/templates/trans/alert/duplicatestring.html
- weblate/templates/trans/other-row.html
- weblate/templates/translate.html
- weblate/templates/zen-units.html
- weblate/trans/templatetags/translations.py
- weblate/trans/tests/test_templatetags.py
These are the most frequent use-cases, so better to have a simple interface for these instead of duplicating the logic in the templates (and forgetting to add some parameters somewhere).
> templatetags: specialize tags for rendering unit strings

- weblate/checks/base.py
- weblate/checks/consistency.py
- weblate/trans/models/unit.py
This makes propagation actually work for same target check.
Fixes #9621
> checks: implement custom propagation rule per check

- docs/changes.rst
- weblate/formats/ttkit.py
Depends on https://github.com/translate/translate/pull/4948 to be released.
Fixes #7767
> formats: support location for xliff

- pyproject.toml
- weblate/addons/base.py
- weblate/addons/git.py
- weblate/addons/tasks.py
- weblate/addons/tests.py
- weblate/formats/base.py
- weblate/glossary/tasks.py
- weblate/machinery/baidu.py
- weblate/machinery/base.py
- weblate/machinery/tests.py
- weblate/trans/exceptions.py
- weblate/trans/management/commands/import_project.py
- weblate/trans/migrations/0127_fix_source_glossary.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/tasks.py
- weblate/trans/views/files.py
- weblate/trans/views/git.py
- weblate/utils/lock.py
- weblate/utils/tasks.py
- weblate/utils/version.py
- weblate/vcs/apps.py
- weblate/vcs/base.py
- weblate/vcs/git.py
- weblate/vcs/mercurial.py
- weblate/vcs/tests/test_vcs.py
- weblate/wladmin/tasks.py
> chore: improve exceptions naming

- docs/admin/access.rst
- docs/admin/addons.rst
- docs/admin/backup.rst
- docs/admin/checks.rst
- docs/admin/config.rst
- docs/admin/continuous.rst
- docs/admin/customize.rst
- docs/admin/install.rst
- docs/admin/install/docker.rst
- docs/admin/machine.rst
- docs/admin/management.rst
- docs/admin/memory.rst
- docs/admin/optionals.rst
- docs/admin/projects.rst
- docs/admin/support.rst
- docs/admin/translating.rst
- docs/api.rst
- docs/devel/community.rst
- docs/devel/translations.rst
- docs/formats.rst
- docs/formats/appstore.rst
- docs/formats/excel.rst
- docs/formats/flatxml.rst
- docs/formats/subtitles.rst
- docs/formats/xliff.rst
- docs/user/checks.rst
- docs/user/search.rst
- docs/vcs.rst
These are quite old, so there is no longer need to keep this in the documentation.
> docs: remove notes on changes in 3.x series

- weblate/accounts/tests/test_registration.py
- weblate/accounts/tests/test_views.py
- weblate/trans/tests/test_selenium.py
- weblate/trans/tests/utils.py
While overriding AUTHENTICATION_BACKENDS the results might be cached inside social_core and cause unexpected test failures.
> tests: safely handle social_core backends cache

- docs/changes.rst
- docs/formats.rst
- docs/formats/html.rst
- docs/formats/markdown.rst
- docs/formats/txt.rst
- docs/snippets/format-database-backed.rst
- requirements.txt
- weblate/checks/tests/test_checks.py
- weblate/formats/auto.py
- weblate/formats/base.py
- weblate/formats/convert.py
- weblate/formats/models.py
- weblate/formats/tests/test_convert.py
- weblate/formats/tests/test_formats.py
- weblate/formats/ttkit.py
- weblate/trans/models/translation.py
- weblate/trans/tests/data/cs.md
Based on https://github.com/translate/translate/pull/4966, can be merged once that is merged and released.
> formats: Add Markdown support

- docs/user/checks.rst
- weblate/checks/fluent/inner_html.py
- weblate/checks/fluent/references.py
Follow up to https://github.com/WeblateOrg/weblate/pull/9540
Clarify some sentences, remove the use of "we", and replace the "\\\*" with "\*" in the text code-blocks.
> fluent: Tidy up some of the check documentation.

- docs/admin/access.rst
- weblate/templates/auth/team.html
> docs: Clarify automatic team assignment behavior

- docs/changes.rst
- weblate/auth/permissions.py
- weblate/lang/views.py
- weblate/static/style-bootstrap.css
- weblate/templates/component.html
- weblate/templates/language-project.html
- weblate/templates/language.html
- weblate/templates/project.html
- weblate/templates/snippets/activity.html
- weblate/templates/trans/change_list.html
- weblate/templates/translate.html
- weblate/templates/translation.html
- weblate/trans/feeds.py
- weblate/trans/forms.py
- weblate/trans/mixins.py
- weblate/trans/models/component.py
- weblate/trans/models/project.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/templatetags/translations.py
- weblate/trans/tests/test_changes.py
- weblate/trans/views/basic.py
- weblate/trans/views/changes.py
- weblate/trans/views/edit.py
- weblate/urls.py
- weblate/utils/forms.py
- weblate/utils/stats.py
- weblate/utils/urls.py
- weblate/utils/views.py
- utilize path lookups
- provide endpoints for all objects instead of filtering in the URL
- move validation logic to the form
- use new path_object_breadcrumbs helper
- raise TypeError in case of missing implementation
> changes: Consolidate view

- docs/admin/install/docker.rst
- docs/changes.rst
- weblate/settings_docker.py
- weblate/utils/environment.py
- do not directly use os.environ
- fail with a nicer error message if missing configuration
- annotate more configurations as required
- support for file backed secrets, fixes #9482
> docker: improve strings parsing from environment

- docs/changes.rst
- weblate/screenshots/models.py
Without that the file might be cached by the browser causing it to show old content after update.
> screenshots: generate new name on screnshot update

- weblate/checks/views.py
- weblate/trans/models/component.py
- weblate/trans/templatetags/translations.py
- weblate/utils/random.py
- weblate/utils/stats.py
We do not need that radom IDs as uuid4 provides and this is much faster.
> utils: Add helper to generate random IDs

- docs/changes.rst
- weblate/checks/consistency.py
> checks: avoid reused check to trigger on blank strings

- docs/changes.rst
- weblate/trans/models/project.py
The resulting object is huge and it is faster to rebuild it rather than loading it from cache (escpecially as we already cache list of the words).
> glossary: Avoid storing automaton in the cache

- docs/changes.rst
- weblate/trans/models/category.py
- weblate/trans/models/change.py
- weblate/trans/views/files.py
- weblate/utils/views.py
This performs better than doing complex join in many places.
> category: cache child component IDs

- docs/changes.rst
- requirements.txt
- weblate/glossary/models.py
- weblate/utils/requirements.py
This delivers a better performance.
Fixes #9825
> glossary: use ahocorasick_rs instead fof pyahocorasick

- weblate/metrics/models.py
- weblate/utils/stats.py
> changes: Reuse existing lookups for related changes

- docs/admin/install/docker.rst
- weblate/settings_docker.py
Fixes #8566
Added USE_X_FORWARDED_HOST key
> feat(weblate/settings_docker.py): Add USE_X_FORWARDED_HOST key in settings_docker.py file.

- weblate/utils/stats.py
This avoids fetching all components just to figuring out their language and offloads the query to the database.
> stats: Improve determining whether language scoped objects are source

- docs/api.rst
- docs/changes.rst
- weblate/api/tests.py
- weblate/api/views.py
It is missing there, see #9807
> api: Add listing of components in a component list

- weblate/templates/category.html
- weblate/templates/component.html
- weblate/templates/project.html
- split it to two messages, second part is generic
- clarify that it affects API as well
- clarify that it affects all child components
> ui: Clarify warning about moving/renaming

- weblate/templates/category-project.html
- weblate/templates/category.html
- weblate/templates/component.html
- weblate/templates/language-project.html
- weblate/templates/mail/billing_expired.html
- weblate/templates/project.html
- weblate/templates/trans/delete-form.html
- weblate/templates/translation.html
- weblate/trans/tests/test_manage.py
- weblate/trans/views/settings.py
This hides both renaming and moving to different project or category, so the menu item should be clearer here.
See #9807
> ui: Clarify menu item for moving

- docs/formats/tbx.rst
``<note from="translator">the note from translator</note>``
> Update tbx.rst; typo correction "note from translator"

- weblate/trans/models/component.py
```diff
- msg = gettext("Editing template is not support with this file format.")
+ msg = gettext("Editing template is not supported with this file format.")
```
- ~~[ ] I have added tests that prove my fix is effective or that my feature works.~~
- ~~[ ] I have added documentation to describe my feature.~~
> Fix grammatical error in template validation error message

- weblate/trans/templatetags/translations.py
- weblate/trans/tests/test_templatetags.py
- weblate/utils/tests/test_diff.py
> diff fixes

- weblate/api/tests.py
- weblate/api/views.py
> api: Fix and test categorized translation access

- docs/changes.rst
- weblate/trans/views/edit.py
This seems to perform better in many situations. But needs more testing.
See #9903
>  translate: improve other units performance 

- docs/changes.rst
- weblate/trans/models/project.py
- weblate/trans/views/basic.py
> project: List only uncategorized components on top level page

- weblate/glossary/models.py
There is no need to do that later in Python.
> glossary: use DISTINCT to get distict values from the database

- weblate/accounts/avatar.py
- weblate/machinery/base.py
- weblate/machinery/netease.py
- weblate/vcs/base.py
This is more widely accepted by code linting tools than nosec comments.
> chore: annnotate md5/sha1 uses by usedforsecurity

- docs/api.rst
this is the url that works for me, for example at https://hosted.weblate.org/api/components/tor/tor-browser%252Ftb-aboutdialogdtd/statistics/
> correction

- weblate/auth/models.py
- weblate/auth/tests/test_models.py
This reduces traffic and serialization time for heavy usage of component based permissions.
> auth: Fetch only needed fields for permission check

- weblate/api/views.py
- weblate/lang/models.py
> lang: utilize prefetch to get a default plural

- weblate/api/views.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/views/search.py
We typically do not need these on prefetched query, so reduce trafic and amount of data which needs to be parsed.
> component: defer possibly long text fields

- .github/workflows/migrations.yml
- ci/run-migrate
It will not be supported in 5.1.
Issue #9569
> ci: drop migration testing from 4.x

- docs/changes.rst
- weblate/utils/checks.py
- weblate/vcs/apps.py
- weblate/vcs/base.py
- weblate/vcs/git.py
> vcs: Drop support for deprecated configuration

- weblate/memory/utils.py
Make sure that all parameters are passed to it.
> memory: tighten is_valid_entry API

- weblate/lang/models.py
> lang: drop legacy code

- weblate/templates/accounts/contact.html
- weblate/templates/mail/shared-activity.html
- remove it from the activity mail footer, it can be confusing (see #9983)
- include message about support for other instances on Hosted Weblate only
> contact: clarify contact form disclaimer

- docs/changes.rst
- weblate/auth/views.py
This is expected for people to follow project once they accept an invitation. See #5155
> auth: add project to watched on accepting an invitation

- weblate/auth/models.py
- weblate/checks/models.py
- weblate/lang/views.py
- weblate/screenshots/models.py
- weblate/trans/fixtures/simple-project.json
- weblate/trans/models/change.py
- weblate/trans/models/component.py
- weblate/trans/models/suggestion.py
- weblate/trans/models/translation.py
- weblate/trans/models/unit.py
- weblate/trans/views/basic.py
- weblate/trans/views/changes.py
- add support for language filtering
- make it operate at manager level to utilize object change_set  attributes
- apply project/component filtering only when needed
This improves performance for most of the use cases because the slow path is component restriction, which is rarely used.
> Last changes improvements

- docs/admin/machine.rst
- weblate/machinery/models.py
- weblate/machinery/tests.py
- weblate/machinery/yandexv2.py
Added Yandex Translate v2 to machine translations
Issue - https://github.com/WeblateOrg/weblate/issues/3378#issuecomment-1304545491
> machinery: yandex translation v2

- docs/admin/install.rst
- docs/admin/install/docker.rst
- docs/changes.rst
- weblate/settings_docker.py
- weblate/settings_example.py
This avoids connection overhead from every request.
> config: default to persistent database connections

- weblate/trans/models/component.py
- weblate/trans/models/project.py
This doesn't change that often and is expensive to fetch on the language page.
Fixes WEBLATE-4H5
> project: cache source language ids

- weblate/static/style-bootstrap.css
- weblate/templates/last-changes-content.html
- weblate/trans/models/change.py
- weblate/trans/templatetags/translations.py
This makes it consistent with the top bar and handles categories gracefully.
Fixes #10028
> history: Use breadcrumbs logic for navigation

- weblate/vcs/ssh.py
This allows to fix broken permissions.
Fixes #10025
> ssh: check ssh wrapper permission upon create

- weblate/templates/snippets/list-objects.html
- weblate/trans/tests/test_newlang.py
> list: do not show add icon if user has no permissions

- weblate/templates/category.html
- weblate/trans/forms.py
- weblate/trans/models/category.py
- weblate/trans/models/project.py
- weblate/trans/views/basic.py
- weblate/trans/views/settings.py
> category: Do not show add category form when not possible

- weblate/checks/base.py
- weblate/checks/consistency.py
- weblate/checks/tasks.py
It makes it easier to see what is going on in the background, see #9955.
> checks: log batch check updates

- weblate/utils/views.py
This makes the code more readable and debug in case of crash.
> utils: name functions instead of using lambdas

- docs/vcs.rst
> docs: Clarify search push user

- weblate/accounts/models.py
- weblate/trans/views/basic.py
- weblate/trans/views/js.py
This avoids need to wrap it in additional lambdas.
> accounts: use get_translation_order directly as sorting key

- weblate/screenshots/views.py
Fixes WEBLATE-4NE
Fixes WEBLATE-4KX
> screenshots: Improve error handling

- docs/changes.rst
- weblate/trans/models/component.py
This is needed to distinguish categorized components.
> component: Include category in repo links

- docs/changes.rst
- weblate/auth/models.py
- weblate/machinery/base.py
- weblate/memory/tests.py
- weblate/trans/autotranslate.py
- weblate/trans/models/suggestion.py
This helps to differentiate MT content from other contributions.
See #10063
Issue #3009
> machinery: use dedicated users for MT originated content

- docs/changes.rst
- weblate/addons/base.py
- weblate/addons/generate.py
This makes it easier to spot from where this content is coming.
Fixes #9294
See #3009
> addons: use dedicated author for add-on originated translations

- weblate/vcs/ssh.py
Provide output even in case of parsing failure, so that user can diagnose the issue.
> ssh: consolidate error messages

- weblate/trans/models/change.py
> stats: automatically update last change timestamps

- weblate/trans/models/translation.py
> translation: use change_set to create related change entries

- weblate/settings_test.py
- weblate/utils/models.py
- weblate/utils/stats.py
This is really only useful for testing where the stats are not needed most of the time and slow down tests considerable. On production, the stats need to be updated.
> stats: add lazy mode

- docs/admin/memory.rst
Just some tidy up of the instructions to make them more clear and easier to parse.
Also added a tip that felt was interesting because i have seen many bad translations on the shared memory....
> small corrections, remove unnecessary words, add missing tip

- docs/changes.rst
- weblate/api/serializers.py
- weblate/api/views.py
> api: Fixed some API URLs for categorized components

- .github/workflows/test.yml
- weblate/trans/util.py
> ci: Include Python 3.12 in tests

- docs/api.rst
- docs/changes.rst
- docs/user/files.rst
- weblate/api/tests.py
- weblate/api/views.py
- weblate/formats/exporters.py
- weblate/templates/category.html
- weblate/templates/component.html
- weblate/templates/language-project.html
- weblate/templates/project.html
- weblate/trans/tests/test_files.py
- weblate/trans/tests/test_views.py
- weblate/trans/views/files.py
- weblate/utils/views.py
> files: support converted downloads on all levels

- weblate/templates/snippets/activity.html
#issue #9998 
In this we have made the Activity chart more responnsive.
The bars width  adpts to the width of screen
> activity: The bars width adpts to the width of screen

- weblate/addons/base.py
- weblate/addons/tasks.py
This makes it automatically share repository instance and updates the repo caches. Noticed when reviewing #10100.
> addon: share component instance in eager mode

- weblate/auth/permissions.py
- weblate/templates/snippets/info.html
- weblate/trans/models/suggestion.py
- weblate/trans/models/translation.py
- weblate/trans/templatetags/translations.py
This doesn't change any behavior, just exposes these parameters at translation level so that they can be customized later.
Issue #5447
> translation: add abstraction layer for customizing workflow settings

- weblate/trans/views/basic.py
Perform the filtering in the database and use comprehension to update the list.
> views: optimize fetching ghost translations

- weblate/memory/tasks.py
- weblate/memory/views.py
- weblate/templates/browse.html
- weblate/templates/zen.html
The prefetch fetches categories needed to build full slug and defers loading of huge fields like commit messages what both have positive performance impacts.
> component: use prefetch instead of all

- docs/changes.rst
- weblate/auth/data.py
- weblate/auth/models.py
- weblate/auth/permissions.py
- weblate/auth/tests/test_permissions.py
The names have to be unique to correctly apply filtering on project scoped forms.
> auth: Avoid overlapping permission names

- docs/changes.rst
- weblate/machinery/tests.py
- weblate/machinery/views.py
- weblate/static/editor/full.js
- weblate/trans/templatetags/translations.py
This makes the look consistent with the translations and also highlights things like whitespace. See also #10145
> machinery: Use full highligher for machinery results

- docs/admin/projects.rst
> docs: Clarify Edit base file documentation

- docs/changes.rst
- weblate/addons/consistency.py
It fetched list of the languages from a component instead of a project.
Fixes #10188
> addons: Fix language consistent behavior

- docs/changes.rst
- weblate/accounts/models.py
- weblate/templates/category.html
- weblate/templates/component.html
- weblate/templates/language-project.html
- weblate/templates/project.html
- weblate/templates/snippets/share-menu.html
- weblate/templates/translation.html
- weblate/utils/stats.py
- make share menu reusable across levels
- add share to user configured fediverse server
- built on top of https://github.com/WeblateOrg/weblate/pull/10214
>     user: Add fediverse sharing menu item

- docs/changes.rst
- weblate/utils/checks.py
- weblate/utils/environment.py
- weblate/vcs/apps.py
- weblate/vcs/base.py
- weblate/vcs/git.py
This should make it easy to spot configuration issues like in #10226.
> vcs: add validation for VCS CREDENTIALS

- docs/changes.rst
- weblate/formats/base.py
- weblate/trans/models/translation.py
This makes upload perform faster and allows replacing a file which has syntax errors.
Fixes WEBLATE-52V
> translation: Avoid parsing existing file on replace upload

- docs/changes.rst
- weblate/utils/stats.py
This allows to skip updates when already processed from other source.
> stats: store last update timestamp

- weblate/trans/forms.py
- weblate/trans/models/component.py
- weblate/trans/models/translation.py
This makes it easier to deal with nested components where slug is no longer unique inside a project.
Fixes WEBLATE-4NP
> widgets: use component ID instead of slug in form

- weblate/utils/stats.py
This is triggering unnecessary updates of the parent object.
> stats: honor update_parents flag

- weblate/utils/stats.py
This should reduce impact of fetching many translations where we only need an ID to build stats wrapper.
> stats: Fetch only object IDs

- weblate/utils/stats.py
We never want to go that path, so better to not implement it and use prefetch based solutions only. This will also make it fail gracefully with AttributeError instead of hiding it behind other exception.
> stats: drop individual value calculation

- weblate/utils/stats.py
Remove code which was never invoked and make the API more clear.
> stats: remove unused path percents calculation

- weblate/templates/mail/pending_suggestions.html
- weblate/templates/mail/pending_suggestions_subject.txt
> notification: localize numbers in pending suggestions notification

- weblate/checks/base.py
- weblate/checks/chars.py
- weblate/checks/same.py
- weblate/examples/check_czech.py
- weblate/lang/models.py
It more belongs there rather than to the check.
> unit: Move is_language helper to Unit class

- docs/changes.rst
- weblate/formats/exporters.py
- weblate/formats/tests/test_exporters.py
This is now the upstream recommended encoding.
Fixes #10281
> exporters: Use UTF-8 for iOS strings

- weblate/utils/stats.py
These are present at all levels.
> stats: Always set default value for last_*

- docs/formats/fluent.rst
- docs/formats/go-i18n.rst
- docs/formats/html.rst
- docs/formats/ini.rst
- docs/formats/joomla.rst
- docs/formats/markdown.rst
- docs/formats/qt.rst
- docs/formats/resourcedict.rst
- docs/formats/resx.rst
- docs/formats/stringsdict.rst
- docs/formats/tbx.rst
- docs/formats/txt.rst
- docs/formats/xliff.rst
- Added all the example files to their respective file formats.
- Tested with a local build of the documentation and it looks good.
- Fixes #9078
> Docs: Add file format examples

- weblate/trans/models/change.py
These are updated anyway on update_stats, so there is no reason to do it here second time.
> change: avoid direct updating of last change stats

- weblate/glossary/tests.py
- weblate/machinery/tests.py
- weblate/memory/tests.py
- weblate/screenshots/tests.py
- weblate/trans/tests/test_autotranslate.py
- weblate/trans/tests/test_search.py
- weblate/trans/tests/test_selenium.py
- weblate/utils/db.py
This avoids copying this code to multiple tests.
> tests: move _databases_support_transactions implementation to mixin

- weblate/trans/models/unit.py
- weblate/trans/tasks.py
This needs up-to-date stats, but we don't want to do that until the transaction is committed.
> unit: move completed translation detection to background

- weblate/utils/stats.py
This shares aggregating logic making it shared between more classes.
See #10270
> stats: introduce AggregatingStats helper class

- weblate/trans/util.py
Partial revert of 918893da4a751a20bffd1a13ca6d9c39af4786e5, see also https://github.com/WeblateOrg/docker/pull/1990
> utils: Revert using en_US locales by default

- weblate/checks/utils.py
- weblate/lang/models.py
- weblate/trans/models/project.py
- weblate/trans/tasks.py
- weblate/trans/util.py
- weblate/trans/views/reports.py
- weblate/utils/checks.py
This is easier to read code and performs better.
> chore: use itemgetter instead of lambdas

- weblate/utils/stats.py
- use max/sum to aggegate instead of doing that manually
- use object_list to get source translation
Fixes #10270
> stats: use aggegating functions instead of doing that in a loop
