WeblateOrg/weblate

weblate/trans/tests/test_vcs.py
weblate/trans/vcs.py

Gerrit is a very popular Code Review Tool. It is a git under the hood but uses a specific review command instead of pushes.
To make use of it, the repository needs to contain a .gitreview file as defined at https://pypi.python.org/pypi/git-review#gitreview-file-format
I am rather unsure about the tests, since Gerrit is just with a different push workflow, I just added a class overriding the `VCSGitTest` that basically does the same as the Git Tests but uses a different push method.

Basic Gerrit Support

---

weblate/trans/vcs.py

*config* command is not part of vanilla Mercurial, so usage of *hg config* causes error. Working with Mercurial config file was written by analogy to set_config method of HgRepository class. Also, renamed *key* variable to more canon *option*

Changed method for getting config data for Mercurial.

---

weblate/accounts/models.py
weblate/html/last-changes.html
weblate/html/translate.html
weblate/trans/migrations/0023_perm_save_template.py
weblate/trans/models/unit.py
weblate/trans/views/edit.py

In some cases it will be very helpful to let only managers save template (source) translations. Regular  users (external) should be able to contribute to all other languages only.

Add permission to save template (source) translation

---

openshift/htaccess
openshift/install.sh

Hi Michal
Please note that the current master head doesn't install on OpenShift as the newly released python-social-auth 0.2.5 doesn't install. This doesn't seem to be related to OpenShift as I'm also unable to install python-social-auth 0.2.5 into a local virtualenv (IOError: [Errno 2] No such file or directory: 'social/tests/requirements.txt').
Kind regards
Daniel

Solution for issue #709: Openshift and static files

---

weblate/trans/machine/google.py

Seems that google has changed their API. I now always get error code 503. This a different approach to get only one translation.

Modifed google web translate to changed api

---

docs/admin/config.rst
docs/admin/continuous.rst
docs/admin/install.rst
weblate/appsettings.py
weblate/settings_example.py
weblate/trans/vcs.py

Tries to fix #656. Uses the [`hub`](https://github.com/github/hub) command line tool and requires that is has been set up (either by creating `~/.config/hub` or setting `GITHUB_USERNAME` and `GITHUB_PASSWORD` environment variables). The most complicated part is probably getting the Github username configured for hub out of the config, which is needed because it's also the name of the remote created for the fork (`hub fork`). Maybe there's an easier way?
I thought about using a Github API module for Python instead of `hub`, but this would probably require some admin functions to manage Github API tokens.. using `hub` should be simpler.
I didn't test this too much (and didn't yet add any automated tests), but wanted to get some feedback.. so let me know what you think!
You can see an …

Add GitHub VCS provider.

---

docs/admin/management.rst
openshift/install.sh

This patch prevents updating existing user groups when running an update on Openshift. This preserves any changes made to the default group. Of course this means the administrator might need to manually assign new permissions to the default group, but I think that makes some sense.
I have also included a fix to the documentation regarding the `setupgroups --no-privs-update` option which of course could be applied separately.

Openshift: do not change existing groups on update

---

weblate/trans/checks/base.py
weblate/trans/checks/format.py
weblate/trans/validators.py

Adds a `default_disabled` field to the `Check` class which can be set to disable a check by default. This generalizes the current implementation for the format checks and allows custom checks that are disabled by default but can be explicitly enabled using the proper flag.
This can be used in custom checks as follows:
```
class FooCheck(TargetCheck):
check_id = 'foo'
name = _('Foo check')
description = _('Your translation is foo')
default_disabled = True
def check_single(self, source, target, unit, cache_slot):
return 'foo' in target
```
If this checks gets included it will not be run by default, but one can explicitly set the `foo` tag for a unit. The existing checks in weblate/trans/checks/format.py have been migrated to use this new functionality.
I will write some tests for my own use …

Checks can be disabled by default

---

weblate/accounts/views.py

- Noticed when doing enUS to enGB on Weblate of the Weblate software (how meta...).
- "Can not" here looked weird to me.
- Technically, "can not" is valid, but "cannot" is used more frequently and "can not" with the space is generally used when not able to be a contraction like "can't". In this case, use the version without the space because "You can't change demo account on the demo server" is valid.
(It's worth noting here that I don't know if I've changed it in the right place for it to be included in the translatable strings as well as the code when it gets updated, but I hope so and we'll see!)

Fix typo: "can not" => "cannot"

---

weblate/html/subproject.html

- Contract "can not" to "can't" and rearrange "above list" to be "the list above".
To me at least, this reads better.
Thanks very much for making Weblate! I particularly like the version control integration that pushes changes as correctly attributed commits. (Sorry about all these tiny wording changes.)

Make the "language missing" sentence flow a bit more nicely

---

weblate/html/list-comments.html

We often leave links to documentation or screenshots during discussion with translators in the comments.
This makes those links clickable so they don't have to be copy-pasted anymore.

Make urls in comments clickable

---

MANIFEST.in

When installing the current git repo as a built package I ran into the exception `UncompressableFileError while rendering: 'bootstrap/css/bootstrap.css' could not be found in the COMPRESS_ROOT '...' or with staticfiles.`
This fixes it. (related: #605)

Include static folder in .egg

---

docs/admin/auth.rst

The python blocks are not showing up at https://docs.weblate.org/en/latest/admin/auth.html#cas-authentication - I suspects its because of these two missing newlines (is there an easy way to test this stuff with readthedocs?)

Render Python blocks in the CAS documentation

---

weblate/accounts/admin.py

Since [Django 1.5](https://github.com/django/django/commit/69ff1b7390e140f332a5aa55c44a091c838923fb) `groups` is part of `UserAdmin`'s `list_display` - the filter now shows up twice in the admin.

Remove duplicate groups from list_display

---

docs/user/checks.rst
weblate/trans/checks/base.py
weblate/trans/checks/chars.py
weblate/trans/tests/test_chars_checks.py
weblate/trans/validators.py

This patch is about handling 'maximum length' of translation which discussed in #864.
However, I am afraid that I got the point exactly and my approach is not graceful to implement initial version. Although basic function works, more exception handling is required.
To enable checking 'max-length', the follow steps are required.
1. add 'weblate.trans.checks.chars.MaxLengthCheck' to CHECK_LIST variable at settings.py
2. choose 'Maximum Length of Translation' to Check flags of "source / review " UI
3. then edit value like "max-length:5"
@nijel, could you review my patch and advise me?

Additional flag to check max-length

---

weblate/trans/admin_views.py

[Since Django 1.3](https://docs.djangoproject.com/en/1.4/topics/cache/#memcached) Django ships with a pylibmc cache backend, so we can assume it's a good backend.

Consider PyLibMCCache as a good cache backend

---

weblate/html/i18n.html

The phrase "Argentinean Spanish" is misspelled. Should be "Spanish (Argentina)" because it is a variant of the Spanish language.

Correct syntax variant Spanish

---

openshift/install.sh

This broke with commit 8ddd4b92ec97af3fa14ec9ec2cd83a0eddefce3f since that commit did run sed again on the original requirements.txt, ignoring the previous sed.
The `cat` I added is not necessary, but it reads nicer IMHO. And if somebody wants to add another transformation rules it's easy to understand and do

Fix Openshift install not pinning Django to 1.8

---

weblate/appsettings.py
weblate/trans/checks/angularjs.py
weblate/trans/tests/test_angularjs_checks.py

Adds a check that tries to validate AngularJS interpolation strings like e.g. `"Hello {{username}}"` (see https://docs.angularjs.org/api/ng/service/$interpolate). The check makes sure that any interpolation string used in the source is also used again in the target.
The check is disabled by default and can be added with the `angularjs-format` flag.
I actually found the checks API to be a bit confusing, so I hope I got it right. But this check is working fine for me in production for several months now.

Angularjs interpolation check

---

weblate/accounts/auth.py
weblate/trans/tests/test_permissions.py

The patch provided in #867 was broken, because it was removing _permissions_ where it should have been removing _groups_. So if an ACL-locked group gave you a permission that you already had from elsewhere, it would get removed too.
I have fixed this and added more tests to check for the desired behavior.

fix groupACL locking behavior

---

docs/admin/install.rst

On Debian Jessie libjpeg-dev was required to install Pillow (as specified in requirements.txt). I don't have an OpenSUSE box at hand to test whether it is really called libjpeg-devel.

Doc: Add libjpeg as required package for installations using pip

---

weblate/trans/permissions.py
weblate/trans/tests/test_permissions.py

This is a serious bug in GroupACL code that we discovered when deploying on l10n.opensuse
Basically it boils down to using OR matching instead of, well, more clever matching, for the ACL rules. In effect, a Group ACL set to project+language would affect *all* languages in that project, and the same language in *all* projects. This was not discovered earlier because if a different ACL rule applies to another language, it (correctly) takes precedence and everything looks OK.
This PR contains explanations for current Group ACL tests, a new test for this issue, and a fix for the matching query.

GroupACL partial match bug

---

docs/admin/machine.rst

Prefix `weblate.` was missed all these days!

Translation services' names fixes in docs

---

weblate/trans/machine/microsoft.py

Example of supported locales for MicrosoftCognitiveTranslation: 'af', 'ar', 'bs-Latn', 'bg', 'ca', 'zh-CHS', 'zh-CHT', 'yue', 'hr', 'cs', 'da', 'nl', 'en', 'et', 'fj', 'fil', 'fi', 'fr', 'de', 'el', 'ht', 'he', 'hi', 'mww', 'h', 'id', 'it', 'ja', 'sw', 'tlh', 'tlh-Qaak', 'ko', 'lv', 'lt', 'mg', 'ms', 'mt', 'yua', 'no', 'otq', 'fa', 'pl', 'pt', 'ro', 'r', 'sm', 'sr-Cyrl', 'sr-Latn', 'sk', 'sl', 'es', 'sv', 'ty', 'th', 'to', 'tr', 'uk', 'ur', 'vi', 'cy'
But I use long locale names in my instance of weblate, examples: 'ru_RU', 'it_IT' etc.
That's why I could not use this machine translation service, every language "was not supported" by service.
This code was patched on my production server and worked as expected!

Language conversion fix for MicrosoftCognitiveTranslation

---

docs/admin/config.rst
docs/admin/machine.rst

The old api (see http://wiki.apertium.org/wiki/Old_Apertium_web_service ) required keys, but the new one doesn't (it might in the future, but we haven't had any abuse so far). The old service might still run, sometimes, but it's recommended to either run your own APY server or use https://www.apertium.org/apy/ for single-users

Apertium API keys not used any more

---

weblate/api/serializers.py

The code deleted `or True` causes that ever the response return an empty answer
```python
result['vcs'] = None
result['repo'] = None
result['branch'] = None
result['filemask'] = None
```
The comprobation of the permision is made on `not can_see_git_repository(user, instance.project)`
So the code `or True` is unnecessary

[FIX] serializers: Delete unnecesary True

---

.gitattributes

Not needed when downloading a zip.

Add github dir to export-ignore

---

weblate/trans/vcs.py

'git review' needs --yes as an argument to push commits silently if there is more than one commit.
From ‘man git-review’: “-y, --yes : Indicate that you do, in fact, understand if you are submitting more than one patch.”

allow multiple commits with gerrit

---

docs/admin/deployments.rst

Was a reference to google_auth but these vars are for GitHub.

Fix incorrect link to GitHub authentication.

---

weblate/trans/machine/weblatetm.py

to get the difference of the two machine-translation-engines, show their names in the table instead of a static “Weblate”

differentiate between “Weblate” and “Weblate similarity” in machine translation table

---

weblate/settings_example.py

Maybe this isn't the best way in python, but I was just looking through the changes and thought it might might make it easier for end-users when modifying the list.

Enforce INSTALLED_APPS order in settings_example

---

weblate/legal/templates/legal/index.html

If not terms of service plural, it should be pointed out that it is a document.

The terms of service, email address, indefinetely.

---

weblate/legal/templates/legal/cookies.html

As with #1620 
If not terms of service plural, it should be pointed out that it is a document.

The terms of service, no "purpose", honours

---

weblate/trans/vcs.py

if the component is checked out with weblate and its branch is not 'master', `git review --yes` fails with error message “The branch 'master' does not exist on the given remote 'origin'. If these changes are intended to start a new branch, re-run with the '-R' option enabled.”

add branchname to 'git review' for gerrit push

---

.gitattributes

adds diff filter for .po and .pot files.
before it can be used git needs to be configured:
```
git config diff.msgcat.textconv "msgcat --no-location --no-wrap --sort-output"
```
if you wish to cache callouts of msgcat in `notes/textconv/msgcat`:
```
git config diff.msgcat.cachetextconv true
```

use msgcat for .po/.pot files diff

---

weblate/trans/util.py

We are using a Windows server. For some reason Weblate was not able to call git. When updating the repository I got the following error:
```
ERROR webportal/trunk: failed to update repository: Error in GnuTLS initialization: Failed to acquire random data.
fatal: unable to access 'http://************:********@****************/translation.git/': Couldn't resolve host '************' (128)
```
Calling `git fetch origin` worked perfectly fine.
Allowing the environment variable *SystemRoot* to be passed to git solves this problem.
---
`python manage.py list_versions`returns the following list:
* Weblate weblate-2.18-245-g4e3b780ee
* Python 3.5.2
* Django 2.0.1
* six 1.11.0
* social-auth-core 1.6.0
* social-auth-app-django 2.1.0
* django-appconf 1.0.2
* Translate Toolkit 2.2.5
* Whoosh 2.7.4
* …

Keep "SystemRoot" in get_clean_env()

---

weblate/static/loader-bootstrap.js
weblate/templates/translate.html

in the machine translation tab there is a new column with a progress bar
indicating the quality score of the machine translation
commit for WeblateOrg/weblate#1785

added visualization for machine translation score

---

weblate/lang/data.py

Hi, this is a human-readable alias for Korean language

add a human-readable alias for Korean

---

weblate/templates/accounts/email-sent.html

Consistent spelling of email.
As "French Coordinator OTF/LocLab" said at https://hosted.weblate.org/translate/weblate/master/da/?type=comments&offset=4: "We have 18 occurrences for "email" and 4 for "e-mail". To be consistent, should read "email" everywhere."

e-mail → email

---

scripts/generate-language-data

Hi Michal,
you might want to complete the iso-codes gettext domains for this blacklist.
Regards,
Tobias

Add all iso-codes gettext domains to blacklist

---

weblate/accounts/forms.py

To conform to Django 1.11+ need to pass self.request here so that underlying authentication models get it.
https://docs.djangoproject.com/en/2.0/topics/auth/default/#django.contrib.auth.authenticate
If this is not the case here or is not correct please inform and I will make changes to the underlying authentication model instead
https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#authentication-backends

Pass Request to authenticate

---

docs/user/translating.rst
weblate/static/robots.txt
weblate/templates/translation.html
weblate/trans/autotranslate.py
weblate/trans/forms.py
weblate/trans/tests/test_autotranslate.py
weblate/trans/views/basic.py
weblate/trans/views/edit.py
weblate/urls.py

Added this feature into the automatic translation view. Calling the function from the view works as expected.
I touched/modified all files I am aware of, but there has been a few places where I did not know what to do:
- urls.py (ehance the regexp `r'^projects/' + TRANSLATION + 'auto/$',` by the -mt one): I did not find out if that extension is needed
- test_autotranslate.py: I did add some basic unit tests, but to do some more detailed testing I could not find out how the test model looks like
- command line execution: I did not understand how this exactly works and how I should implement this feature to the command line functions
beside that I changed everything I was aware of

automatic translation via machine translation

---

weblate/machinery/saptranslationhub.py
weblate/machinery/tests.py

the translation hub translation engine was not able to be run on python 3

fix sap translation hub to run on python 3

---

weblate/templates/list-translations.html

This column actually displays number of untranslated strings, so either remove '%' or display percentage. But displaying percentage may be redondant with 'translated' column.

Remove '%' in untranslated column

---

weblate/trans/tests/test_util.py
weblate/trans/util.py

Empty components (like .po files without translation units) shows in the Dashboard as 0%.
This was happening to us after importing automatically many .po files extracted from files that are expected to be empty in some cases.

Show empty files as fully translated

---

docs/admin/quick.rst

Fixes #2140
Formatting might not be entirely correct, I've never used ReST before.  
I've put the virtualenv instructions first, because I find it the easiest and fastest way.  
Let me know about any changes you would like me to make, please.
-----------------------

Include instructions for virtualenv in Quick Install page

---

weblate/addons/events.py
weblate/addons/models.py

This adds new event handler when unit is updated. One specific use case is to call an addon when translation (or unit) state is updated from "Waiting for Review" to "Approved". This uses built-in Django signal `django.db.models.post_save` and filters sender if of class `Unit`.
P.S. This is my first time contributing to open-source would be glad to know how to do it properly. I have missing tests and will be pushed in a while.

Add event `unit_post_save` for use with addons

---

weblate/formats/exporters.py
weblate/formats/external.py

The format is called "Office Open XML", as per https://en.wikipedia.org/wiki/Office_Open_XML
The Excel specific variant markup seems to be "SpreadsheetML", as per https://docs.microsoft.com/en-us/office/open-xml/how-to-parse-and-read-a-large-spreadsheet
Maybe "Excel Office Open XML" is correct? Though the tool should be irrelevant, I assume it is not.

Open XML, Excel interpretation string

---

.github/ISSUE_TEMPLATE.md

using run would launch another instance of postgres and redis,
this not needed and not sure how well postgres handles concurrent writes from different process to same data store.

github/issue template: do not launch new containers to report versions

---

CODE_OF_CONDUCT.md

Critique welcome, changes equally so, I suggest on the basis of being OK to all, from a neutral standpoint of starting afresh.
The credibility of coming from one member of community (not for being a contributor) is at-least better than boilerplate, and it is offered as such.
> Welcome to the Weblate community
>
> Accept and offer criticism constructively.
> Let anyone have the privacy they desire.
>
> Finding yourself unable to do so, e-mail info@weblate.org,
> answered by Michal Čihař, the project maintainer.

Reworked language for avoiding and escalating conflict

---

docs/admin/install.rst

The command, `worker`, must be the first argument.
Tested on celery 4.2.1 (windowlicker)
Signed-off-by: Sun Zhigang <sunner@gmail.com>
Ensured that:

Fix celery worker doc

---

weblate/addons/management/commands/install_addon.py
weblate/addons/tests.py

Without this patch, the newly added testcase breaks on:
```
======================================================================
ERROR: test_install_addon (weblate.addons.tests.CommandTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/sunner/weblate/weblate/addons/tests.py", line 407, in test_install_addon
stderr=output,
File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 141, in call_command
return command.execute(*args, **defaults)
File "/home/sunner/weblate/weblate/trans/management/commands/__init__.py", line 42, in execute
super(WeblateCommand, self).execute(*args, **options)
File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 335, in execute …
```

Fix install_addon breaks on addons without form

---

docs/admin/config.rst
docs/admin/machine.rst
weblate/machinery/base.py
weblate/machinery/models.py
weblate/machinery/netease.py
weblate/machinery/tests.py
weblate/settings_example.py

Netease Sight (https://sight.netease.com/) supports Chinese and English.
It requires posting arguments in json format. Therefore, added one parameter to json_req():
> json_body=False
Signed-off-by: Sun Zhigang <sunner@gmail.com>
Ensured that:

Add Netease Sight translate service

---

ci/requirements-scrutinizer.txt
docs/admin/install.rst
docs/admin/quick.rst
requirements-optional.txt

It was used in older translate-toolkit versions, but it should not be
required now.

Remove Babel dependency

---

weblate/checks/base.py
weblate/checks/consistency.py
weblate/trans/models/component.py
weblate/trans/models/unit.py

For some checks it is better to perform them once after translations are
imported as they do heavy database queries which can be done more
effectively globally on the database side. The typical use case is
consistency check which triggers way too many queries when executed for
each unit, but it's relatively cheap when done globally.
Fixes #2318

Add batch target check operation

---

docs/admin/checks.rst
docs/admin/projects.rst
docs/admin/translating.rst
weblate/trans/forms.py
weblate/trans/migrations/0001_squashed_0143_auto_20180609_1655.py
weblate/trans/models/component.py
weblate/trans/tests/test_component.py
weblate/trans/views/source.py

These no longer configure only flags, so better to have generic name.
Fixes #2310

Rename Quality checks flags to Translation flags

---

dev.Dockerfile

docker container previously moved to python3 as shown here: https://github.com/WeblateOrg/docker/commit/2ff9f50
There is still an issue executing the application within the container, but pip is no longer "missing".
Signed-off-by: Harold Gray <haroldgray3@gmail.com>

change to pip3 to match container's version

---

dev.Dockerfile

Previously choosing python version ambiguously and defaulting to python2.7 as is configured in the container layer above. pip3 installed packages could not be found by python2.7 and it never found the django dependency.
I'm off to bed for now, but I will revisit tomorrow with the aim of getting the dev container to work. :)
Thanks for your patience as I slowly learn python.
Signed-off-by: Harold Gray <haroldgray3@gmail.com>

explicitly launching dev container with python3

---

weblate/settings_dev.py

Signed-off-by: Harold Gray <haroldgray3@gmail.com>
Was getting `ImportError: No module named 'settings_example’`. Set the import to explicitly pull from `weblate.settings_example`.
Dev docker container seems to be working now.

setting module import to explicitly

---

weblate/templates/about/keys.html

This clarifies that it is a commit sent using Weblate, as opposed to on behalf of Weblate itself.

Spelling: "All commits made with Weblate"

---

weblate/accounts/forms.py

Registered a new account and found the description of a field right next to it to be redundant.
It seems to me like this change is not a problem for blind/visually impaired users.
Also, accepting any password, and just disregarding it means it could be omitted altogether.
CAPTCHA, as per https://en.wikipedia.org/wiki/CAPTCHA

Spelling: a unique, CAPTCHA, Leave empty

---

docs/formats.rst

Previous documentation incorrectly mentioned "fuzzy" which is a concept that
does not exists in XLIFF and was also replaced in Weblate by "Needs editing".
More importantly it was very unclear that the `state` attribute is never used
at all. But instead only `approved` attribute is used. That lead to even more
confusion for the reader.
The following tables show all possibles cases in both directions:
| XLIFF file            | Weblate       |
|-----------------------|---------------|
| absence of `<target>` | Empty         |
| absence of `approved` | Needs editing |
| `approved="no"`       | Needs editing |
| `approved="yes"`      | Approved      |
| Weblate            | XLIFF file       |
|--------------------|------------------|
| Needs editing      | `approved="no"`  |
| Waiting for …

Clarify supported states for XLIFF format

---

weblate/formats/ttkit.py
weblate/trans/tests/test_xliff_placeholders.py
weblate/trans/util.py

This is a work in progress and unit tests will be added and squashed when ready. But I wanted to double-check if I am going in the right direction before progressing further.
Given this XLIFF unit:
```xml
<trans-unit id="id-1">
<source xml:space="preserve">source "<x id="INTERPOLATION" equiv-text="{{ angularExpression }}"/>", source.</source>
<target xml:space="preserve">target "<x id="INTERPOLATION" equiv-text="{{ angularExpression }}"/>", target.</target>
</trans-unit>
```
I store in DB the placeholder preserved as XML. So something like the following (after translation of target), note the absence of flags:
In Weblate, it will look like that:
Interestingly I did not implement any checks, but the placeholder are still highlighted. So I guess we don't need to do anything for that part ? …

Add support for XLIFF placeholders

---

docs/admin/continuous.rst

When talking about git the action 'pull' is essentially a fetch + merge. This has tripped me up when reading the documentation and was only made clear to me when reading related issues.
Weblate actually only does a nightly 'fetch' (updating the repository information) and requires additional config to do a merge as well.

Use 'fetch' instead of 'pull' in documentation

---

weblate/lang/data.py

Currenly Weblate consistetnly names plurals based on CLDR naming, so
depending on how many plurals language has each plural form will get one
of following labels: Zero, One, Two, Few, Many, Other
While this works fine for the more complex languages, showing just
Singular/Plural for simple languages with just one plural might make it
easier to understand.
Current displaying:
This PR changes it to:

RFC: Use singular/plural for languages with just one plural

---

openshift3/persistent-mysql.json
openshift3/persistent-postgresql.json
weblate/settings_openshift.py

This is a fix of https://github.com/WeblateOrg/weblate/pull/2477.
There was a small issue with configuration, so cache was not working properly.
By the way - the mysql implementation is throwing some errors - is weblate even meant to be run on mysql? Can I actually remove this, since I'm not sure why would anybody want to switch DBs? And if they do, they should configure it by them self ...

Fix for openshift storage claim

---

weblate/settings_openshift.py

When deploying to openshift, you cannot set `LOGIN_REQUIRED_URLS` via openshift environment variables, since it require an array with regex. 
So I've used same solution as it is in docker container - introduced one more config varable `WEBLATE_REQUIRE_LOGIN` with boolean possible value.

Require login setting for openshift deployments

---

docs/admin/config.rst
weblate/templates/base.html
weblate/trans/context_processors.py
weblate/trans/models/conf.py

This is lightweight variant to using legal app.
Fixes https://github.com/WeblateOrg/docker/issues/76

Add support for specifying legal documents outside Weblate

---

weblate/templates/format-translation.html
weblate/trans/templatetags/translations.py

This closes #2470.
I fixed issues of my previous pull request. 
- The button works in zen mode
- Now copy to clipboard button has the same content as the "Copy" button.
- The button now has more appropriate color and looks fine with long texts (the picture shows it).

Add copy to clipboard featue

---

weblate/static/style-bootstrap.css

Goal is to avoid translator copying the '1' and '2' indicators from the source string when using text selection instead of 'Copy' button
I don't think this warrants a test case...

Disable text selection on badges

---

docs/admin/config.rst
weblate/settings_example.py
weblate/trans/models/conf.py
weblate/trans/models/unit.py
weblate/trans/tests/test_models.py

Use case:
When translating language files which are key value based with short keys like "home.description" and a long translation Weblate currently limits the length of the translation to max(100, source.length * 10), in this example 160 chars. To avoid adding a manual max-length constraint to all keys tapping into this case the option LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH can be set to false. If it's set to false the calculation will be skipped and instead translations up to 10.000 characters are allowed.
Signed-off-by: Enno Woortmann <enno.woortmann@web.de>
- [ x ] Every commit has message which describes it
- [ x ] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ x ] …

Add a configuration option to make the translation length limit based on the source string optional

---

examples/celery-weblate.service

I had trouble with usage of /bin/sh in systemd celery service. The pid wasn't the good one for systemd because of  /bin/sh call to interpret celery command line. Since I found it is not necessary by using environment variable without braces, I'd like to propose this enhancement.
(It seems celery team could be also notified)

fix systemd service example : remove use of /bin/sh

---

weblate/trans/models/component.py
weblate/trans/models/source.py
weblate/trans/models/unit.py
weblate/trans/tests/test_edit.py

This avoids needs to fetch checks for every unit during update, heavily
reducing import time.

Cache checks list while importing component

---

weblate/templates/project.html

I think it makes more sense to go for status here. (Gray label.)

Spelling: is linked to, link → Linked

---

.s2i/action_hooks/deploy

By default, openshift storage has `chmod 660` for all files, but for git and ssh this level of permission on  `id_rsa` file is to wide, so we need to change it after openshift setup script is run.

Fixed issue with wrong permissions for id_rsa on openshift

---

.s2i/action_hooks/deploy

Just found another bug in deployment script. Missing `]`.

Fix a typo in openshipft deployment

---

openshift3/persistent-mysql.json
openshift3/persistent-postgresql.json

This fixes https://github.com/WeblateOrg/weblate/issues/2675, where on build sqlite was actually triggered, instead of psql/mysql. 
This bug affected only build stage, on deployment correct database was used.

Fix openshift deployment to not trigger sqlite on build

---

weblate/trans/models/component.py
weblate/trans/models/translation.py
weblate/trans/tests/test_component.py

In case of many linked components, going one translation by one just to
figure out if there is something to commit is slow. We can better
directly filter translations for the ones with pending units.
Issue #2670

Component: Improve commit pending performance

---

docs/changes.rst
weblate/static/loader-bootstrap.js
weblate/static/style-bootstrap.css
weblate/templates/component-progress.html
weblate/templates/trans/embed-alert.html
weblate/trans/mixins.py
weblate/trans/models/__init__.py
weblate/trans/models/component.py
weblate/trans/models/translation.py
weblate/trans/tasks.py
weblate/trans/tests/test_component.py
weblate/trans/tests/test_manage.py
weblate/trans/views/create.py
weblate/trans/views/manage.py
weblate/urls.py

Should address issue #372 
Steps:

Progress for component import

---

.travis.yml

- base on xenial image
- default to Python 3.7
- default to Django 2.2
- remove tests for no longer support Django 2.0
- test with Python 3.5 (default in Debian Stretch, used on Hosted Weblate)

CI: Adjust Travis CI test matrix

---

requirements.txt
weblate/templates/trans/discover-choice.html
weblate/trans/forms.py
weblate/utils/requirements.py

This requires translation-finder 1.3 which exposes such metadata.

Component: Show origin from translation-finder

---

weblate/addons/forms.py
weblate/addons/gettext.py

Signed-off-by: netniV <netniv@hotmail.com>
Unfortunately the documentation mentioned nothing about the latter two requests so I haven't done those.  This functionality allows you to customise the path to the MO files which may not always be in the same folder as the PO files.
For example, cacti stores it's MO files in /locales/LC_MESSAGES but stores the PO/POT files in /locales/po/.  This change allows you to customise the output by either entering a full path or a relative path (eg, ../LC_MESSAGES)

Allow custom location of MO files

---

weblate/addons/forms.py

If not, what messages are translated?

Spelling: msgid of translated messages → strings

---

weblate/formats/auto.py
weblate/formats/base.py
weblate/trans/models/component.py
weblate/trans/tests/test_files.py

We do not want to perform the validation in all cases, in some places
it's valid to have an empty file (for example in export).

Formats: Move store validation to separate method

---

docs/admin/deployments.rst

docs: fix typo in LDAP auth example

---

weblate/formats/ttkit.py

As per 
https://en.wikipedia.org/wiki/SubStation_Alpha
https://toolkit.translatehouse.org/
https://en.wikipedia.org/wiki/Media_type (used to be called MIME type)
Not 100% sure abut TTKit, from both https://www.thumbtack.com/engineering/adopting-swift-migrating-frameworks-ios/ and https://github.com/CocoaPods/CocoaPods/issues/7584

Spelling: Translate Toolkit, TTKit, iOS strings, SubStation Alpha, media type

---

weblate/templates/addons/squash_help.html
weblate/templates/ratelimit.html
weblate/templates/replace.html
weblate/templates/snippets/legend-button.html
weblate/trans/forms.py
weblate/trans/models/alert.py
weblate/wladmin/sites.py

My rationale is that the indicated state is not multicoloured, so colour indicates is always correct, whereas colours indicate can be misinterpreted.

Spelling: colors indicate → color indicates

---

docs/changes.rst
docs/user/files.rst
weblate/formats/exporters.py
weblate/formats/tests/test_exporters.py

We already partly did this for gettext, it is now complete including
inherited flags from source or component.
Issue #1194

Formats: Export unit flags to xliff and gettext

---

weblate/trans/forms.py

I don't understand "to get access to additional components." Should it be something like "to make use of automated translations from more projects"?

Spelling: Turn on, for the project

---

weblate/addons/resx.py

A lot of guesswork going on here.

Spelling: Avoiding "translation keys". and "units".

---

weblate/vcs/git.py

This change makes weblate work with some custom git versions. The current implementation simply takes the last element from the output of `git --version`, which in the case of git on macOS returns:
```
git version 2.20.1 (Apple Git-117)
```
A more robust check might be to always take the 3rd element from the beginning.
The current VCS test infrastructure does not make it possible to mock the git version output, and the whole `VCSGitTest` class depends on a working `git` right from `setUp`...

git: don't assume the last element is the version number

---

docs/admin/config.rst
docs/admin/install/docker.rst
docs/vcs.rst
weblate/settings_example.py
weblate/trans/models/_conf.py
weblate/trans/tests/data/lab
weblate/vcs/git.py
weblate/vcs/models.py
weblate/vcs/tests/test_vcs.py

This support is based on "lab" CLI, which is inspired by "hub" tool, which is
used for GitHub's pull request support.
"lab" also proxies a lot of commands to "hub", so parts of the Github and
Gitlab's requirements are abstracted out in a mixin class and then only the
basic functionality that is different is implemented via separate classes.
Creating a draft PR for early reviews, will update with test cases soon.

Add support for pushing to GitLab using merge requests.

---

weblate/trans/forms.py

This change follows a previous PR (#3024 ) and adds the ability to switch translation components to Gitlab as a VCS type.

Add the ability to switch to Gitlab as a VCS type for a component.

---

weblate/accounts/migrations/0004_create_profile.py
weblate/accounts/migrations/0006_subscriptions.py
weblate/accounts/migrations/0008_auto_20190426_0941.py
weblate/accounts/migrations/0015_auto_20190922_1948.py
weblate/addons/migrations/0011_squash_addon.py
weblate/addons/migrations/0012_addon_repo_scope.py
weblate/addons/migrations/0013_fix_repo_scope.py
weblate/addons/migrations/0015_flags.py
weblate/addons/migrations/0016_language_consistency.py
weblate/addons/migrations/0017_auto_format_fixup.py
weblate/addons/migrations/0018_resx.py
weblate/gitexport/migrations/0001_squashed_0002_fill_in_url.py
weblate/trans/migrations/0015_linked_component_branch.py
weblate/trans/migrations/0016_fix_alert_occurrence.py
weblate/trans/migrations/0018_remove_unusednewbase_alert.py
weblate/trans/migrations/0024_resolve_auto_format.py
weblate/trans/migrations/0025_auto_20190426_0941.py
weblate/trans/migrations/0026_alert_change.py
weblate/trans/migrations/0029_vote_value.py
weblate/trans/migrations/0034_priority.py
weblate/trans/migrations/0038_contribute_tm.py

Adjust RunPython migation steps to use correct database connection and
mark them as elidable for future migrations squashing.
Fixes #3129

Migrations: Fix multi database scenario

---

weblate/middleware.py

When using Auth0 as authentication provider, admin can set also custom image hosted on some external server. When this occurs, it should be added to `Content-Security-Policy` http header.

Add new url to CSP request header

---

weblate/templates/mail/repository_error.html
weblate/templates/mail/repository_operation.html

Consistent with https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/mail/repository_error_subject.txt#L3

Spelling: in {{ component }}

---

docs/admin/backup.rst
docs/admin/config.rst
weblate/settings_example.py
weblate/utils/models.py
weblate/utils/tasks.py

This PR aims at fixing #3200. 
Specifically it does the following: 
* Add new options to skip backups or to compress DB backups
* Improve documentation

feat: Add some new options for backups.

---

weblate/settings_docker.py

The WEBLATE_GITLAB_USERNAME environment variable is specified in the documentation. But it is never assigned.

Use WEBLATE_GITLAB_USERNAME environment variable

---

ci/run-migrate
docs/changes.rst
weblate/trans/migrations/0053_unitdata.py

This affects Python 2.7 installations. The problem is that dict(Model)
returns more attributes than just fields there, so better to construct
list manually.
Fixes #3342

Migrations: Fix for old Django

---

dev-docker/Dockerfile
dev-docker/docker-compose.yml

Create user and group while building dev-docker image
to fix 'Failed to generate key: b'No user exists for uid ...\r\n''
error when generating ssh keypair via weblate web interface
Signed-off-by: Aleksandr Loktionov <loktionovam@gmail.com>

Docker: Fix user and group in dev-docker

---

docs/api.rst
docs/changes.rst
weblate/api/serializers.py
weblate/api/tests.py
weblate/trans/models/component.py

**Problem**: when a new translation component is created via API `Repository push URL` field became empty (pushing is turned off if this field is empty), so translated strings don't send back to the main VCS.
**Solution**: allow to setup a VCS push URL via API request during component creation.

API: Allow to use vcs push url during component creation via API.

---

weblate/utils/templatetags/icons.py

There are 2 issues with the current code:
1. `DATA_DIR` being ignored for icons (use `settings.STATIC_ROOT`)
2. in case of an exception `icon()` was called with an empty `name`. I could not track where this happens yet, but regardless file reading should handle errors (python2 might need `IOError`, but sorry I don't use python2 anymore, cannot test).
For example:
```
...
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'xxx.xxx.xxx.xxx'. You may need to add 'xxx.xxx.xxx.xxx' to ALLOWED_HOSTS.
During handling of the above exception, another exception occurred:
...
File "/export/apps/weblate/venv/lib64/python3.6/site-packages/weblate/utils/templatetags/icons.py", line 42, in icon
with open(os.path.join(PATH, name), "r") as handle:
IsADirectoryError: [Errno 21] Is a …
```

Fix icon file handling.

---

weblate/accounts/utils.py

`hexlify()` returns `b''` in py3, resulting in usernames like `deleted-2-b'614b67018f'`
This is probably not the most elegant fix, but i dont use python2 anymore, so...

fix hexlify()

---

weblate/utils/checks.py

The check should be applied to the engine instances, not their (unprocessed) configuration. This fixes false positives such as when no `loaders` are defined (cached is added automatically in this case) and/or when `APP_DIRS` is enabled.
Don't encourage cached loader with `DEBUG`.
Get rid of the legacy TEMPLATE_LOADERS.

Make the cached Loader check more robust.

---

weblate/static/style-bootstrap.css
weblate/templates/translate.html

Refs: #3308 
I have fixed the position for the dropdowns in this PR.
For making it inline editing, I think we need to make some design decisions. For example after clicking on the query field, do we show the applied filter (such as `all queries`) also or just replace that part by an input field? If we show the filter, I guess it needs to expand horizontally. Similarly for position, do we show an input field for the page number while still showing the total (I would prefer this)? or just an input box, with a max and min limit.
I also think it will advantageous to move to bootstrap 4 because that gives us the scope to use flexbox directly. Flexbox really helps in designing grid-based UI.
cc: @nijel

Fix the dropdown positions in the pagination tabs

---

docs/user/search.rst
weblate/static/loader-bootstrap.js
weblate/static/style-bootstrap.css
weblate/templates/snippets/query-builder.html
weblate/utils/search.py
weblate/utils/tests/test_search.py

Refs #3409 
I have added the code for allowing exact matches with a term `exact:true`. I haven't added tests or documentation yet. If this method looks good way to proceed with, I will add the corresponding tests and documentation updates.
cc: @nijel

Allows exact match in search

---

weblate/auth/models.py
weblate/auth/permissions.py
weblate/auth/tests/test_models.py
weblate/trans/models/agreement.py

Fetch all user permissiosn in single query. We typically check for bunch
of permissions in every request, so it's better to fetch them all at
once and then do cheap lookups in Python.
This replaces per function cache layer on individual permissions as it
is no longer needed as individual lookups are now cheap.
This is also prepartion for extending permission system in future.
Restrictions or component level permissions are now easier to implement.
Issue #3646
Issue #3267

Auth: Improve permissions caching

---

docs/user/search.rst
weblate/static/style-bootstrap.css
weblate/templates/snippets/query-builder.html
weblate/utils/search.py
weblate/utils/tests/test_search.py

Fixes #3675 
- Used `.input-group-addon` for the exact checkbox instead of an absolute label.
- Fixed the regex expression to match quotes for multi-word expression and without(or with) quotes for single word.
- Added documentation for the same.

Fixes exact checkbox alignment and backend logic

---

docs/api.rst
weblate/api/tests.py
weblate/api/views.py

Resolving: #3076 
Work toward Extending API functionality to allow for the following:
- Getting a list screenshots per component.
- Adding new screenshots.
- Associating strings with screenshots.

Extend API:  Add more api views related to screenshots

---

docs/user/search.rst
weblate/templates/snippets/query-builder.html
weblate/trans/filter.py
weblate/utils/search.py
weblate/utils/tests/test_search.py

New search type allows search for strings with settled context
no matter which context really are.
Fixes #3684

Search: Add ``has:context`` search type

---

weblate/addons/removal.py
weblate/checks/__init__.py
weblate/checks/base.py
weblate/checks/consistency.py
weblate/checks/flags.py
weblate/checks/migrations/0001_squashed_0002_auto_20180416_1509.py
weblate/checks/models.py
weblate/checks/source.py
weblate/checks/tests/test_commands.py
weblate/checks/tests/test_utils.py
weblate/checks/utils.py
weblate/checks/views.py
weblate/trans/filter.py
weblate/trans/forms.py
weblate/trans/models/component.py
weblate/trans/models/project.py
weblate/trans/models/suggestion.py
weblate/trans/models/translation.py
weblate/trans/models/unit.py
weblate/trans/templatetags/translations.py
weblate/trans/tests/test_commands.py
weblate/trans/views/edit.py
weblate/utils/requests.py

It was considered an optimization, but it makes things much worse in several scenarios, especially for bigger projects.
In case we want to revisit this, it might make sense to do some batching for initial import, but for updates batching will almost always perform worse than direct processing as number of changed strings is typically small.
Fixes #3664

Remove batch checks processing

---

weblate/checks/tests/test_markup_checks.py

---
This PR makes markdown links for `md-link` checker order independent.
This closes https://github.com/WeblateOrg/weblate/issues/3651

make md-text link checks order-independent

---

weblate/checks/flags.py
weblate/checks/tests/test_flags.py

Add `markdown-text` as alias for the `md-text` flag.
closes https://github.com/WeblateOrg/weblate/issues/3648

add alias markdown-text for md-text flag

---

docs/api.rst
weblate/api/serializers.py

I'm currently wrestling with identifying approved translations from the API for a translation report. This PR adds an 'approved' flag to the Units API. As far as I can tell there's no test coverage changes required.

Add 'approved' flag to Units API

---

docs/user/checks.rst
weblate/checks/duplicate.py
weblate/checks/tests/test_duplicate_checks.py

Fixes #3702
This check mostly just looks for consecutive tokens that consist entirely of word characters (crucially excluding things like punctuation).
In order to eliminate some false positives, I've added a blacklist of tokens and patterns that are likely to be repeated. I generated this list in the simplest way possible: counting reduplicated terms in a large text corpus and selecting the top terms by frequency. We could do something much smarter (e.g. by using PMI or a classifier), but this is quick and scalable.
Happy to generate similar blacklists for other languages here or in a follow-up PR.

Adds check for duplicate words.

---

weblate/static/icons/sort-ascending.svg
weblate/static/icons/sort-descending.svg
weblate/static/loader-bootstrap.js
weblate/static/style-bootstrap.css
weblate/templates/search.html
weblate/templates/snippets/query-builder.html
weblate/templates/snippets/query-field.html
weblate/templates/snippets/search-form.html
weblate/templates/translate.html
weblate/templates/zen.html
weblate/trans/filter.py
weblate/trans/forms.py
weblate/trans/models/unit.py
weblate/trans/tests/test_selenium.py
weblate/trans/views/edit.py
weblate/trans/views/search.py
weblate/utils/forms.py
weblate/utils/views.py

Separates the query search field from the pagination part and adds filters
and sorting options in UI

Query Field: Separates query field from the pagination part

---

docs/changes.rst
requirements.txt
setup.cfg
weblate/trans/models/component.py

This avoids several race conditions when running concurrent updates. In
case the lock can not be obtained, the update is scheduled in background
and retried until the lock can be obtained.
Fixes #25
Fixes WEBLATE-3RA
Fixes WEBLATE-3JC
Fixes WEBLATE-3QQ
Fixes WEBLATE-3QH
Fixes WEBLATE-3QG
Fixes WEBLATE-3NP
Fixes WEBLATE-3QD
Fixes WEBLATE-3QC
Fixes WEBLATE-3Q4
Fixes WEBLATE-3Q3
Fixes WEBLATE-3NM

Component: Lock for updating translations

---

weblate/templates/fonts/font_detail.html
weblate/templates/screenshots/screenshot_detail.html

Not 100% sure about the fonts, but this situation is prevented
Created on  ...................................................................5 months ago
[Created on](https://hosted.weblate.org/translate/weblate/master/en/?checksum=3beb7745147a7faf ) ...................................................................[%(count)s months ago](https://hosted.weblate.org/translate/weblate/master/th/?checksum=d0fd21d070c7bd)
Probably fails in some languages, but alas.

Spelling: Created -on x2

---

docs/admin/customize.rst

The reference wouldn't be linked otherwise.

Docs: fix reference to own checks

---

docs/admin/customize.rst
docs/contributing/internals.rst

Came across these while reading through docs.

Docs: fix typos and update internal modules list

---

weblate/static/loader-bootstrap.js

On Mac this ends up mapping to `command+s` whereas on Windows and Linux it maps to `ctrl+s`. This is available since Mousetrap 1.4.

Shortcuts: bind using `mod` cross-platform modifier

---

weblate/formats/exporters.py
weblate/formats/tests/test_exporters.py
weblate/templates/snippets/unit-state.html
weblate/templates/translate.html
weblate/trans/models/__init__.py
weblate/trans/models/unit.py
weblate/trans/tests/test_edit.py
weblate/trans/tests/test_suggestions.py
weblate/trans/views/edit.py

Fetch all checks once and then generate needed filters on Python
side. In most cases we are needed all of them anyway, so better
to do the query just once instead of repeating that.

Checks: Reduce need of database queries when rendering unit

---

docs/admin/install.rst

Clarify  SECURE_HSTS_SECONDS setting documentation
- Explicitly mention how and why to enable it.
- Link to relevant Django docs.
Fixes [ #3784 ](https://github.com/WeblateOrg/weblate/issues/3784)
I have tested this on my local machine with Sphinx. As its a change in the documentation, please let me know if the sentences are clear and as per standards.

Added changes to document for SECURE_HSTS_SECONDS

---

docs/changes.rst
docs/user/translating.rst
weblate/static/loader-bootstrap.js

* Brings back to life "dismiss check" shortcut
* Adjusts shortcut tooltip help based on the platform
* Fixes docs on Mac shortcuts.
Fixes #2034.

Shortcuts: fix `mod+i <N>`

---

docs/api.rst

Fixes #3890 
Adds documentations for POST request in users, groups and roles API along with example data in users and groups API

Adds docs for POST in users, groups and roles API

---

weblate/templates/paginator.html
weblate/templates/translate.html

Otherwise, "Enter position to jump to".

Spelling: Jump to

---

weblate/trans/migrations/0064_fulltext_index.py

Use a local check to run CREATE EXTENSION only if extension is not installed already.
`0064_fulltext_index.py` tries to install `pg_trgm` with `IF NOT EXISTS`. Unfortunately that still requires superuser privileges. The manual mentions, that it's possible to install the extension manually but that is not supported by the migration in it's current form.
This is a bigger issue with django itself as well.  It already defines a migration operation `TrigramExtension` to help with the installation of this extension.  I guess it's not easy to use it in this case because of the Mariadb/Mysql/Pgsql 🍝  :D
But in the same way the django docs mention the possibility to install extensions manually, but would fail in the same way on these Operations …

CREATE EXTENSION ... IF NOT EXISTS still requires superuser

---

weblate/templates/snippets/list-objects.html
weblate/templates/trans/embed-alert.html

Text before:
Text after:
Icons before:
Icons after:

Listings: avoid extraneous underline on hover

---

weblate/static/editor.js
weblate/static/loader-bootstrap.js
weblate/templates/base.html
weblate/templates/translate.html
weblate/templates/zen.html

This moves the code as-is from a globally-included script file to an
editor-specific script. It includes code for both regular and zen mode
editing.
Further improvements should be made on top of this to avoid leaking
global variables and/or ensuring only editor mode-specific code is
initialized.
Fixes #3875.

Editor: move client side code apart

---

weblate/static/editor.js
weblate/templates/base.html
weblate/templates/translate.html
weblate/templates/zen.html

* Moves initialization out of the global scope into a function
* Sets up events as delegated, i.e. no need to re-attach handlers when new contents are loaded (e.g. in Zen mode)

Editor: use delegated events

---

docs/admin/addons.rst
weblate/addons/forms.py
weblate/addons/git.py
weblate/addons/tests.py
weblate/vcs/git.py

Fixes #3709. Support appending trailers and overriding the commit message.
Draft PR because I'm not sure how to approach adding tests for this, the existing tests are only counting the number of commits that are produced, not the commit messages produced. Some pointers to what you'd like to see here would be helpful.

Update the Squash addon

---

weblate/static/editor.js
weblate/static/editor/base.js
weblate/static/editor/full.js
weblate/static/editor/zen.js
weblate/templates/translate.html
weblate/templates/zen.html

* Avoids polluting the global namespace
* Makes the distinction between full & zen modes more explicit (more to come)
@nijel I ignore what's the set of browsers Weblate is meant to support, so I kept on using ES5 language features.

Editor: separate full & zen modes

---

weblate/static/editor/base.js
weblate/static/editor/full.js

* Moves all remaining code to full mode (bug reporting, translation area persistence)
* Reuses jQuery objects as much as possible
* Binds events to `$editor` when possible
* `localStorage`-related cleanups

Editor: move remaining code to full mode

---

weblate/static/editor/full.js
weblate/static/editor/zen.js

The conversion to arrow functions for now only happens where previously
`var self = this` was necessary.
Refs. https://github.com/WeblateOrg/weblate/issues/4034#issuecomment-644618132

ES2015+: use arrow functions where applicable

---

weblate/static/editor/full.js

The previous code was assuming synchronous behavior, when it truly is
asynchronous. Therefore the translation textarea `focus()` was always
occuring before the modal was closed, and the modal puts the focus
elsewhere after it being closed.

Glossary: fix focusing after closing dialog

---

weblate/templates/accounts/user.html

Spotted by @rffontenelle 
In my head "Contributed projects" means projects the user has put (contributed) onto/on the platform.

Spelling: Screenshot (singular), Project contributions

---

weblate/checks/consistency.py
weblate/locale/django.pot

The string "This string has been translated in the past" changed to "This string has been translated in the past. Last translation was %s".

"String translated in the past" warning enhancement

---

weblate/addons/base.py
weblate/addons/git.py
weblate/trans/models/component.py
weblate/trans/models/translation.py
weblate/trans/tests/test_remote.py

Reuse the same commit code in component, translation and addons. This
makes the commit behave consistently (for example it properly pushes and
sends signals).
Fixes #3708
Fixes #3707

Component: Consolidate commit code

---

docs/admin/access.rst

Adds one extra line between each privilege description to prevent
getting them together in a single line, breaking the rendered docs

Docs: break lines from access.rst

---

docs/workflows.rst

Empathize Translate, Translators, Review, and Reviewers as they are access and group names. Also replace 'access control' with ref link to 'Access control' page.
Also use on and off (lowercase letters) to reuse occurrences from Weblate/Application component.

Docs: Improve translation workflow tables

---

docs/wlc.rst

This proposal changes the rendered text from
> You need to install `wlc`:, wlc to use these.
to
> To use the commands below, you need to install `wlc`:
Notice the ":" misplaced in the currently publish doc.

Docs: Fix install wlc phrase

---

docs/changes.rst

Thanks in advance for fixing this typo.

Fix typo: translsate -> translate

---

docs/user/checks.rst

Replace button label "Use this string" with "Use this translation", to conform with [weblate/templates/trans/other-row.html], line 17
[weblate/templates/trans/other-row.html]: https://github.com/WeblateOrg/weblate/tree/master/weblate/templates/trans/other-row.html#L17

Docs: Fix Use this translation button label

---

docs/admin/config.rst

'checks' link already is rendered as 'Quality checks', so having 'quality' in the paragraph results in having duplicate quality in the resulting string.
How is the documentation currently:
> All built-in quality [Quality checks](https://docs.weblate.org/pt_BR/latest/user/checks.html#checks) are turned on by default (...)

Docs: Remove duplicate quality word

---

docs/admin/admin.rst
docs/admin/auth.rst

* `admin/admin.rst`: sections below -> sections above, see commit message:
> The paragraph uses 'sections below', using as an example
'Weblate translations'.  However, this and other sections
are found only in one of this page's screenshots which can
be found ABOVE, not BELOW, this paragraph.
Therefore, use 'above' to fix the reference's direction.
* `admin/auth.rst`: spelling fixes:
> 'inbuilt' -> 'built-in'
'Django based project' -> 'Django-based project'
'OpenID based services' -> 'OpenID-based services'
'tenant specific' -> tenant-specific'

Small doc fixes

---

weblate/templates/translation.html
weblate/trans/views/basic.py

Here is my fix to #4220, which does the following:
1. Limit the number of "Other components" displayed to 10, preferring untranslated ones
2. Template: Add a link to the full list of components

Fix: Limit number of components displayed on translations overview page

---

docs/api.rst
weblate/api/tests.py
weblate/api/views.py

Extends screenshot API

---

weblate/trans/views/edit.py

this happens for translation types where source can be empty like "gettext PO file (monolingual)"
Signed-Off-By: Matthias Blümel <matthias.bluemel@krumedia.com>
It's probaly better to filter them in the lines above but I don't know how

skip strings with empty source for "other occurrences"

---

weblate/locale/zh_Hans/LC_MESSAGES/django.po

The time hit in english is `Appeared %(first)s, last seen %(last)s`, it's right.
But the wrong translate appear in chinese, what seems like 
>14 小时前天前出现，最后露面12 小时前天前
It's so funny

fix: wrong time hint in chinese

---

weblate/checks/chars.py
weblate/checks/models.py
weblate/checks/tests/test_chars_checks.py
weblate/settings_docker.py
weblate/settings_example.py

A little spell bug, the right spell `Punctuation`  has occurred [here](https://github.com/em0t/weblate/blob/2b99426d55bac2387809e88fc56aaf178c5fd836/weblate/checks/chars.py#L389)

fix: wrong Puctuation class name to Punctuation

---

docs/changes.rst

Change "automated suggestions" to "automatic suggestions" to match the rename on aea07a13

docs: Fix automatic suggestions name

---

weblate/trans/views/files.py

Fixes https://github.com/WeblateOrg/weblate/issues/4491
In addition to this, we should probably be updating weblate/templates/component-list.html to prevent showing the Download button  if no components are visible. I'm not familiar with this framework as to how to do it, though

Files: Return a filtered component view for zip file download requests

---

weblate/vcs/ssh.py

Newer GitLab needs a host key with minimun 4096 bit lenth.

Generate 4096 bit RSA host key

---

weblate/checks/management/commands/list_checks.py
weblate/templates/trans/alert/duplicatelanguage.html
weblate/utils/django_hacks.py

Fixed two small typos found in the source files:
immediatelly ⇒ immediately
shoud ⇒ should

Fix small typos

---

weblate/api/serializers.py
weblate/api/tests.py
weblate/api/views.py
weblate/trans/views/create.py
weblate/utils/views.py

Adds support to create components using docfile and zipfile via API

---

weblate/static/loader-codemirror.js
weblate/static/style-bootstrap.css

This fixes #4442 and the following changes were made:
1. Wrap comment-area so that long comments without space does not overflow horizontally.
2. Wrap comment textarea using [`lineWrapping`](https://codemirror.net/doc/manual.html#option_lineWrapping) option from CodeEditor. This prevents comment text from having a horizontal scroll.
3. Make comment textarea automatically resize to fit its text

Fix: Wrap comment text and make comment textarea automatically resize itself

---

requirements-optional.txt
weblate/machinery/googlev3.py
weblate/machinery/tests.py

The Python module API has changed in a not compatible way, see
https://googleapis.dev/python/translation/latest/UPGRADING.html
Fixes #4358
Fixes #4281
Fixes WEBLATE-4X8
Fixes WEBLATE-4XA
Fixes WEBLATE-4X9

Machinery: Upgrade Google Translate to google-cloud-translate 3.0.0

---

weblate/templates/manage-access.html

A confirmation box was added using modals when removing user from a project.
Issue: #3667

Added a confirmation box when removing user from a project

---

weblate/templates/manage-access.html

- username bold to make it more visible
- message clearer to prevent potential guessing if translations of the removed user stay
seems that covering this is not needed, @nijel let me know if you think that something should be modified at https://docs.weblate.org/en/latest/admin/access.html?highlight=access#managing-per-project-access-control

rewording and bolding access removal message

---

weblate/templates/engage.html

Fix the problem found on this page (https://hosted.weblate.org/engage/ut-tweak-tool/):
* "The translation project for ut-tweak-tool currently contains **251 string** for translation."

fix(engage.html): fix plural `string` => `strings` & fix comment typo

---

weblate/formats/txt.py

Google Play allows up to 50 characters for the title
Allows title.txt for Fastlane to be up to 50 characters instead of up to 30 as Google Play allows up to 50:
I'm using this option to ping @eighthave to ensure F-Droid is also aware of the 50 character limit of Google Play.

Allow 50 characters for app store title

---

weblate/lang/models.py
weblate/lang/tests.py

This change fixes issue with incorrect language code being used for creating translations. https://github.com/WeblateOrg/weblate/issues/4966

Fix for incorrect language being chosen #4966

---

weblate/templates/manage/billing.html

Page shows "Commerial" but I assume the correct is "Commercial".

Billing: fix typo commerial

---

docs/admin/deployments.rst

Cloudron has a 1-click installation package for Weblate and we make sure all instances are automatically kept up-to-date.
The package is at https://git.cloudron.io/cloudron/weblate-app where we also maintain selenium e2e tests, which have to succeed before we push an update. Usually updates happen withing a few days from upstream release.
Previous attempt at the wrong page https://github.com/WeblateOrg/weblate/pull/5065

Add Cloudron installation method

---

docs/api.rst

Cleanup a little terminology mess and mistakes created by the rename of 'fuzzy strings' to 'strings marked for edit' on the API documentation.
Due to the API uses the term `fuzzy` and UI uses `marked for edit` I suggest to mention both on the API docs. Also fix a probably mistaken naming of `fuzzy strings` as `marked for review`.

Docs: minor terminology cleanup in api.rst

---

weblate/lang/models.py

There is a small typo in weblate/lang/models.py.
Should read `unknown` rather than `uknown`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, uknown -> unknown

---

weblate/formats/tests/test_formats.py
weblate/formats/ttkit.py
weblate/trans/tests/data/xwiki_new_language.properties

Those changes aims at fixing #5040.
Basically the idea is to ensure that in case of a new language the unit is properly retrieved and not marked as missing.

Fix problems when saving XWiki properties.

---

weblate/checks/same.py

Hello,
I'm [trying](https://github.com/WeblateOrg/weblate/pull/5248) to support a new programming language (Lua, flagged as `#, lua-format`), and I noticed weblate.checks.same was aware of several format string flavors in its own right.
To avoid making this worse by making weblate.checks.format better, I propose a simple refactoring so the "same" check automatically picks up enhancements like this.
Either this is a good refactor (and some of the above criteria are inapplicable), or it's problematic and we can take another approach.
Honestly, it's probably not too bad to merge #5248 and leave this alone, but I felt like I had to provide an alternative.
All the best,
Justin

Refactor checks.same to keep feature parity with checks.format.

---

docs/admin/checks.rst
docs/changes.rst
docs/user/checks.rst
weblate/checks/format.py
weblate/checks/models.py
weblate/checks/tests/test_format_checks.py
weblate/settings_docker.py
weblate/settings_example.py

Hello, I'd like to fix issue #4289 (Support Lua format) as my first contribution.
For Weblate's purposes, a Lua format string is a C format string. (The differences are that some features supported by `printf()` in C are errors in Lua, and the allowed type codes -- which Weblate does not police in any case -- include 'q'.)
Because of the close relationship between Lua and C format strings, I believe we can be content with a very simple unit test (same as the corresponding feature for Perl, for instance).
As a new contributor who'd previously only used hosted Weblate, I may have missed a step in the end-to-end delivery of this feature. (Hopefully not.)
Because weblate.checks.same makes an apparent effort to maintain parity with weblate.checks.format, I'm opening a separate PR to ensure it …

Support Lua format strings. Fixes #4289.

---

requirements.txt
weblate/settings_example.py
weblate/trans/autotranslate.py
weblate/trans/bulk.py
weblate/trans/models/translation.py
weblate/trans/models/unit.py
weblate/trans/views/search.py
weblate/utils/db.py

This reduces locking congestion on doing updates as it holds only row
level locks and not table level ones for primary key.
Needs Django 3.2 (not yet released), see https://code.djangoproject.com/ticket/30375 and https://github.com/django/django/commit/a4e6030904df63b3f10aa0729b86dc6942b0458e

Trans: Disable key locking in select_for_update

---

docs/vcs.rst

Should it be "SVN co" instead of "svn co"? Not sure what that is.

Tune-up of VCS documentation

---

weblate/auth/permissions.py
weblate/trans/forms.py
weblate/trans/models/translation.py
weblate/trans/tests/test_edit.py

This adds/removes units on all translations. Both bilingual and
monolingual formats behave consistently regardless there is difference
in how the units are stored.

Translation: Support for adding/removing units on bilingual source

---

docs/devel/translations.rst

Fixes #5235
Check English label names.
Needs something about how it works for different formats, mono-/bilingual files.
Screenshots, formatting?
Edit: It doesn't make any sense that removal of languages is "Tools > Removal" while project and component removal is in "Administrate" > "Removal" (?)

Document translation removal

---

docs/changes.rst
weblate/static/loader-bootstrap.js
weblate/static/style-bootstrap.css
weblate/templates/dashboard/user.html
weblate/templates/paginator.html
weblate/templates/project.html
weblate/templates/snippets/list-objects.html
weblate/trans/views/basic.py
weblate/trans/views/dashboard.py
weblate/utils/views.py

In case there is 1k+ components in a projects, the generated page is
huge and takes long to load and render.
This partially reverts 2cddd81be2b8e8cc38d5bfce4aa687fd921897bb from
pull request #4349, ordering as requested by #3011 is still to be
addressed.
Fixes #5513

Project: Bring back pagination to component listing

---

docs/user/translating.rst

Before:
After:
See: https://docs.weblate.org/en/latest/user/translating.html#keyboard-shortcuts

Docs: fix shortcut format

---

docs/faq.rst

VCS less operation -> VCS-less operation
https://docs.weblate.org/en/latest/faq.html#does-weblate-support-other-vcses-than-git-and-mercurial

Docs: Add hiphen to compound adjective

---

docs/user/checks.rst
weblate/checks/format.py
weblate/checks/models.py
weblate/checks/tests/test_format_checks.py
weblate/settings_docker.py
weblate/settings_example.py

Fixes #5504.
This adds scheme format checking.
Lint passes, but I have two failing tests. I have  copied tests from php, and adapted them to scheme syntax, but I might not understand fully what they are testing. The two failing tests are:
```
2021-03-06T21:37:47.5201557Z ----------------------------------------------------------------------
2021-03-06T21:37:47.5203539Z Traceback (most recent call last):
2021-03-06T21:37:47.5206320Z   File "/home/runner/work/weblate/weblate/weblate/checks/tests/test_format_checks.py", line 306, in test_missing_tilde_format
2021-03-06T21:37:47.5208133Z     self.check.check_format("~s~~ ~~", "~s~~ tilde", False, None)
2021-03-06T21:37:47.5210472Z AssertionError: {'missing': ['~'], 'extra': []} is not false
2021-03-06T21:37:47.5211631Z …
```

Formats: Add scheme format.

---

docs/formats.rst

I believe "state" should not be translated, since it is the name of an attribute. So, marking it as ``` ``literal`` ```.

formats: make "state" attribute literal

---

weblate/templates/translation.html

Not 100% sure this is better, I think I have seen "offline translation" somewhere else.

Spelling: Suitable for offline translation

---

docs/admin/management.rst
docs/changes.rst
weblate/trans/management/commands/auto_translate.py

Add translation mode support to `auto_translate` management command following that it already exists in the [Web Interface](https://docs.weblate.org/en/latest/user/translating.html?highlight=automatic%20translation#automatic-translation).
```shell
$ docker-compose exec weblate weblate auto_translate -h
usage: weblate auto_translate [-h] [--user USER] [--source SOURCE] [--add]
[--overwrite] [--inconsistent] [--mt MT]
[--threshold THRESHOLD] [--mode MODE]
[--version] [-v {0,1,2,3}] [--settings SETTINGS]
[--pythonpath PYTHONPATH] [--traceback]
[--no-color] [--force-color]
project component language
performs automatic translation based on other components
positional arguments:
project               Slug of project
component             Slug of component
language              Slug of language …
```

auto_translate management command: Add translation mode support

---

docs/conf.py
weblate/glossary/tasks.py
weblate/trans/bulk.py
weblate/trans/exceptions.py
weblate/trans/models/component.py
weblate/trans/tasks.py
weblate/trans/views/git.py
weblate/utils/lock.py
weblate/vcs/base.py

- The code is now shared for repo and component level locking
- It prefers Redis based locking as that usually performs better
- The Redis locks will also nicely work in a distributed environment
(#2984)

Utils: Use single class for handling locks

---

docs/admin/continuous.rst

`--all` -> `\--all` to prevent Sphinx from rendering `--` as `–` (en-dash).
Current text in documentation:
Text after the fix:
Link: https://docs.weblate.org/en/latest/admin/continuous.html#updating-repositories

[docs] Fix --all flag

---

weblate/vcs/base.py
weblate/vcs/git.py

The git status updating of index is optional, so better to disable it
and avoid locking completely here.
Fixes #6036

vcs: Avoid locking for getting repository status

---

docs/admin/config.rst
weblate/settings_docker.py
weblate/trans/models/_conf.py
weblate/utils/views.py

Component pagination is great, but it's better to be able to tune in each different project (with a default option of 100, like now).
For a project with 500 components, 100 components per page it's ok (only 5 pages).
But for a project with 5000 components, 100 components is very low (50 pages are a lot of pages). So let the admin decide which size is better for his users.
Improves #5513 and references #6034

[IMP] Default Pagination on Environment Variable

---

docs/user/search.rst
weblate/utils/search.py
weblate/utils/tests/test_search.py

Component name is available on search now.
Searching by component:`slug` is not useful due to the possible lack of knowledge of Users. 
Users don't need to know what `slug` is, so most of the time, they will search for **component name**, because is the only text inside the weblate page that refers to the component.
So, the new way to search for component names will be: 
`component_name`:_substring of component name_

[IMP] Component name available for searching

---

weblate/accounts/templatetags/authnames.py

Fixes #6216
Fix the issue with overriding title/image for auth providers with dashes ('-') in the name

accounts: Fix overriding name and image of auth

---

docs/api.rst

The form parameter for how to handle a conflict when uploading a file is called "conflict", not "conflicts". I have figured this out through trial and error, but not verified in code.
POSTing with "conflicts" returns a "bad request (400)" error.
I propose to fix the typo in the documentation.

Fix typo in documentation ("conflict" form parameter)

---

dev-docker/docker-compose.yml
weblate/settings_docker.py

The Docker image for weblate was recently updated to use a newer version of Debian, and a newer version of Python (https://github.com/WeblateOrg/docker/commit/a86df5b527e20cd86df4596d6d4a59ce79da62bb). There are still docker files in the main repository assuming the use of Python 3.7, however.
This PR updates the paths directly related to docker to use `/python3.9/` rather than `/python3.7/`. Without these changes, trying to run a local development Docker image with `rundev.sh` will not actually use your local version of weblate.
There are also some strings in the documentation that refer people to Python 3.7, but as those aren't directly related to Docker I've left them as they are.

Fix Docker paths (python3.7 -> 3.9)

---

weblate/settings_docker.py

As per documentation: 
https://docs.weblate.org/en/weblate-4.8.1/admin/install/docker.html#envvar-WEBLATE_PRIVACY_URL
should be available to docker installations but is not working (nor available) as per 4.8.1.
`.py` files throw `EXE002` errors on flake8 check, by the sheer number I'm guessing this is supposed to be correct.

Add WEBLATE_PRIVACY_URL to docker settings

---

docs/admin/install/docker.rst

This section also hints to the setting type which will help administrators understanding the scope.
The docker part of the documentation is missing the `WEBLATE_AUTO_UPDATE` setting which can be quite useful.
Things to consider in terms of documentation quality:
I had to learn the hard and manual fiddling fiddling way that a lot of settings work different or not to their full extend as the source installation versions. As example: `full` is not a valid setting in docker context because the setting is evaluated by a function that looks for boolean kind of strings.
Right now this forces administrators to dig through the code which can slow down deployment processes. 
Possibly the documentation could point out the setting type. Don't know.

Add missing WEBLATE_AUTO_UPDATE option to docs

---

docs/admin/install/docker.rst
weblate/settings_docker.py

New logic to obtain Google Translation API v3 environment variables from the docker compose environment (see https://github.com/WeblateOrg/docker-compose/pull/109).
Set variables defined by proposed change to the docker compose environment.
Trivial change.

docker: Add support for Google Translate v3

---

weblate/templates/trans/alert/ambiguouslanguage.html

At first I thought this meant
"Different components of the same language are using ambiguous language codes"

Spelling: Clarify ambigous language codes in use

---

weblate/templates/mail/account_activity.html

As the last possible means of quality control, despite statements as to how flawed it was, this has been implemented knowingly. The problem isn't so much discarding better alternatives as it is a disregard for all other means of available help beyond pointing out basic errors.
Between the uncalled-for description of me in abolishing the review team and what members of it instrument on their own accord, the process speaks for itself.
Happy to return to fixing problems as they exist, and not deal with problems relating to interpersonal conflicts as they are created, which I still refuse to do.

Account_activity language reworked

---

weblate/templates/accounts/email-sent.html

>Password reset almost complete
Account removal almost complete
Registration almost complete
I like "nearly" here. In my head that means more of ~the full effect is near, rather than "it is somewhat done, but written badly".
@orangesunny, thoughts?
Or "Nearly there" "Almost done" "Almost finished", "one more step" might work(?)
Something about the original sounds a bit like those spammy type of register-to-win guaranteed deals.

Snuplification of e-mail sent language

---

docs/changes.rst
docs/user/translating.rst
weblate/trans/models/unit.py

This is similar approach to what we use in source review - the label is
automatically created when needed.
Fixes #6774

unit: Label automatically translated strings to ease their filtering

---

weblate/trans/models/component.py

When adding a new component for the same repository a while ago, it wasn't clear to me (as a relatively new user to Weblate) why I could not add certain settings. Following my support request (ticket number 204939) a change was made to the docs (https://github.com/WeblateOrg/weblate/commit/2406024b3f659ba401465cf1b6e998b86456979a). This PR makes it immediately clear to the user what is happening, and that it is fine that the field is empty.
- ?? Lint and unit tests pass locally with my changes.
- N/A I have added tests that prove my fix is effective or that my feature works.
- N/A I have added documentation to describe my feature.
- N/A I have squashed my commits into logic units.
I hope the code style is correct :) Tried to imitate what I saw above & below the changed lines. EDIT: Ah, …

Explain in Warning what will happen with linked component settings

---

docs/devel/community.rst

The guidance to build a translator community is updated with the content from #3084
I haven't run any test, because this is only a change of the documentation. The sources of the guidance are in the description.
Should we include the terminolgy #243 into the checklist (and its screenshot)?

Update community.rst from #3084

---

docs/changes.rst
weblate/addons/git.py

Picking the first ends up duplicating commits, every time it gets squashed it gets a new Change-Id.
Pick the last instead to hopefully try and avoid that.
Fixes: 2f93229
See #7067

addons: Use last Change-Id instead of first one

---

docs/admin/config.rst
docs/admin/install/docker.rst
weblate/settings_docker.py

Allow changing `DEFAULT_PULL_MESSAGE` in a docker compose environment using the environment variable `WEBLATE_DEFAULT_PULL_MESSAGE`. Document behaviour in `docker.rst` and `config.rst`.
Closes #7204
I've not yet come around to test this, as `./rundev.sh test` fails with `panic: handle is invalid` for me, presumably as I'm on windows. It would be really kind, if someone else would be able to lint and run unit tests as well as trying the feature. Otherwise I will try to get back to this as soon as I find some time to test :)

docker: allow changing `DEFAULT_PULL_MESSAGE`

---

weblate/vcs/git.py

Make sure that all user provided input is handled as expected.

vcs: Improve git parameters handling

---

weblate/templates/accounts/user.html

A while ago the configuration of the `liberapay.org` domain was changed to redirect all requests to the home page of the `liberapay.com` domain, so the links that Weblate generates no longer lead to the intended pages.

Fix links to Liberapay profiles

---

weblate/trans/exceptions.py
weblate/trans/models/component.py
weblate/trans/models/translation.py

Parse the template at the point we will actually need it (once a change
in one of the translations is detected).
Fixes #7383

component: Postpone template validation until it is really needed

---

weblate/templates/base.html
weblate/templates/snippets/position-field.html

This should hint the browser to consider prefetching the next page,
which is especially beneficial on `/translate`.
https://html.spec.whatwg.org/multipage/links.html#link-type-next
https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ
Possible drawback: e.g. if you edit a string and it is referenced on the next page (e.g. in "Nearby keys"), then if the next page gets prefetched, that referenced string will appear unchanged.
But then, in a perfect world, to negate this, I'd say it would be good to load "Nearby keys" separately from the page SPA-style so they get loaded after the next page loads, which would also benefit performance.
Did not test this since setting up a local copy is going quite rough for now. Gecko browsers currently should be doing prefetching based on …

improvement: add `<link rel="(next|prev)"` to `<head>`

---

weblate/trans/fixtures/simple-project.json

Renamed `ckb` and `kmr` to Central Kurdish and Northern Kurdish.
Reasons for the change:
- The current names are not popular, nor standard.
- The renamed entities are not often searched for by Kurm.. or Sora..
- To match with the name of the other dialect, `sdh` (Southern Kurdish).

Rename `ckb` and `kmr`

---

weblate/templates/base.html

Although browsers may prefetch the next link just based on `rel="next"`,
they are still entitled to doubt whether it is likely that the user will
want to visit it. Let's tell them that it is indeed highly likely.
This is a follow-up to 2340bf6b25 (#7558)

improvement: add `prefetch` for `<link rel="next`

---

docs/admin/install/docker.rst
weblate/settings_docker.py

I propose to allow the following variables to be set (according to documentation) when run in docker:
* `SOCIAL_AUTH_KEYCLOAK_IMAGE`
* `SOCIAL_AUTH_KEYCLOAK_TITLE`
* `SOCIAL_AUTH_SAML_IMAGE`
* `SOCIAL_AUTH_SAML_TITLE`

Allow SOCIAL_AUTH_* _IMAGE and _TITLE customization for Keycloak and SAML

---

weblate/trans/tests/test_reports.py
weblate/trans/views/reports.py

Also rewrite with `format_html` instead of `escape`
This also makes it not output leading and trailing newlines
as I think it was an error.
Same issue still exists for `/counts`, need to do the same
Before:
After:

fix: `/credits` escaping HTML chars when outputting in `text/plain` mode

---

weblate/addons/forms.py

The original `GettextCustomizeForm.width` specified its choices in terms of gettext behavior.  In 54c519d, this specification was removed in favor of help text.  While the help text clarifies gettext's own behavior, highlighting the comparison to `xgettext` and its flags is helpful for choosing the right Weblate option.
Motivating discussion:  #7791
- [n/a] I have added tests that prove my fix is effective or that my feature works.
- [n/a] I have added documentation to describe my feature.
Feel free to close if you prefer the current text!  In that case, just consider this user feedback.  :-)

feat: explicitly link `GettextCustomizeForm.width` choices to `xgettext` flags

---

weblate/templates/snippets/list-objects-percent.html

closes #7778 
The checkmark was not shown because `0` is `False` in python so the else statement was executed.

template: show checkmark for components with 0 strings

---

.github/workflows/closing.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/labels.yml
.github/workflows/migrations.yml
.github/workflows/rundev.yml
.github/workflows/setup.yml
.github/workflows/test.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

weblate/static/loader-bootstrap.js
weblate/templates/snippets/sort-field.html

closes #7830 
https://user-images.githubusercontent.com/24358501/178294980-743cd1fb-9d5d-46ea-bb3a-656141f66b52.mov
I am not sure about the exact reason but the sort order change was happening at two places, one before submitting the form([`toggle`](https://github.com/WeblateOrg/weblate/blob/main/weblate/static/loader-bootstrap.js#L1033)) and another after the response received on the basis of [`sort_by`](https://github.com/WeblateOrg/weblate/blob/main/weblate/static/loader-bootstrap.js#L943-L953) value. Now I made it to happen only once after the response is received and it's looking fine.

template: add tooltip for current sort order

---

docs/api.rst
weblate/api/serializers.py
weblate/api/tests.py
weblate/api/urls.py
weblate/api/views.py

Ref: https://github.com/WeblateOrg/weblate/issues/6440
- Add API for listing and deleting memory entries
@nijel  Please let me know what else I can add in the documentation and for the API test. Thanks

api: add api to list and delete memory entries

---

weblate/accounts/notifications.py
weblate/templates/mail/parse_error.html

closes #2106 
- Link Filename if they exist on parsing error mail.

trans: link filenames when sending parse error mails

---

weblate/trans/models/change.py
weblate/trans/models/unit.py

The fuzzy state calculated by Weblate was not stored to the file and was kept in the database only. This was caused by lack of support for this in most of the formats, but it makes sense to write it out for formats that do support this.
Fixes #8036

Store fuzzy flag for monolingual PO files

---

weblate/checks/flags.py

Alternatively
The/a translation flag should have/is missing its/some parameter/s.

Spelling: flags, tag prefix, the

---

weblate/trans/models/component.py
weblate/trans/models/translation.py

- Avoids additional logic to commit template changes first
- Remove ordering issue when add-on is triggered on partial commits
- Make the code more straightforward as the commit implementation is no longer a generic entry point

translation: Always commit whole component

---

docs/api.rst

The parameter was lacking a trailing `s`.

Fix `conflicts` parameter in API docs

---

weblate/lang/data.py

This is intended to fix #8223 by adding `pa_PK` to the list of "underscore" codes to include in the basic language list. Like `pt_BR`, the majority of Punjabi speakers live in Pakistan, and like the situations with Chinese, Belarusian, and Norwegian, there are differences in the way the languages are written which mean `pa` and `pa_PK` cannot be readily substituted for eachother.

Addition of pa_PK to basic language exceptions

---

docs/user/search.rst

Stated that  state:TEXT can only handle searching for string states while  is:TEXT  can search for string states and search for pending translations.

Added clarification for state:TEXT and is:TEXT

---

weblate/trans/models/component.py
weblate/trans/models/translation.py

In handle_store_change we explicitly parse the change no. for the aforementioned message when the translation is not source. However, we never parse this when it is source.
This results in the aforementioned message never being sent when replacing source string via an upload.
Fixes: https://github.com/WeblateOrg/weblate/issues/8285
To resolve this by ensuring we can parse this via the create_translation method in the component which will then eventually parse it to check_sync downstream thereby ensuring the message is pushed to the exchange.

Ensure the "Replaced file by upload" fedora message is sent

---

weblate/api/tests.py
weblate/checks/placeholders.py
weblate/trans/autofixes/base.py
weblate/trans/fixtures/simple-project.json
weblate/trans/forms.py
weblate/trans/models/unit.py
weblate/trans/tests/test_models.py

Use correctly plurals for counting words or fixing.
Taken out of https://github.com/WeblateOrg/weblate/pull/8323 by @Changaco to merge it separately.

replace other incorrect uses of `unit.source_string`

---

docs/admin/customize.rst
docs/admin/install/docker.rst

Cover in the documentation how to customize settings when using Docker, *without* using the data volume.
Resolves #8358.
While I think there may be valid use cases for the data volume approach, and it is in many ways simpler, I think the alternative approach proposed here may be preferable in some scenarios.
However, no hard feelings if this change gets rejected. I can think of a few valid reasons for rejection, such as this not being a common scenario (I thought it would be, but it does not look like it is), or how bad it plays with https://github.com/WeblateOrg/docker-compose.
Regardless of whether these changes are merged or rejected, I think we can close #8358 along with this merge request.

docs: Cover customizing settings from a custom Docker image

---

docs/admin/addons.rst
docs/admin/config.rst
weblate/addons/forms.py
weblate/addons/models.py
weblate/addons/tests.py
weblate/addons/xml.py
weblate/settings_docker.py
weblate/settings_example.py

I'm using Weblate to maintain XLIFF translation files from my Business Central packages.
Compiler is using non self-closing tags format when no data is stored in a node - and as a result, huge diff are currently generated after a unit is translated from Weblate.
The purpose of this changes is to provide an optional way to handle the output formatting of XLIFF files.
It relays on the following pull request which add a flag to the XLIFF storage https://github.com/translate/translate/pull/4751

feat: add xml add-on

---

weblate/templates/snippets/query-builder.html
weblate/trans/filter.py
weblate/utils/forms.py

Follow-up to b240770f3a9. This should make it easier to translate by first translating strings with screenshots. And, for admins, find strings with no screenshots (#3821).
Did not test. Also I'm not sure if I changed the right places, and that I did not miss to change something else.

improvement: add `has:screenshot` filters to UI

---

.readthedocs.yml

Hi friends! I was looking at your documentation and noticed that the nice diagrams were broken. Example: https://docs.weblate.org/en/latest/workflows.html#quality-gateway-for-the-source-strings
Read the Docs' newer build images stopped bundling a bunch of different packages. You can imagine that it's something that when most projects don't need Graphviz, it's a lot of extra load on the CI platform to bake it into default images. More background here: https://github.com/readthedocs/readthedocs.org/issues/8800

Adds graphviz package to Read the Docs build image

---

README.rst

The sentence "You should have received a copy of ..." is not suitable for the README on the GitHub repository.
This PR removes the paragraph "You should have received a copy of the GNU General Public License ..." and adds a link to GPLv3 instead.

README: Simplify license description

---

weblate/static/style-bootstrap.css

| Before | After |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/39462442/207921027-516b3675-e3b0-4970-8ba9-f2ab1d559049.png) | ![image](https://user-images.githubusercontent.com/39462442/207920531-9be98579-6e02-4ad2-84c4-ec348d08252c.png) |
I also tested it with a narrower screen - it doesn't overflow it (although touches the edge, as it is now on wide screens)

improvement: don't stretch screenshot modal if image is narrow

---

docs/user/checks.rst
requirements.txt
weblate/checks/markup.py
weblate/trans/autofixes/html.py
weblate/trans/tests/test_autofix.py
weblate/utils/html.py
weblate/utils/requirements.py
weblate/utils/tests/test_html.py

Bleach is getting deprecated and nh3 is way faster.
This is not yet ready, needs https://github.com/messense/nh3/issues/8
Bleach depreciation notice: https://github.com/mozilla/bleach/issues/698

deps: Replace bleach by nh3

---

docs/changes.rst
weblate/utils/db.py
weblate/utils/tests/test_db.py

Use iexact and icontains for strings that pg_trgm doesn't handle well. It looks at alphanumeric characters and in case there are none, all strings match the index causing huge penalty when doing recheck at the next step.
Fixes #8668

db: Fallback to Django operator for some strings

---

docs/api.rst

Update docs adding `tmx` as a valid file format when using `GET /api/translations/(string: project)/(string: component)/(string: language)/file/` endpoint.
It's an fix to API documentation that I checked works correctly in version 4.15.2

Add tmx as an accepted file format to download a translation file.

---

weblate/vcs/git.py
weblate/vcs/tests/test_vcs.py

https://github.com/WeblateOrg/weblate/commit/38008c51e6a12630348ed36f34d0370e1fb10c9c changed the request being send to gitea for creating a project
fork from sensing an empty json body with the correct Content-Type
header to sending just an empty body and no Content-Type header.
Gitea doesn't accept these requests and returns an "Empty Content-Type"
error instead.
Fix that by adding back the json body via requests `json` parameter
which also adds the correct content type header again.

Fix creating repository forks on gitea

---

weblate/addons/json.py

Fix json customize addon not work when using i18nextv4 format
- [x ] Lint and unit tests pass locally with my changes.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] I have added documentation to describe my feature.
- [x ] I have squashed my commits into logic units.
- [ x] I have described the changes in the commit messages.

fix: add json customize addon's compat

---

weblate/machinery/base.py

https://github.com/WeblateOrg/weblate/commit/e3595b31c2600a92102b1f8a23e9e5ae14c166db This commit removed a parameter for the fuction `download_translations`, but did not remove the parameter of the test case, which will cause the failure when adding a new api.
Fix the problem that failed when adding a new api.

machinery: Remove a parameter that are no longer used

---

weblate/templates/accounts/redirect.html

With this change, the POST login request should be set correctly as a form parameter instead of query url
n/a

Fix next param still not working when single social auth is enabled

---

weblate/trans/bulk.py
weblate/trans/models/unit.py
weblate/trans/views/search.py

The search() result can contain nullable join in several lookups (for example has:label) and in that case it is not possible to do select_for_update().
Avoids that by doing the search first and then locking only based on primary key.
Fixes #8899

search: Avoid using select_for_update on possibly nullable joins

---

weblate/checks/chars.py
weblate/checks/tests/test_chars_checks.py

There's a rule for French that ensures there's whitespace before certain punctuation characters: https://docs.weblate.org/en/latest/user/checks.html#punctuation-spacing
However there are some strings where you have doubled characters such as `!!`, `?!`, `::`. The lack of space between them was flagged by this check, which I think is wrong.
Some examples of what would be flagged before this PR:
- `%s1  ::  %s2`
- `État collecteur : dommages lourds !!`
- `BT, t'as abandonné l'Arche ! Pourquoi ?!`
I didn't run tests/lint, but I hope the change is simple enough for that to be fine.

Fix PunctuationSpacingCheck for repeated punctation

---

docs/admin/config.rst
weblate/vcs/git.py
weblate/vcs/tests/test_vcs.py

These changes allow for users to use protocols other than `https` when connecting to VCS. This change was made because Weblate originally forced `https` connections, which made it impossible for users to connect to VCS using `http`. This pull request also updates the Configuration page of the documentation to reflect these changes. Unit tests have also been added to test `http` connections.
Issue that these changes resolve: #9179

Added 'protocol' setting to Git credentials

---

docs/changes.rst
weblate/checks/format.py
weblate/lang/models.py
weblate/lang/tests.py
weblate/machinery/base.py
weblate/static/editor/full.js

This covers some situations that were missed in https://github.com/WeblateOrg/weblate/pull/8323 by @Changaco:
- blank translations when interpolation is supported by the check but not possible
- improved mapping when translating from language with more complex plural rules
- fixed plurals merging in UI when more plurals are translated with a same string
- added tests for `PluralMapper`

Improved plurals handling in machine translation

---

weblate/accounts/forms.py
weblate/accounts/password_validation.py
weblate/addons/gettext.py
weblate/api/routers.py
weblate/api/views.py
weblate/checks/icu.py
weblate/checks/markup.py
weblate/checks/source.py
weblate/lang/models.py
weblate/memory/views.py
weblate/metrics/wrapper.py
weblate/settings_docker.py
weblate/trans/discovery.py
weblate/trans/forms.py
weblate/trans/templatetags/translations.py
weblate/trans/views/changes.py
weblate/utils/backup.py
weblate/utils/licenses.py
weblate/utils/stats.py
weblate/vcs/git.py

Utilize comprehensions in more situations. This should slightly improve the performance and makes the code easier to read in many cases.
Discovered by ruff PERF401, needed for https://github.com/WeblateOrg/weblate/pull/9500

chore: Use more comprehensions

---

docs/admin/install/docker.rst
docs/admin/translating.rst
docs/admin/upgrade.rst
weblate/auth/admin.py
weblate/auth/tests/test_commands.py
weblate/glossary/views.py
weblate/machinery/base.py
weblate/metrics/models.py
weblate/trans/management/commands/cleanuptrans.py
weblate/trans/models/unit.py
weblate/trans/tests/data/XWikiFullPageSource.xml
weblate/vcs/git.py

Fix several user-facing and non-user-facing typos.
Found via `codespell -q 3 -S ./weblate/static/vendor -L childs`
n/a

Fix various typos

---

docs/admin/install.rst

Edited mistake in required python version. it's changed from 3.6 to 3.9 as addressed in issue #9594

Update install.rst #9594

---

docs/admin/config.rst
docs/admin/install.rst
docs/changes/v4.rst
weblate/examples/apache-path.conf
weblate/examples/apache.conf
weblate/examples/apache.gunicorn.conf
weblate/examples/weblate.nginx.conf

* document content of CACHE_DIR
* adjust related documentation to cover change in 4.16, fixes #9601

CACHE_DIR documentation

---

docs/changes.rst
weblate/glossary/tests.py
weblate/trans/models/translation.py

- avoids expensive sync_terminology call on adding every glossary entry
- makes added entries credited to the adding user
Fixes #9661

glossary: add terminology entries directly

---

weblate/trans/migrations/0001_squashed_0074_fix_broken_browser_alert.py
weblate/trans/mixins.py
weblate/trans/models/component.py
weblate/trans/models/project.py

The logic is same and needs to account future categories.

models: reuse path url logic for filesystem

---

weblate/templates/addons/addon_detail.html
weblate/templates/addons/addon_list.html
weblate/templates/browse.html
weblate/templates/component-progress.html
weblate/templates/component-settings.html
weblate/templates/component.html
weblate/templates/contributor-agreement.html
weblate/templates/guide.html
weblate/templates/matrix.html
weblate/templates/new-language.html
weblate/templates/project.html
weblate/templates/replace.html
weblate/templates/screenshots/screenshot_detail.html
weblate/templates/screenshots/screenshot_list.html
weblate/templates/snippets/component-breadcrumb.html
weblate/templates/snippets/translation-breadcrumb.html
weblate/templates/translate.html
weblate/templates/translation.html
weblate/templates/zen.html
weblate/trans/views/basic.py
weblate/trans/views/edit.py
weblate/utils/views.py

This will make projectlanguge and category work consistently at all levels.
Issue #263

templates: use shared breadcrumb renderer

---

weblate/trans/mixins.py
weblate/trans/models/component.py
weblate/trans/models/translation.py
weblate/trans/models/unit.py
weblate/trans/tests/test_manage.py
weblate/utils/stats.py

These can be same so reduce code duplication and use existing url path.

mixins: reuse url path for full_slug

---

weblate/templates/zen-units.html

Implement highlighting search string in context when in zen mode.
Fixes #9044
I did not write specific automated tests, only a visual confirmation of the cosmetic changes.
Before change
After change

Fixed zen mode template to highlight search string in context

---

weblate/templates/svg/multi-language-badge-horizontal.svg
weblate/templates/svg/multi-language-badge.svg
weblate/templates/svg/style.svg

I have noticed some problems with the bar chart widgets generated by Weblate:
- The font "Source Sans Pro" was replaced by "Source Sans 3" and moved to a subdirectory. However, the widgets still try to use the old font from the old path.
- My browser (Firefox) did not recognize the specified fallback ``Sans``. As a result, the serif font "Times New Roman" was used. This seems to be unintentional.
In this PR, I updated the SVG templates. The font CSS should now be imported from the correct path. And I changed the fallback to ``sans-serif`` which is also used in other places.

Font fixes for bar chart widgets

---

docs/admin/install/docker.rst
weblate/settings_docker.py

Resolves #9854
Support [IP_PROXY_OFFSET](https://docs.weblate.org/en/latest/admin/config.html#std-setting-IP_PROXY_OFFSET) configuration in the docker image.

docker: add WEBLATE_IP_PROXY_OFFSET

---

weblate/trans/models/category.py
weblate/trans/models/project.py
weblate/utils/stats.py

This affects both CategoryLanguage and ProjectLanguage - the parent objects not cache list of source languages to make the individual decisions cheap instead of doing a database query for each language.
Fixes WEBLATE-4F5

stats: remove additional queries needed to figure out source language

---

weblate/metrics/models.py

Although all calls have 0 there, let's still make the argument used to prevent confusing behavior in the future. Follow-up from https://github.com/WeblateOrg/weblate/pull/9921.
- ~~[ ] I have added tests that prove my fix is effective or that my feature works.~~
- ~~[ ] I have added documentation to describe my feature.~~

MetrixQuerySet: fix passing secondary argument to filter method call

---

weblate/static/style-bootstrap.css
weblate/templates/manage/repos.html

When there are a lot of linked repositories it can become difficult to get a overview of the status of the real repos.
Adds a basic checkbox that toggles the display of linked repositories in pure CSS.
Input needs to be on same level as components to make the CSS selector work. Because there is no way in CSS to select a parent element.

ui: add option to hide linked repositories in admin repo status page

---

weblate/glossary/models.py
weblate/glossary/tests.py
weblate/trans/models/unit.py
weblate/trans/templatetags/translations.py
weblate/trans/tests/test_templatetags.py

We already have positions of the glossary terms inside a string, so reuse these instead of doing second matching.

glossary: Reuse match logic while rendering

---

weblate/machinery/google.py

Currently only the "nb_NO" (locale with country code) is mapped to "no", but no mapping exists for just the locale "nb". This "nb" locale doesn't exist in Weblate by default, but can be created through the Django admin interface via the "Languages" section. Because of this, the Google Translate automatic translation provider currently doesn't recognize the "nb" locale. This change will add a mapping for the "nb" locale as well.

Add "nb" locale mapping to Google Translate

---

docs/changes.rst
weblate/static/style-bootstrap.css
weblate/templates/snippets/list-objects.html

Show approved percentage in the object listing to have a number corresponding to the left most bar when reviews are enabled.
Only shows the column if reviews are enabled in the project.
A simpler implementation compared to MR #9864.
Resolves WeblateOrg#9855

ui: Add approved percentage to the object listing (v2)

---

weblate/accounts/models.py
weblate/accounts/utils.py
weblate/accounts/views.py

This leaks admin IP address to the user.
Fixes #9983

auditlog: skip notification for admin triggered account removal

---

docs/admin/install/docker.rst
docs/changes.rst
docs/snippets/vcs-credentials.rst
weblate/utils/environment.py
weblate/utils/tests/test_environment.py

Resolves #8132
The env variable is a "Python dict as a string" because it most closely matches the [docs](https://docs.weblate.org/en/latest/admin/config.html#gitlab-credentials). Could also be JSON or YAML instead.

settings: add support for multiple vcs api host credentials from env var

---

docs/changes.rst
weblate/checks/base.py
weblate/checks/tests/test_chars_checks.py
weblate/checks/tests/test_checks.py
weblate/lang/models.py

This commit modifies the `Check.check_target_unit()` method to improve how source and target strings are paired for comparison, which should reduce both false positives and false negatives. It fixes <https://github.com/liberapay/salon/issues/581>.

Improve accuracy of checks on plural messages

---

docs/api.rst

The doc says "Returns statistics for a project." when it should be "Returns categories for a project."

Docs: Fix typo in GET categories

---

weblate/api/tests.py
weblate/trans/models/__init__.py
weblate/trans/models/component.py
weblate/trans/models/suggestion.py
weblate/trans/models/translation.py
weblate/trans/tasks.py
weblate/trans/tests/test_views.py
weblate/trans/views/settings.py
weblate/utils/stats.py
weblate/utils/tasks.py

Always calculate up-to-date stats for a translation on a change, parent stats are updated automatically in the background.
There is no explicit cache invalidation anymore to make sure some stats are always present (and thus nearly no request on higher level will force calculating them).
This might cause that parent stats are showing outdated number for very short time, but this should cause no harm.
Fixes #9662

stats: keep stats up-to-date instead of invalidating

---

weblate/templates/snippets/list-objects.html

When you are inside a category and want to create a new component, you can either click "Manage > Add new translation component", or "+" (Add new translation component link)
This + link is on the left of the table's headers of the component list
There is a typo "categry" vs "category" which leads to an empty value on the second screen of the creation form (ie. the category is not pre-selected)

category: preserve the category id when creating a new component

---

docs/changes.rst
weblate/lang/models.py
weblate/lang/tests.py
weblate/static/style-bootstrap.css

Instead of the tooltip, the text is rendered in the page now:
Fixes #9675

translate: Show plural form examples more prominently

---

weblate/utils/lock.py

Include the lock's name in the `WeblateLockTimeoutError` message to help with pinpointing which lock is affected.
This is only for redis locks.

utils: provide lock name in timeout error message for better debugging

---

weblate/trans/models/change.py
weblate/utils/stats.py

Improve logic to store the last change object locally as well so that update_stats() does not have to fetch it again. This needs to be done immediately to be available right after creating the change (contrary to what update_cache_last_change() does – it updates the cache for other processes).

stats: avoid fetching last change from database when doing it

---

weblate/templates/translate.html

Fixes #10225
Tested this locally and the tools button now aligns correctly with the other buttons.

fix: Align the Tools button

---

weblate/trans/models/unit.py
weblate/trans/util.py
weblate/trans/views/reports.py

This makes both location use consistent implementation.
See #10278

utils: Factor out word counting

---

weblate/trans/views/basic.py
weblate/utils/management/commands/ensure_stats.py
weblate/utils/render.py
weblate/utils/stats.py
weblate/utils/tests/test_commands.py

Since https://github.com/WeblateOrg/weblate/pull/10269 there should be no performance difference in prefetch and getting individual values as both are calculated same. This makes the ensure_* helpers useless as lazy fetching produces same result with less code.

stats: drop ensure_* helpers

---

weblate/trans/models/change.py
weblate/trans/models/translation.py
weblate/utils/stats.py

It is actually the most expensive one to get, so it makes sense to cache negative result as well.

stats: cache none last change result as well

---

weblate/middleware.py
weblate/utils/views.py

This avoids additional database queries when we already know that the path can not be resolved. This also provides feedback to the middleware, that the path is too long (and it can redirect to parent when trying to fix this).

utils: end path filtering once we are out of supported types

---

docs/admin/machine.rst
weblate/machinery/base.py
weblate/machinery/deepl.py
weblate/machinery/forms.py

I added an option to the DeepL API integration to specify the formality.
Link to DeepL API: https://www.deepl.com/docs-api/translate-text
This PR adds a dropdown-setting to the configuration screen of the DeepL integration, with 3 options:
Default (which is the default and sets `formality` to `default`)
Informal (this sets `formality` to `prefer_less`)
Formal (this sets `formality` to `prefer_more`)
This PR also adjusts the `mtid` field of the `MachineTranslation` to make sure the caching works correct (informal/formal/default texts of DeepL suggestions are cached separately).
The `@FORMAL` and `@INFORMAL` language id endings have precedence over this new setting.
I am not very familiar with Python or Django, so I didn't know what the best way is to translate the config options and …

Add formality parameter to DeepL API integration

---

weblate/static/style-bootstrap.css
weblate/static/style-dark.css
weblate/templates/snippets/progress.html
weblate/templates/translation.html
weblate/trans/models/translation.py
weblate/trans/templatetags/translations.py

Make progress bars use neutral colors (primary and neutral instead of info and danger). Updated also legend and unit states colors. Introduced new class for unit states, `.unit-state-bad` to differ units with problems from `.unit-state-todo`.
For me personally currently high amount of "danger" color for in progress translations causes an "UI anxiety".
- ~~[ ] I have added tests that prove my fix is effective or that my feature works.~~
- ~~[ ] I have added documentation to describe my feature.~~
<details>
<summary>Light before</summary>
</details>
<details>
<summary>Light after</summary>
</details>
<details>
<summary>Dark before</summary>
</details>
<details>
<summary>Dark after</summary>
</details>
Legend in translation view:
<details>
<summary>Light before</summary>
</details>
<details> …

Neutral colors for progress bars and translation unit states

---

weblate/static/loader-bootstrap.js
weblate/trans/specialchars.py
weblate/trans/templatetags/translations.py
weblate/trans/tests/test_specialchars.py

Related to #3006
When a languge has hyphens then show a button in the visual keyboard to insert a [soft hyphen](https://en.wikipedia.org/wiki/Soft_hyphen). 
Using `WHITESPACE_REGEX` to get a red highlight in the editor where there are soft hyphens.

specialchars: add soft hyphen (U+00AD) button

---

docs/admin/machine.rst
docs/changes.rst
docs/user/glossary.rst
weblate/checks/tests/test_checks.py
weblate/glossary/models.py
weblate/glossary/tests.py
weblate/machinery/openai.py
weblate/trans/models/project.py

machinery: Include glossary in OpenAI translations

---

docs/admin/machine.rst
docs/changes.rst
docs/user/glossary.rst
weblate/machinery/base.py
weblate/machinery/deepl.py
weblate/machinery/tests.py

- Add generic mixin to handle service side glossaries
- Implement DeepL integration
Fixes #7086
Fixes #10468
Built on top of #10516

machinery: Add DeepL support for glossaries

---

weblate/templates/snippets/list-objects.html
weblate/trans/templatetags/translations.py

Count read-only strings to the approved percentage number shown in object listings.
The progress bars display both approved and read-only strings as "Approved".
Also in the string status page both read-only strings and approved strings have the same colour.
Since #9936 the percentage of approved strings is shown as a number in the object listing, but without considering read-only strings.
This leads to a visual mis-match between the progress bars and the number:

ui: include readonly in approved percentage listing to match with progress bars

---

docs/user/checks.rst
weblate/checks/format.py
weblate/checks/models.py
weblate/checks/tests/test_format_checks.py
weblate/settings_docker.py
weblate/settings_example.py

perl-format and perl-brace-format are distinct
https://www.gnu.org/software/gettext/manual/html_node/perl_002dformat.html
This patch adds support for perl-brace-format:
"There are {number} apples"

checks: Support for Perl brace format (#10626)

---

weblate/trans/specialchars.py

A button with the text "SHY" might not be that clear for non-technical people. Replace it with something that looks similar to the ISO symbol for the soft hypen.
Icon from [Wikipedia](https://en.wikipedia.org/wiki/Soft_hyphen) and [this proposal to Unicode](https://www.unicode.org/L2/L2017/17072-symbols-9995.pdf#page=5). U+2433 never got included in the [Control Pictures Unicode block](https://en.wikipedia.org/wiki/Control_Pictures), so no font has a representation for this.
Before:
After:

specialchars: use iso symbol as soft hyphen button for better clarity

---

docs/changes.rst
weblate/trans/models/change.py
weblate/trans/models/translation.py
weblate/utils/stats.py

It used to track only changes by users inside Weblate, now it reflects all changes to the translation - including repository updates, comments or commits.
Fixes #6548
See #10512

stats: last_changed now reflects changes outside Weblate as well

---

weblate/trans/models/component.py
weblate/trans/models/translation.py
weblate/trans/tests/test_files.py

With early trigger, the translation files are not yet parsed and the update might be skipped. Emiting signals later avoids cleanup add-on to store translation revision before parsing.
Fixes #10763

translation: delay emitting post commit signal

---

weblate/utils/db.py
weblate/utils/tests/test_db.py

Generate SQL directly instead of doing intermediate objects for fallback. These would not get proper table aliases causing wrong SQL being generated (ProgrammingError).
Fixes WEBLATE-65M
Fixes #10620

utils: Fixed generating query with aliased tables

---

weblate/addons/base.py
weblate/addons/cdn.py
weblate/addons/cleanup.py
weblate/addons/discovery.py
weblate/addons/models.py
weblate/addons/scripts.py
weblate/addons/tests.py

This is a regression introduced in
e3ff25a8ab62c590ac983ad04aac9f1fcb0686ec - it removed child condition from the repository scoped add-ons causing discovery add-on being triggered on all shared repos instead of only main one.
See #10892

add-ons: trigger discovery on the main repo only

---

weblate/accounts/notifications.py
weblate/api/tests.py
weblate/lang/management/commands/move_language.py
weblate/memory/tests.py
weblate/trans/backups.py
weblate/trans/tests/test_backups.py
weblate/trans/tests/test_changes.py
weblate/trans/tests/test_component.py
weblate/trans/tests/test_models.py
weblate/utils/tests/test_db.py

The first() might return None when object is not present what is not well handled in some situations. The code should crash on getting instead.

chore: avoid using QuerySet.first() when None is not handled

---

weblate/api/serializers.py
weblate/trans/forms.py
weblate/trans/models/change.py
weblate/trans/models/translation.py
weblate/trans/models/unit.py
weblate/utils/state.py

- introduce StringState enum to track string state
- reuse it's verbose labels for choices instead of doing it again with a different content

unit: use enum for string states

---

weblate/trans/backups.py
weblate/trans/models/project.py
weblate/trans/tasks.py
weblate/trans/tests/test_backups.py
weblate/trans/views/settings.py

These can be huge and would block wsgi for long. Instead, we copy the file temporarily to the static storage and redirect to it. This way the download is handled directly by the web server, which can handle it more effectively than wsgi and can also support resuming of interrupted download. As a side effect, it can be donwloaded via command line tools as the randomly generated temporary URL doesn't require authentication.

backups: use static files to download project backup

---

docs/api.rst
docs/changes.rst
weblate/api/serializers.py
weblate/api/tests.py

api: expose linked component

---

weblate/lang/data.py
weblate/lang/tests.py
weblate/trans/tests/test_newlang.py

A regression was introduced a while back when a couple of languages were split into their respective couple of variants in [language-data](https://github.com/WeblateOrg/language-data/commits/main/weblate_language_data/languages.py?since=2023-04-18&until=2023-04-18) and, thereby, here got filtered out of the default list of basic languages altogether since they no longer present themselves in their base form.
Instead of adding them to `UNDERSCORE_EXCEPTIONS` to resurrect their pre-split position, this PR tries to adopt a more future-proof approach to the default list of basic languages to include the default variant of languages without a base form (when an alias for which is present) such that they would not be filtered out of the default list of basic languages altogether just because, …

basic languages: factor in the default variant of languages without a base form

---

weblate/accounts/models.py

This fix prevents bot users to commit using the email based on their username especially when `PRIVATE_COMMIT_EMAIL_OPT_IN = False`
Because bot users have a colon in their username, this results in invalid emails and 500 errors when committing and sending notifications.

Bots should avoid using site commit email

---

docs/api.rst

The `page_size` REST parameter seems to be undocumented. This change add documentation based on what I read in the code.

api.rst: document page_size parameter

---

weblate/screenshots/models.py

Remove Unused Screenshot alerts on deletion and string reassignment
Update the screenshots alerts in the component class on string reassignment and on screenshot deletion, so it removes instantly after these actions.
Fixes: #11141 
- [ x ] Lint and unit tests pass locally with my changes.
- [ x ] I have squashed my commits into logic units.
- [ x ] I have described the changes in the commit messages.

screenshots: fix screenshot alerts removal

---

weblate/templates/snippets/list-objects-number.html
weblate/templates/snippets/list-objects.html

~~Added an additional list object component to `list-objects.html` which gets displayed when the project view is open.~~
Updated `list-objects.html` to add a search URL to every list objects number entry. `list-objects-number.html` has also been modified to ensure that the number can be clicked if the search URL is defined. This allows the user to click on all numbers within the table. This also includes comments as described in https://github.com/WeblateOrg/weblate/issues/9089.
Resolves https://github.com/WeblateOrg/weblate/issues/9089.
In the repository I could not find any examples of frontend-related tests for specific UI elements. Since this pull request only includes frontend changes, I did not add any tests for it. Also since the proposed change is a very minor UX update which was …

Add clickable list object numbers using search URLs

---

weblate/checks/base.py
weblate/checks/chars.py
weblate/checks/models.py
weblate/checks/tests/test_chars_checks.py
weblate/settings_docker.py
weblate/settings_example.py

The updated code now allows for the swapping of "?!/!?" while translating and checks for the presence of interrobangs in both the source and translation. Tests have been implemented to validate the changes made to the code.
"EndQuestionCheck" and "EndExclamationCheck" do not produce warnings if an interrobang (?!/!?) is present. I added "EndInterrobangCheck" to verify if there is an interrobang in the original text or the translation (through the check_interrobang function) and generate warnings in case of mismatch. This function also permits the swapping of (?!/!?) without triggering any warnings. Tests have been implemented to validate the modifications made to the code.
Fixes: #10296

Fixed #10296: Tolerated interrobang swapping.

---

docs/changes.rst
weblate/templates/last-changes-content.html
weblate/trans/models/unit.py

This stores full unit info and makes changes tracking complete (including state).
See #11446

unit: use generate_change for source string change

---

docs/user/files.rst
weblate/trans/forms.py

- I updated the documentation with which permissions are required for the individual file upload methods.
- I also added documentation for the `approve` method, which was previously missing. Please confirm that its accurate and actually what this method does as I just assumed that this is what it does, based on what the `suggestion` method does.
I did not build the documentation locally, or tested that the references/links are correct. I'd appreciate if you could do that on your side.

Update documentation on file upload permissions

---

weblate/vcs/git.py
weblate/vcs/tests/test_vcs.py

This will automatically get the username from the push URL when using Gerrit as VCS
This solves issue #10596

Set the value of gitreview.username from the gerrit push URL

---

weblate/accounts/data.py
weblate/accounts/tests/test_notifications.py
weblate/accounts/tests/test_views.py
weblate/api/tests.py

This should encourage users to complete the translation they contributed to.
It applies to new users only.
Fixes #10533

feat(notification): turn on digest notification on new strings by default

---

.github/workflows/codeql-analysis.yml
.github/workflows/docs.yml
.github/workflows/licenses-update.yml
.github/workflows/migrations.yml
.github/workflows/mypy.yml
.github/workflows/pre-commit.yml
.github/workflows/pylint.yml
.github/workflows/schema-update.yml
.github/workflows/setup.yml
.github/workflows/test.yml
ci/pip-install
ci/run-migrate
pyproject.toml

- use uv instead of pip for better peformance
- drop cache as uv cache is way bigger than pip

ci: use uv to install packages

---

dev-docker/docker-compose.yml
docs/contributing/start.rst

Exposing the port of the PostgreSQL container would help a lot in the development especially when dealing with the records inside the database. This database is exposed to port 5433 only when using the development docker-compose of weblate.

Expose PostgreSQL when using the development Docker setup

---

weblate/trans/models/component.py

Set the `force` option to `True` when calling `create_translations` in the `do_file_scan` handler, as already done by the `do_reset` one.
Currently, 'Reset' will (after resetting the weblate repository) enforce a complete rescan of all source translation files (e.g. all PO files).
The 'Rescan' option however, does not. As a consequence, translations sources are only re-scanned in case the source files are actually detected as changed since last update.
This behavior does not seem consistent with the description of this command (`Loads translations from the files into Weblate. Use when Weblate missed some of the strings after updating the repository`).
And it does not indeed actually update translations when e.g. the regular 'Update' command failed to finish properly (due to reaching the …

Fix 'Rescan' not enforcing rescan of source translation files.

---

docs/changes.rst
weblate/accounts/forms.py

This makes it possible to generate new passwords instead of filling in existing one.
Thanks to @spaze for hint on this.

feat(accounts): add autocomplete hints for password field

---

docs/changes.rst
weblate/glossary/models.py

Doing repeated single character regular expressions is slow, better to match all word boundaries at once early.

fix(glossary): fetch word boundary positions just once

---

weblate/formats/base.py
weblate/formats/convert.py
weblate/formats/multi.py
weblate/formats/tests/test_formats.py
weblate/formats/ttkit.py
weblate/formats/txt.py
weblate/trans/models/translation.py

This breaks in multivalue storage and is using internals where not necessary.
Fixes WEBLATE-CH

fix(formats): avoid using internal unit in add_unit()

---

weblate/accounts/templatetags/authnames.py
weblate/static/style-bootstrap.css
weblate/templates/accounts/profile.html

feat(accounts): make identities listing responsive

---

docs/changes.rst
weblate/machinery/base.py
weblate/machinery/tests.py

The same text and different replacements would use first replacements only because the text is replaced in the translations dictionary.
Fixes #11179

fix(machinery): avoid mixing translations with different replacements

---

docs/devel/integration.rst
weblate/lang/models.py
weblate/static/loader-bootstrap.js
weblate/templates/translation.html
weblate/trans/forms.py
weblate/trans/models/translation.py
weblate/trans/tests/test_edit.py
weblate/trans/views/basic.py

This changes the way how the adding of new translation string done in the web UI.
This adds an option to add pluralized translation string.
This solves issue #7663.
Example image:

Implement pluralized add new translation string on web UI

---

docs/admin/addons.rst
weblate/addons/forms.py
weblate/addons/properties.py
weblate/addons/tests.py

This adds a configuration to toggle case-sensitive key sorting to the `weblate.properties.sort` add-on.
This solves issue #11714.
Example images:

Add case-sensitive key sorting setting in Properties add-on

---

weblate/addons/base.py
weblate/addons/discovery.py
weblate/api/serializers.py
weblate/templates/addons/addon_head.html
weblate/templates/addons/addon_list.html

It currently shows preview based on the component, so it crashes without it.
While technically there is no reason not to allow it, it is unlikely that a single discovery add-on configuration would work on different repositories.
Fixes #11939
Fixes WEBLATE-QC

fix(add-ons): disable discovery add-on on site and project wide

---

CONTRIBUTING.md

This would have helped me a lot, so hopefully it helps others.

docs: add link to dev-docker contributing docs

---

weblate/trans/forms.py
weblate/trans/tests/test_changes.py

This fixes the issue regarding the pagination buttons in Changes. The pagination buttons leads to 404 page when a date range filter is added.
This solves issue #11954.

Fix the Changes pagination issue due the unformated period values

---

docs/admin/machine.rst
docs/changes.rst
weblate/machinery/forms.py
weblate/machinery/openai.py
weblate/machinery/tests.py

Allows usage of local LLMs or other providers
Adds a new field when setting up the OpenAI integration to allow the user to add a custom base_url

feat(machinery): allow base_url of OpenAI to be customized

---

weblate/static/loader-bootstrap.js
weblate/trans/views/changes.py

When using the date range search filter on the Changes page, the dates just go back to the current date instead of setting the initial date range to the dates that were submitted. To solve this, the form must be able to supply the submitted date range values and be set as initial start and end dates in the form.

Fix the initial values of period in ChangeForm when there is a user input

---

weblate/formats/tests/test_formats.py
weblate/formats/ttkit.py

The go-i18n-json v1 format uses an array as top level element (unlike all other JSON formats).
I have manually checked, that the added `parse_file` line in the tests would have caught this.
Discovered while working on #11133 / #11937.

fix(formats): new_translation = "[]\n" for go-i18n-json

---

weblate/templates/translation.html
weblate/trans/views/basic.py

The plural form currently is displayed if  `plural.number > 1` and forgot to check if the format supports plurals. This will add another condition to see if the format set in the component supports plurals.
This solves issue #12044.

Add supports plural condition for the plural form

---

docs/changes.rst
weblate/formats/base.py
weblate/formats/multi.py
weblate/formats/tests/test_formats.py
weblate/formats/tests/test_multi.py
weblate/formats/ttkit.py
weblate/trans/tests/data/fr-multi-mono.csv

* This tests for Translation.update_units does.
* Adds basic pathlib support to translation formats.

tests(formats): test monolingual unit handling in Weblate

---

docs/user/translating.rst
weblate/static/editor/browse.js
weblate/templates/browse.html

Adds 2 keyboard shortcuts (left and right arrows) for navigating back and forth while browsing translation strings of a project.

Fix #9979: Add left and right arrows for browsing project strings

---

weblate/trans/autotranslate.py
weblate/trans/exceptions.py
weblate/trans/models/suggestion.py
weblate/trans/models/translation.py
weblate/trans/tests/test_models.py
weblate/trans/views/edit.py

Raise a specific exception when the submitted suggestion is the same as the current translation
Any code calling Suggestion.objects.add is responsible of handling that error
fixes #7705

7705 suggestion already exists bug

---

weblate/utils/errors.py

To avoid spurious missed check-in issues with Sentry Crons for Celery Beat.
Since the introduction of Celery Beat monitoring with Sentry Cron in https://github.com/WeblateOrg/weblate/commit/1d1a92ba456646f99143ccc2a1c1074a2d6e0e9d we are getting a lot of spurious missed check-in alerts similar to these here: https://github.com/getsentry/sentry-python/issues/3179
Using [`keep_alive=True`](https://docs.sentry.io/platforms/python/configuration/options/#keep-alive) has fixed it for us.
Using `SENTRY_EXTRA_ARGS` for this configuration is not possible with the docker container.

chore: add sentry connection keep-alive

---

weblate/formats/tests/test_formats.py
weblate/formats/tests/test_multi.py
weblate/formats/ttkit.py

Do not copy the notes (comments) from the template/source when adding a translation for a key (in monolingual formats).
This fixes #11133. Copying the notes is problematic because the are not synced when they are updated. As a result, they can get out of date.
The implicit assumption behind this change is that most users only care about comments in source files (but not in target files).

fix(formats): do not copy template notes for new translations

---

docs/changes.rst
weblate/checks/format.py
weblate/checks/tests/test_format_checks.py

feat(checks): detect extra curly braces in Python brace format

---

weblate/checks/base.py
weblate/checks/format.py
weblate/checks/tests/test_format_checks.py

Since f2f333fd275 the errors are not longer shown with a single messsage, but the message is shown for each missing/extra format.
This also introduces specific error message for single braces in python brace format.

fix(checks): improve format string error reporting

---

docs/changes.rst
weblate/screenshots/forms.py
weblate/static/js/screenshots/clipboard-paste.js
weblate/templates/screenshots/screenshot_detail.html
weblate/templates/screenshots/screenshot_list.html
weblate/templates/screenshots/snippets/paste-button.html
weblate/templates/translate.html

**Added:** Paste screenshot from clipboard.
The user clicks paste. Then the clipboard is read if the permesion is given and the context is secure (as required by the clipboard API). Then the image is pasted into the select file input. Otherwise if no image is available we only inform the  user about that.
Closes: #6710

Feat: Add clipboard paste functionality for screenshots

---

weblate/addons/base.py
weblate/addons/cdn.py
weblate/addons/cleanup.py
weblate/addons/discovery.py
weblate/addons/models.py
weblate/addons/scripts.py
weblate/addons/tests.py
weblate/trans/models/component.py

These should not be executed on linked components, but only on the main    one. This is generic solution to the problem replacing previous specific    solution to single event and add-on.
Fixes #12232
Fixes #10892

fix(add-ons): execute repository scoped add-ons only once

---

weblate/templates/translation.html

Allow multiple downloads in custom download form.
There was an onSubmit event listener blocking the resumbit of the downlaod form. Which can be removed by adding the .double-submission to the desired form.
Closes: #12236

Allow for multiple downloads in Customize download

---

docs/changes.rst
weblate/machinery/forms.py
weblate/utils/forms.py

The previous solution applied both Django and Weblate validation to these fields.
Fixes #12291

fix(machinery): overwrite Django built-in URL field validation

---

weblate/middleware.py

* Split up the code to smaller blocks
* Better detect authentication method URLs (fixes #12302, fixes #12321)
* Avoid using blank hostnames in CSP

refactor Content-Security-Policy headers building

---

weblate/formats/base.py
weblate/formats/tests/test_convert.py
weblate/trans/models/translation.py

Use context manager to write out content, but keep it around for the filename and delete that later.
Discovered by ruff: https://docs.astral.sh/ruff/rules/open-file-with-context-handler/

chore: use tempfile as context manager even when not deleting it

---

weblate/lang/data.py

I've added hi_Latn to the list of underscore code exceptions, which based on #8229 should add it to the basic languages list and make it available for selection by translators, without involving the maintainers.

Add hi_Latn to basic language exceptions

---

weblate/trans/models/unit.py

It was missed when editing source.
Fixes #12550

fix(unit): always generate change for explanation edit

---

weblate/templates/snippets/query-builder.html
weblate/trans/forms.py

- use relative dates instead of hardcoding one month in the text
- improve label for some examples
See https://hosted.weblate.org/translate/weblate/application/en/?checksum=2ff38e4324d4bf34#comments
Fixes string introduced in https://github.com/WeblateOrg/weblate/pull/12414

fix: improve description of filter example

---

.github/workflows/test.yml
docs/admin/install.rst
docs/changes.rst
pyproject.toml
scripts/show-extras
weblate/api/tests.py
weblate/machinery/base.py
weblate/trans/models/translation.py
weblate/utils/tests/test_search.py

* Limit list of supported versions with upcoming Python 3.13 (see https://github.com/WeblateOrg/weblate/pull/12557)
* Python 3.11 introduced several type annotation features which will make them easier

Drop support for Python 3.10

---

weblate/static/loader-bootstrap.js

This will adjust the initial values of the daterangepicker to blank.
This solves issue #12558.
Example image:

Adjust daterange defaults

---

.github/workflows/docs.yml
.github/workflows/linkcheck.yml

The linkcheck is less and less reliable in past weeks. It seems that some of the sites are broken often, it might be also caused by them blocking GitHub ranges as such probing might be visible on some of them.
Separating the workflow allows us to execute it only on documentation changes (we still want to run regular documentation build on all pull requests to make it required).

feat(ci): separate linkcheck to standalone workflow

---

weblate/static/loader-bootstrap.js
weblate/static/styles/main.css
weblate/templates/paginator.html
weblate/templates/snippets/position-field.html
weblate/templates/trans/change_list.html

- Add second paginator to the top of changes page
- Fixed bug of inactive input when a second paginator is added.
Closes: #12601 
@nijel the main issue was the use of `id` selectors with more than one element (which is incorrect). Plus, ofc the logic for closing, hiding and focusing the input field in the paginator wasn't adapted for two paginators.
There are two paginators (one at the top, and one at the bottom) + the bug discovered in #6888 is fixed.

Add second paginator to the top of changes page

---

weblate/utils/search.py

It can be expensive to import due to building thousands of regexps at import time (see https://github.com/scrapinghub/dateparser/pull/1181).

feat(search): lazily import dateparser

---

docs/contributing/tests.rst

Add missing word in testing docs

---

weblate/trans/forms.py
weblate/trans/models/component.py
weblate/trans/tests/test_component.py

- This needs to be on the model to validate edits via API.
- Fix test to actually test for validation error.
- Remove not needed r prefix from some strings.

fix(component): move key_filter validation to the model

---

weblate/api/serializers.py
weblate/api/views.py
weblate/utils/stats.py

This allows better logic separation and makes it properly documented in OpenAPI.
See #12584

api: use serializer class for metrics

---

.github/workflows/test.yml
ci/apt-install
ci/pip-install

Expect failures right now as this will most likely unveil issues in the dependency chain.
Known issues:
* https://github.com/sirfz/tesserocr/pull/357
* https://github.com/grpc/grpc/issues/34922, https://github.com/grpc/grpc/pull/37643
* https://github.com/pydantic/jiter/issues/144 / https://github.com/pydantic/jiter/pull/145
* https://github.com/G-Research/ahocorasick_rs/issues/104 / https://github.com/G-Research/ahocorasick_rs/pull/105
* https://github.com/xmlsec/python-xmlsec/issues/327

feat(ci): add testing with Python 3.13

---

weblate/checks/base.py
weblate/trans/models/suggestion.py

There is a cache key collision between renders generated in checks for the unit and for its suggestions.
How to reproduce the collision:
1. Create a component with the max-size check
2. Create a unit in the source language and translate it in a target language
3. The render check (whether valid or incorrect) will display the render for the target string
4. Add a different suggestion to the same unit
5. The render check will display the render for the suggestion instead of the target string

Cache key collision in render checks for suggestions

---

weblate/trans/models/component.py

fix(component): avoid crash on getting unused enforcements

---

docs/changes.rst
weblate/trans/forms.py
weblate/trans/tests/test_create.py
weblate/trans/views/create.py
weblate/utils/views.py

A 'Target language" field is added to the `Translate document` form to identify and process bilingual files
fixes #11085

11085 bilingual file upload

---

weblate/addons/consistency.py
weblate/utils/apps.py
weblate/utils/checks.py
weblate/utils/classloader.py
weblate/utils/tests/test_checks.py
weblate/utils/tests/test_classloader.py

This adds a deploy check (`python manage.py check --deploy`) that will check all instances of ClassLoader and tries to load their data.
Fixes: #12135 
If loading fails, CheckMessage will be shown:
```
?: (weblate.E028) Module 'weblate.addons.consistency' does not define a 'LangauegConsistencyAddon' class in WEBLATE_ADDONS
HINT: https://docs.weblate.org/en/latest/admin/config.html
```
This also fixes a typo `LangaugeConsistencyAddon` to `LangaugeConsistencyAddon` with backward compatibility.

Add check for loading data to ClassLoader instances. Fixes: #12135

---

weblate/wladmin/models.py
weblate/wladmin/sites.py
weblate/wladmin/views.py

Fixes (7) mypy errors in wladmin module.
list of fixed errors
```
weblate/wladmin/models.py:333:9: error: Name "support_status" already defined on line 331  [no-redef]
weblate/wladmin/sites.py:41:28: error: Argument 1 of "each_context" is incompatible with supertype "AdminSite"; supertype defines the argument type as "HttpRequest"  [override]
weblate/wladmin/sites.py:41:28: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#incompatible-overrides
weblate/wladmin/sites.py:41:28: note: This violates the Liskov substitution principle
weblate/wladmin/views.py:326:18: error: Argument "key_type" to "get_key_data_raw" has incompatible type "str"; expected "Literal['rsa', 'ed25519']"  [arg-type]
weblate/wladmin/views.py:348:44: error: Argument "key_type" to "generate_ssh_key" has …
```

mypy: fix mypy errors in wladmin module. Rel: #3703

---

docs/changes.rst
weblate/checks/format.py
weblate/checks/same.py
weblate/checks/tests/test_format_checks.py

Relying on findall and finditer resulted in off by one for some of the matches causing false positives in some checks.
The code now consistely uses finiter which return re.Match objects and not a tuple matches as findall.
Fixes #12746

fix(checks): consolidate format string matching to use re.Match

---

weblate/accounts/models.py
weblate/utils/html.py
weblate/utils/tests/test_html.py

Some e-mail services such as Gmail automatically convert things that look like a link into links even in HTML mails. This could be problematic for audit log entries as want to display the information as is without turning that into links.
Adding `<span>` seems to help in this according to https://stackoverflow.com/a/23404042/225718

feat: quote audit log values to avoid auto linking

---

weblate/trans/models/unit.py

Since introduction of PermissionResult the has_perm gives exact reason why string can't be edited, so display it to the user instead of checking a single condition only.

feat(unit): show propagation failure reason from PermissionResult

---

docs/changes.rst
weblate/trans/autotranslate.py
weblate/trans/models/unit.py

The prefetch_bulk() and prefetch_full() do prefetch unit data, but not parent objects with assumption that these are typically called from translation.unit_set where such prefetch is not needed. But when it originates from Unit.objects, it needs to be added.

fix(unit): add some missing prefetch() calls

---

weblate/trans/discovery.py

Otherwise user gets an error which is hard to understand.

fix(discovery): disable edit_template if format does not support it

---

weblate/trans/forms.py

Prevent wrong submit of add new translation form when clicking on the special chars toolbar.
the toolbar consists of buttons which defaults to type submit when embedded inside a from, which is incorrect in this case.
closes: #12761

fix(forms): add missing "type" attribute to button element

---

docs/changes.rst
weblate/machinery/base.py
weblate/machinery/deepl.py

We do XML escaping when sending the content to the service, so we should unescape that when returnning back.

fix: forcibly apply cleanup to XML based machinery backends

---

docs/changes.rst
weblate/trans/models/change.py
weblate/trans/tests/test_reports.py
weblate/trans/views/reports.py

This add the field `username` when generating credits. Tests related to this change were also updated.
This solves issue #12800.

Add username in translator credits

---

pyproject.toml
scripts/set-version

This can cause tools to build project just to figure the version (see https://github.com/astral-sh/uv/issues/8771), what slows down things and pulls in not needed dependencies. We anyway inject the version into several places manually, so doing that in pyproject.toml as well is not a big deal.

chore: avoid using dynamic version in pyproject.toml

---

weblate/glossary/views.py
weblate/templates/snippets/glossary.html

Because of  add_glossary_term view handler that duplicates the term in the returned results. Plus bad returned html table template that breaks rendering when injected into the right side panel.
closes: #12624
closes: #12693
see the right side panel, (new term just h've been added, it isn't duplicated + rendered correctly). Also, UI persists after refresh.

Fix glossary term duplication bug

---

docs/changes.rst
weblate/machinery/base.py
weblate/machinery/tests.py

The fix in 07fe2cd was incomplete, it did not turn unescaping on for XML backends.
Fixes #12936

fix(machinery): really fix machinery XML unescaping

---

weblate/addons/forms.py
weblate/trans/forms.py

Correctly use project scoping when available, see #12957

chore(addons): fix bulk edit form construction

---

docs/changes.rst
weblate/static/editor/tools/search.js
weblate/trans/forms.py

Adds the same search preview from _Search and replace_ to the _Bulk edit_ tool.
Related to #4106, #4108 and #7563.
Does not affect the _Bulk edit_ add-on.

feat(tools): add search preview to bulk edit tool

---

weblate/templates/snippets/position-field.html
weblate/trans/views/edit.py

The user now can navigate a full section of strings (based on the nearby strings number in profile preferences)
close: #6393

feat: add navigation for string sections in translation interface

---

docs/api.rst
docs/changes.rst
weblate/api/serializers.py

This makes it easier to obtain lock state.

feat: expose component locked state in component API

---

weblate/utils/search.py
weblate/utils/tests/test_search.py

There is no reason to validate regex using Python engine when it won't be used to execute it.
Fixes #5322

fix: remove double search regex validation

---

docs/admin/continuous.rst

Split into three sub-sections for better clarity and giving more focus on areas where to address these.

docs: split out avoiding conflicts section

---

weblate/checks/models.py
weblate/checks/views.py
weblate/trans/tests/test_edit.py
weblate/trans/views/js.py

When check is no longer installed, Weblate can not get its object and processs it.
Fixes #13020

fix: gracefully handle uninstalled checks

---

weblate/trans/forms.py
weblate/trans/views/edit.py
weblate/utils/antispam.py
weblate/utils/tests/test_antispam.py

Allow future extension to services supporting checking multiple strings at once.

chore: refactor antispam API

---

weblate/trans/templatetags/translations.py

This avoids Django SafeString overhead and we don't use SafeString in these code paths. This drastically improves performance of rendering long strings.

chore: use html.escape directly

---

docs/changes.rst
weblate/formats/base.py
weblate/formats/ttkit.py
weblate/trans/models/translation.py
weblate/trans/tests/test_edit.py

This happens in XLIFF, but can happen in other formats using complex keys such as JSON.
Fixes #13213
Fixes WEBLATE-4HT
Fixes WEBLATE-479

fix(formats): gracefully handle when format changes key upon saving

---

pyproject.toml
uv.lock
weblate/accounts/models.py
weblate/accounts/tests/test_utils.py

Our username fields is more tolerant than e-mail address specification, so bring these in sync.
Fixes #13225

fix(accounts): sanitize usernames before generating private e-mail

---

weblate/trans/models/unit.py

The only user for this is currently the FillReadOnlyAddon which does not actually want to alter the original state so that the strings can be later unmarked as read-only.
Fixes #13248

fix: do not store read-only state as original

---

weblate/static/loader-bootstrap.js
weblate/static/style-dark.css
weblate/static/styles/main.css

Previously nbsp characters were treated as normal spaces which breaks line in the end of it.  The current changes prevent that behavior.
Close: #13073

Fix nbsp characters from breaking lines in highlight editor

---

weblate/machinery/tests.py
weblate/trans/templatetags/translations.py

Most of the strings contain text and HTML escapes and tags are sparse. So operating on the character level brings a lot of overhead. Instead of that we now calculation positions where we need to split the string and iterate only on these positions.
Built on top of https://github.com/WeblateOrg/weblate/pull/13285

chore: avoid iterating over individual characters while formatting

---

weblate/machinery/base.py
weblate/machinery/tests.py

When a glossary term is updated, the result cache is invalidated and new result is fetched.
- closes #13122

Invalidate automatic suggestion result cache on glossary change

---

weblate/templates/trans/alert/duplicatefilemask.html
weblate/trans/models/__init__.py
weblate/trans/models/alert.py
weblate/trans/models/component.py
weblate/trans/tests/test_alert.py

Reusing filemask does not have to be the only issue, the very same issue can happen when a signle file from one component is reused as source for other component.
This also avoids special-casing this single alert and it now uses generic alerts interface.
Fixes #13259

feat: extend DuplicateFilemask to operate on files

---

docs/changes.rst
weblate/auth/models.py
weblate/checks/flags.py
weblate/checks/parser.py
weblate/utils/forms.py
weblate/utils/search.py
weblate/utils/tests/test_search.py

The parser instances cannot be shared between threads as PyParsing is not thread-safe, see https://github.com/pyparsing/pyparsing/issues/89.
Fixes WEBLATE-1MFM

fix: use locks to prevent concurrent parsing

---

docs/changes.rst

Adjust the verb conjugation so that it matches the plural in "Android string resources" title.
Current rendered text in [Changes page](https://docs.weblate.org/en/latest/changes.html#weblate-5-8) is:
> [Android string resources](https://docs.weblate.org/en/latest/formats/android.html#aresource) now supports translatable attribute in its strings.

Fix verb to plural in changes.rst

---

docs/admin/install.rst

There is no longer a separate database that could be corrupt, it uses same database as Weblate.

docs: update outdated Celery beat documentation

---

docs/changes/v4.rst

Changes for 4.14.2 have the exact same sentence, but with dash in "duplicated-words". Due to this small difference, they are two very similar translation strings in Hosted Weblate. This PR is to deduplicate them.

Add dash to deduplicate translation string

---

weblate/accounts/notifications.py

This was ommitted for digest/non-user originated changes and some services like simplelogin.co tend to fill in the sender name from previous e-mail with the same sender making the notifcations look weirdly originated.

feat: always include From header in notification e-mails

---

weblate/templates/configuration/custom.css

When users are unauthenticated by default the theme is set to `auto` (which was before [this fix](https://github.com/meel-hd/weblate/commit/e93d765a802c2e2a12f60f255f09960b0ad4c7a6) **selects incorrect colors**). But when the user is logged in, the theme is set to his preference: `light` or `dark` instead of the auto theme.
The fix now selects the configured(dark/light) theme colors to match the sytem(dark/light) theme in `auto` theme. But only when the user is unauthenticated or he chose to.
Close: #13376

Fix colors to match system color scheme

---

weblate/api/authentication.py

- Fix an issue with the `rest_framework.authentication.TokenAuthentication` and the `weblate.api.authentication.BearerAuthentication` authentication classes when `drf-spectacular` generates the OpenAPI schema and warnings are issued in the log about duplication of the `tokenAuth` security scheme objects.
Fixes #13502.

fix(api): duplicate security scheme objs in openapi schema

---

weblate/auth/permissions.py

Rest of changes from #12449 after splitting out #13364 and #13363.

Permissions language reworked

---

docs/api.rst

Inspired by #12449 by @comradekingu

docs(api): add missing articles

---

docs/changes.rst
weblate/machinery/base.py

Since 63af651 the batch translating would use last cache key to store translations instead of using matching one. This commit keeps track of cache keys and stores translations in matching ones. Type annotations were also added.
Fixes #13388

fix(machinery): use matching cache key while caching translations

---

docs/changes.rst
weblate/checks/chars.py
weblate/checks/same.py
weblate/checks/tests/test_chars_checks.py

Strip markup before checking for punctuation spacing.
Fixes #6470

feat(checks): make punctuation spacing ignore markup

---

.github/workflows/rundev.yml
ci/run-test
docs/Makefile
docs/changes.rst
docs/contributing/start.rst
docs/contributing/tests.rst
pyproject.toml
rundev.sh
weblate/checks/tests/test_checks.py
weblate/formats/tests/test_convert.py
weblate/formats/tests/test_external.py
weblate/formats/tests/test_formats.py
weblate/formats/tests/test_multi.py
weblate/formats/tests/test_txt.py

We used custom logic to skip testing these, but using abstractclasses makes it possible at discovery time in pytest. Unfortunately this doesn't work in Django discovery, so this makes our testsuite pytest only.

feat(tests): utilize abstract classes for base tests

---

docs/changes.rst
weblate/api/views.py

- include field when it is known
- avoid building 400 responses manually

feat(api): use ValidationError with a field speficied when possible

---

docs/changes.rst
weblate/trans/autofixes/html.py
weblate/trans/tests/test_autofix.py

Once the check is ignored on the string, the cleanup should also not happen.
Fixes #13544

fix(autofix): make HTML cleanup honor ignore flag

---

docs/changes.rst
docs/user/checks.rst
pyproject.toml
uv.lock
weblate/checks/base.py
weblate/checks/markup.py
weblate/checks/models.py
weblate/checks/tests/test_markup_checks.py
weblate/settings_docker.py
weblate/settings_example.py

Use docutils to parse the string and show discovered errors.
Issue #8446

feat(checks): add reStructuredText syntax checking

---

weblate/trans/tests/test_hooks.py
weblate/trans/views/hooks.py

Replaces manual parsing of the SSH URL with the provided `path_with_namespace` from the GitLab payload. This ensures accurate retrieval of the repository's full name.
See https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html for example payloads from GitLab

fix(hooks): correct repository full_name extraction

---

docs/api.rst
docs/changes.rst
docs/conf.py
pyproject.toml
uv.lock
weblate/api/spectacular.py
weblate/api/tests.py
weblate/api/views.py
weblate/settings_docker.py
weblate/settings_example.py

This is companion to #13541 to make API error response more consistent. We now rely on drf-standardized-erros to do the processing. It also has drf-spectacular integration, so the error states are now documented in OpenAPI.

feat(api): standardize error responses

---

docs/wlc.rst

Apparenly the default APPDATA location has changed over the years so the documentation should adjust. Additionally wlc now supports LOCALAPPDATA.
Fixes https://github.com/WeblateOrg/wlc/issues/715

docs: update documentation on configuration locations

---

docs/changes.rst
weblate/machinery/deepl.py
weblate/machinery/tests.py

DeepL API Free tokens are suffixed with :fx, we can use this to automatically use matching endpoint.
See #13581

feat(machinery): automatically switch to free API for free api keys

---

weblate/trans/models/translation.py

This should make locking more straightforward to the server instead of locking each row individually.
Fixes WEBLATE-20ZY
Fixes WEBLATE-15BD
Fixes WEBLATE-2101
Fixes WEBLATE-1MKN
Issue #13626

fix(upload): select_for_update all translation units

---

weblate/templates/translation.html

There is no reason to show it when Plural option is not available.
Fixes #13663

fix(translate): remove spurious Singular input

---

weblate/lang/models.py
weblate/trans/models/unit.py
weblate/trans/tests/test_util.py
weblate/trans/util.py
weblate/trans/views/reports.py

chore(lang): move CJK detection to the language model

---

weblate/templates/translation.html
weblate/trans/templatetags/translations.py
weblate/utils/stats.py

The progress bar excludes failing check on translated strings, the percent shown next to it should match it.
Fixes #13669

fix: match displayed percent with progress bar

---

weblate/trans/backups.py
weblate/vcs/base.py
weblate/vcs/git.py

This can considerably reduce backup sizes for repos using squashing and rebasing.

feat: cleanup git repository before doing project backup

---

weblate/utils/apps.py

Avoid triggering weblate.E012 and weblate.E013 when e-mail sending is using dummy backend which actually does not send e-mails.

fix: do not check e-mail addresses of not sending out e-mail

---

weblate/trans/autotranslate.py
weblate/trans/forms.py

- add "Add as approved translation" choice to site-wide automatic translation add-on
- use translated state when approval is not available on the translation when performing automatic translation
Fixes #13766

fix(add-ons): allow selecting approved state on site-wide autotranslate

---

weblate/static/styles/main.css

Fixes mismatched border radii between the panel heading and its container. The issue is not particularly visible in the light theme but is noticeable in the dark theme.

Make .panel-heading match .panel border-radius

---

weblate/templates/accounts/profile.html

fix(profile): improve assorted profile strings

---

weblate/trans/models/alert.py
weblate/trans/models/translation.py
weblate/trans/tests/test_alert.py

The unit removal should affect DuplicateString alert. But as we don't parse all the files, the import alert itself is not triggered properly.
Fixes #13511

fix(alerts): adjust DuplicateString upon unit removal

---

weblate/addons/git.py
weblate/examples/git-merge-gettext-po
weblate/vcs/base.py
weblate/vcs/git.py

In regular merge it it useful to merge timestamps in the PO file, but this often causes issues in rebase (because the commits become different) or squash (because it can apply changes before they should be applied).
Fixes #13828

fix(git): avoid using custom merge driver in rebase or cherry-pick

---

weblate/addons/tests.py

tests: add another testcase for squashing

---

docs/changes.rst
weblate/checks/tests/test_consistency_checks.py
weblate/trans/models/unit.py

Due to a confusingly named variable the logic was inverted and the checks were not propagated on a strings change.
Fixes #13264

fix(unit): corrected check propagation

---

pyproject.toml
uv.lock
weblate/checks/placeholders.py
weblate/checks/tests/test_placeholders.py

This replaces all imports of the `re` regex module with [`regex`](https://pypi.org/project/regex/). This should be backward compatible with `re`, so just changing the import should be enough.
Some tests fail for as yet unknown reasons, as mentioned `regex `should be backward compatible with `re`, so some tweaks to the tests might be needed.
In the UI, all works as expected. You can use the following test regex check to validate.
```
regex:'^[-_\p{Ll}\p{Lo}\p{N}\p{sc=Deva}\p{sc=Thai}]{1,32}$'
```
Fixes #13728

feat: replace re module with regex

---

weblate/addons/management/commands/install_addon.py
weblate/machinery/models.py
weblate/memory/models.py
weblate/trans/management/commands/import_json.py

It is subclass of ValueError and available since Python 3.5.

chore: handle only JSONDecodeError from json.load(s)

---

docs/changes.rst
weblate/trans/views/files.py

This heavily reduces overhead when downloading huge project, category or project/language scopes.
Fixes WEBLATE-1BJP

fix(download): add missing prefetch when downloading multiple translations

---

weblate/static/styles/new-language.css

Fix language picker color when the user picks dark theme and his OS is in light theme the picker shows with a white bg.
Close: #13902

Fix language color picker color

---

weblate/trans/models/unit.py
weblate/trans/util.py

This is more effective as in some cases PostgreSQL messes up the join to take seconds. This also makes loading in the zen mode more effective, because secondary langauges are fetched just once.

fix(unit): reuse secondary language ids from profile

---

weblate/trans/models/project.py

Shared components are rare so optimize for case when they are not used and avoid using union query in that case.

fix: use union only when needed

---

weblate/addons/git.py

While we want to deliver the events per component, the squashing needs to happen per repository to see all the translations.
Fixes #13969

fix(add-ons): corrected squash add-on behavior on linked repos

---

docs/changes.rst
docs/user/search.rst
weblate/utils/search.py
weblate/utils/tests/test_search.py

The implicit operator would have been overriden by an explicit one when both are used in a single query.
See #13978

fix(search): corrected behavior of the implicit AND operator

---

weblate/trans/views/basic.py

The ghost entries make most sense when there is just a few results which can be skimmed visually. This is definitely not the case when pagination is used for the results.

fix: do not show ghosts when paginating results

---

docs/changes.rst
weblate/trans/backups.py
weblate/trans/tests/test_backups.py
weblate/vcs/base.py

After `git gc` the .git/refs/ directories might be empty what causes their ommision from the backup (the zip file includes files, not directories). Upon restoring that blank directory needs to be recreated, otherwise Git does not recognize the directory as a checkout.
Also limit Git traversing outside data dir as that has actually hidden this error for our testsuite as it made it operate on Weblate in CI environment instead of the data.
Fixes WEBLATE-28N0
Fixes WEBLATE-28N2
Fixes WEBLATE-28MC

fix(backups): correctly restore repos without refs

---

docs/admin/auth.rst
docs/admin/config.rst
docs/admin/install/docker.rst
docs/changes.rst
pyproject.toml
uv.lock
weblate/accounts/forms.py
weblate/accounts/models.py
weblate/accounts/password_validation.py
weblate/settings_docker.py
weblate/settings_example.py

While we haven't seen any issues with longer passwords, the 72 is the maximal length recommended by zxcvbn-python. Because of unhandled error longer passwords lead to crash.
Also add a length validator that shows this limit visibly to the user.
django-zxcvbn-password is no longer maitained, so better switch to a maintained alternative.

Update password validation

---

weblate/trans/tests/test_sort.py
weblate/trans/util.py

fix(utils): use strxfrm only if it works
Fixes #14019
Built on top of #14023

fix(utils): use strxfrm only if it works

---

weblate/static/styles/main.css

If it overlaps it will be scrollable in boundry.

Fix history events overlay in the editor

---

docs/changes.rst
weblate/api/views.py
weblate/trans/views/files.py

fix: prefetch metadata when downloading

---

weblate/api/spectacular.py
weblate/api/views.py

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/).
- [GroupViewSet]: Unable to derive type of path parameter "language_code" because model "weblate.auth.models.Group" contained no such field.
- [ComponentViewSet]: Unable to derive type of path parameter "project_slug" because model "weblate.trans.models.component.Component" contained no such field.
- [ComponentListViewSet]: Unable to derive type of path parameter "component_slug" because model "weblate.trans.models.componentlist.ComponentList" contained no such field.
- Annotated non-existent method on TasksViewSet.
- [TasksViewSet]: Unable to guess serializer.
- [Search]: Unable to guess serializer.
---
The purpose of this PR is to fix most the remaining error and warning log messages which are issued when a …

fix(api): various small fixes for schema generation

---

weblate/lang/views.py
weblate/templates/language.html

The pagination object was shadowed by a list of ProjectLanguage instances.
Fixes #14100

fix(lang): show pagination controls on language page

---

weblate/trans/models/component.py
weblate/trans/models/unit.py
weblate/trans/views/edit.py

- reuses defer logic from the component
- reuses source_translation from the source unit
- merging this in the Python seems better than doing too complex query
Fixes WEBLATE-20ZA

fix: use prefetch to get other units

---

weblate/machinery/base.py
weblate/machinery/weblatetm.py

This allows to use short cache expiry for Weblate backend to avoid hitting database too often with expensive queries.

feat(machinery): make cache expiry overridable per backend

---

weblate/metrics/models.py
weblate/metrics/wrapper.py

Since the database is now sparse, it does not contain past entries for newly created objects.
Fixes WEBLATE-23QS
Fixes WEBLATE-9N8

fix(metrics): lazily calculate only todays metrics

---

weblate/trans/tests/test_selenium.py

Chromium 134 seem to broke Selenium and it throws WebDriverException when element is about to get stale. This catches the error and retries the operation after a short delay.
See https://github.com/SeleniumHQ/selenium/issues/15401

fix(test): workaround crash in Selenium tests

---

weblate/trans/tests/test_edit.py

I was hoping this is the cause for #14189, but the test is useful even if it is not.

tests: add test for sync/resync while editing

---

weblate/trans/tests/test_models.py

Ordering of the units is not defined, so .all()[0] returns a random unit. When it ends up to be one with plurals, the logic fails.
Fixes #13904

fix(tests): use the same unit instead of getting random one

---

pyproject.toml

When building the weblate package, there are several "Package would be ignored" errors. See https://github.com/WeblateOrg/weblate/issues/12778 for details.
These errors stem from the fact that any directory even if it doesn't contain python files can be imported in a python file as a namespace package. The template and local directories included in the weblate build as package data qualify as namespace packages. However, since find_namespace_packages was set to false setuptools wouldn't consider it as importable package leading to an inconsistent configuration.
To fix this issue, set find_namespace_packages to true in pyproject.toml. Since weblate is a "flat layout", the include directive is also needed to exclude other top level directories from being included in the final package.
To …

setuptools: use find_namespace_packages

---

weblate/trans/tasks.py

This avoids repeated querying of pending units on components that have none.
Fixes WEBLATE-SQ

fix: check pending changes only on components that have one

---

weblate/lang/models.py
weblate/lang/tests.py

Getting by name is the most fuzzy option as there are confusing language names (Dan language mathes ISO 639-2 code for Danish).
Fixes #14238

fix(lang): prioritize handling aliases before getting by name

---

docs/api.rst
docs/changes.rst
weblate/api/tests.py
weblate/api/views.py

Added a translations action to UnitViewSet to retrieve all target source units for a given source unit. A 400 error is returned if the specified unit is not a source unit.
Fixes #13186

Add an api to get all string translations

---

weblate/api/views.py

It might be diverted to memory_db replica using a custom router and it won't work for delete queries as it is read-only.

fix(api): use default database connection for memory

---

weblate/static/styles/main.css

Fix overflow of long unspaced glossary terms

---

weblate/accounts/templatetags/site_url.py
weblate/accounts/tests/test_templatetags.py
weblate/templates/mail/base.html
weblate/templates/mail/style.css

The add_site_url filter was adding another level of HTML structure.

fix(notifications): avoid generating HTML with two body elements

---

weblate/accounts/models.py
weblate/settings_docker.py
weblate/settings_example.py

Just noticed that when Weblate runs with `REQUIRE_LOGIN`, requests for the manifest fail because they are made without credentials.

Add `site.webmanifest` to `LOGIN_REQUIRED_URLS_EXCEPTIONS` list

---

docs/changes.rst
weblate/accounts/forms.py
weblate/trans/models/translation.py

Pass naive datetime to altcha as it breaks when timezones are involved.
Fixes #14132

fix(captcha): altcha verification does not deal with timezones

---

docs/changes.rst
weblate/checks/base.py
weblate/checks/consistency.py
weblate/trans/models/unit.py
weblate/trans/tests/test_remote.py

- do not perform a full prefetch, that is not really needed, this might address #14274
- filter out matching translations at the database level
- rename property to propagated_units to better match the content

fix: improve translation propagation performance

---

docs/changes.rst
docs/user/checks.rst
weblate/checks/format.py
weblate/checks/models.py
weblate/checks/tests/test_format_checks.py
weblate/settings_docker.py
weblate/settings_example.py

Add an AutomatticComponentsCheckTest to ensure placeholders in automattic components are consistent between source and translation units.
Fixes #13634.

feat(checks): automattic components check

---

docs/changes.rst
weblate/checks/models.py
weblate/trans/views/js.py

- The check dismissal now selects for update to better deal with concurrent updates from concurrent clicks.
- The dismissal is propagate to all same checks on propagated units.
Fixes #12588
Fixes WEBLATE-1N8E

feat(checks): dismissing follows to propagated strings

---

weblate/addons/base.py

The project-wide add-ons should be triggered only on compatbile components. The execution path already does this, but postconfigure was not.
Fixes WEBLATE-1V8Y

fix(add-ons): trigger posinstall only on compatible components

---

weblate/trans/models/project.py
weblate/trans/views/edit.py
weblate/utils/stats.py

There is no need to use union when the base queryset is the same, it is more effective to merge two querysets with or and Django ORM will handle that as a single query.

fix(models): avoid using union when not needed

---

weblate/auth/models.py

The compatibility layer introduced in #13640 doesn't gracefully handle when defaults are not passed and leads to crash.
Fixes #14434

fix(auth): avoid crash when get_or_create is not passed with defaults

---

docs/changes.rst
weblate/trans/models/component.py
weblate/trans/models/project.py
weblate/trans/models/translation.py

Without that the create_translations might be executed before the transaction is committed and operates on stale data. This was not issue before 966378a0bbfb92fc748c911f24d22fbf00d8ff56 where there was a 60 seconds delay which gave the transaction enough time to complete.
Fixes #14401

fix(component): trigger background task on transaction commit

---

docs/changes.rst
weblate/machinery/cyrtranslit.py
weblate/machinery/tests.py

It automatically picks matching translation to use. This allows to use the engine even if the source language is English.
Fixes #13769

feat(machinery): automatically choose source language for cyrtranslit

---

weblate/static/editor/base.js

- Prevent unsaved changes dialog on **submit** of changes.
- Add unsaved changes indicator only to translation editor (it showed also in `add term to glossary` inputs).
close: #14530

fix(editor): improve unsaved changes indication and reset on submit

---

weblate/trans/checklists.py
weblate/trans/models/translation.py

- show unlabeled category only with labeled strings
- show strings without suggestions only when there are some
It is not useful to show only one side of the checklist when the
positive counterpart is missing.
Fixes #14567

fix(translation): hide some checklist items without counterpart

---

weblate/trans/backups.py
weblate/trans/tests/test_backups.py

Include categories in project backups.
Fixes #13743.
Depends on https://github.com/WeblateOrg/weblate_schemas/pull/426.

feat: backup categories

---

weblate/templates/translate.html
weblate/trans/tests/test_edit.py
weblate/trans/views/edit.py

When a unit is deleted, go to the next unit in the batch instead of going back to the component overview page.
fixes #14558

feat: deleting a unit goes to next entry in batch

---

docs/changes.rst
weblate/templates/dashboard/user.html
weblate/trans/templatetags/translations.py
weblate/utils/views.py

Use full path instead of just a component name. This gives consistent behavior with the client side ordering. It is now based on the breadcrumbs code which was generalized a bit to make it more effective.
Fixes #14476

fix: corrected server side ordering of translations

---

docs/api.rst
docs/changes.rst
weblate/api/serializers.py
weblate/api/tests.py
weblate/api/views.py
weblate/trans/models/comment.py
weblate/trans/tests/test_tasks.py
weblate/trans/views/edit.py

Add `/api/units/{unit_id}/comments/` endpoint to create comments.
Fixes #14232

feat: add comment api

---

weblate/lang/views.py
weblate/templates/snippets/sort-field.html
weblate/trans/forms.py
weblate/trans/models/unit.py
weblate/trans/views/basic.py
weblate/trans/views/dashboard.py
weblate/trans/views/edit.py
weblate/trans/views/search.py
weblate/utils/views.py

Add sort choice to sort by component and unit priority to avoid unnecessary jumping between contexts. The units are sorted by the component in the same order as components are sorted in a project/category.
Further, move the sort name and sort query to the SearchForm from the views to ensure consistent sort defaults on all pages.
Also fix a bug in zen mode when changing the sort in zen mode results in a blank page.
#14296

feat: sort units by component when translating multiple components

---

weblate/formats/ttkit.py

There is no need to shadow using stdlib by importing these from translate-toolkit.

chore: avoid importing stdlib modules from third-party

---

docs/changes.rst
weblate/checks/consistency.py

The content changes cover explanation or flags which are not really relevant when looking for a previous translation.
Fixes #14846
Fixes #14847

fix(checks): has been translated should look only at translation changes

---

weblate/addons/tasks.py
weblate/addons/tests.py
weblate/glossary/tasks.py
weblate/trans/models/component.py
weblate/trans/models/translation.py
weblate/trans/tasks.py
weblate/trans/tests/test_edit.py
weblate/trans/tests/test_views.py
weblate/trans/views/basic.py

Historically there was `create_translations` which decided whether to make the processing immediate or in a task based on the configuration and parameter. Remove that parameter and make it always use background processing if available. Also renames the immediate processing method to make it clear what it does and use it where sync behavior is needed.

chore: cleanup translation create interface

---

weblate/fonts/utils.py

Not sure if this actually fixes a issue, but for completeness' sake I think it should be passed to `_render_size()`.

fix(fonts): pass font weight for size rendering

---

weblate/accounts/views.py

Describe the problem:
Currently, the SAML integration appends an `authid` query parameter to the Assertion Consumer Service (ACS) URL to restore the session after SAML authentication. Many SAML Identity Providers (IdP) require the ACS URL to match exactly, and the extra parameter causes authentication to fail with errors such as:
```
Invalid request, ACS Url in request ... doesn't match configured ACS Url ...
```
This strict matching breaks SAML login for platforms that do not allow query parameters in the ACS URL.
Solution brainstorm:
The session restoration mechanism should use the SAML RelayState parameter for passing `authid` or similar session data instead of appending it to the ACS URL as a query parameter. The SAML RelayState is designed for this purpose and is returned unmodified …

fix: do not send authid parameter in saml backend

---

weblate/trans/forms.py
weblate/trans/tests/test_comment.py
weblate/trans/views/edit.py
weblate/utils/forms.py

The browsers count newline as a single character, but post it as \r\n making Django count it as two characters. This makes it reject strings which are okay for the browser. Normalizing newlines makes it behave consistently.
Fixes #14952

fix(comments): normalize newlines before validating comment text

---

weblate/static/styles/main.css

Changes the older non-standard `word-wrap` to `overflow-wrap` and uses the `anywhere` value to wrap more aggressively in case of very long words.
Fixes #14956

fix(history): wrap long content in history

---

docs/api.rst
docs/changes.rst
weblate/api/serializers.py
weblate/api/tests.py

This makes the the users [translated languages](https://docs.weblate.org/en/latest/user/profile.html#translated-languages) selection available via API.
I would like to have this data available to be able to automatically create a overview table of who translates which language on our private instance.

feat(api): show translation languages of user

---

weblate/settings_docker.py
weblate/settings_example.py

Relax SameSite flag to allow including the language cookie with cross site POST requests. This will allow user to see error messages in the selected language.

fix: relax language cookie policy

---

docs/admin/install/docker.rst

This PR solves the next warning when running `docker compose up` when following the installation steps 2 and 3 from https://docs.weblate.org/en/latest/admin/install/docker.html#installation
```sh
WARN[0000] weblate-docker/docker-compose.override.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```
1. in `main` branch, follow step 2 and 3 of the installation doc
2. you should see the warning described above
3. run `ctrl+c` to stop the process
4. switch to this branch and run `docker compose up` or some `docker compose` command
5. you should not see the warning anymore

docs(installation): remove obsolete version

---

weblate/trans/views/edit.py

Fixes https://github.com/WeblateOrg/weblate/issues/14798
When translating on category or project level, make user aware if the component of unit changes.

Show message when moving between components while translating 

---

weblate/static/editor/base.js
weblate/static/editor/full.js

This adds a button "Accept and approve" to the machinery table when the review workflow is enabled.
Fixes #15115

feat(editor): add accept and approve button when review workflow is enabled

---

weblate/trans/autotranslate.py
weblate/trans/bulk.py

The locking should not be needed here as we use select_for_update and the pending changes no longer trigger commit since #15070.
Issue #13623

fix: remove component locking form autotranslate and bulk edit

---

weblate/static/editor/zen.js

Fixes:
- Stop save triggered when clicking source text or inserting placeholders.
- Cancel save operation after (1000ms) quick refocus
- Reduce possibility of multiple validation popups showing in the UI because of unintended saves
Close: #3410

Refactor translation editor save logic to improve focus handling and save timing

---

weblate/trans/tasks.py

The locking was removed for the translation level autotranslate so it can be done here as well.
Fixes WEBLATE-2ZV1
Issue #13623

fix(autotranslate): do not lock component for autotranslate

---

weblate/accounts/avatar.py
weblate/static/styles/main.css
weblate/templates/snippets/info-users.html
weblate/templates/snippets/info.html
weblate/trans/models/project.py

- cache the results to avoid double evaluation of the query
- exclude bots from admin and review accounts
- share the rendering template with admins
- show the number of users in the group
- limit listing to first 25 users
- add CSS to make sure there is spacing around the users
- lazily load user avatars
Fixes #15304

fix: improve listing of project reviewers

---

weblate/trans/models/translation.py
weblate/trans/tests/test_models.py

`update_units` returned an empty list in case no units are updated, but it should always return the changes_status dict.
Fixes #15318

bugfix(pending-units): KeyError if no units updated

---

weblate/trans/models/unit.py
weblate/trans/tests/test_models.py

No translation file exists for source strings in bilingual formats, hence we should not try to commit explanation changes for the same to a file. Do not create a PendingUnitChange entry is a source unit and the file format is bilingual.
Fixes #15344.

bugfix(pending-unit): source string explanation commit to file

---

docs/admin/addons.rst

Component discovery doesn't work if a base file exists but there are no translations (https://github.com/WeblateOrg/weblate/issues/2084).
Document this requirement as a warning.
While I'm here, add a hint that recommends pairing with the "Add missing languages" add-on to ensure that newly discovered components converge on a consistent set of languages.

docs: Note component discovery requirement for at least one translation

---

docs/changes.rst
weblate/machinery/deepl.py
weblate/machinery/tests.py

The codes for the source language differ from target ones as DeepL does not support country suffixes here.
Fixes #15432

fix(machinery): correctly map source languages for DeepL

---

weblate/api/tests.py
weblate/api/views.py

When user is both member and admin, the outer join can list it multiple times.
Fixes WEBLATE-31J7
Fixes WEBLATE-31HT

fix(api): avoid listing duplicate groups

---

docs/specs/openapi.yaml
docs/specs/sbom/partial/python.json
docs/specs/sbom/sbom.json
docs/specs/schemas/weblate-memory.schema.json
docs/specs/schemas/weblate-messaging.schema.json
pyproject.toml
uv.lock

In order for the recent changes in the package `weblate_schemas` to be utilized, its version in dependencies list must be changed to v2025.5.

Update the dependecy weblate-schemas to v2025.5

---

weblate/trans/models/translation.py
weblate/trans/tests/test_models.py

Avoid breaking groups when the same author makes multiple changes to a single unit.
Fixes #15430

bugfix(commit groups): avoid unnecessary group breaking

---

weblate/accounts/views.py
weblate/templates/accounts/login.html

In most cases there is single auth method and Weblate redirects, but in case more of them are configured, the login page is shown and shows form for disabled password authentication as well.

fix(login): do not show login form when not configured

---

weblate/lang/models.py

The browser uses lowercase BCP codes (pt-br) while Weblate uses mixed cases POSIX codes (pt_BR) so we need to convert them to gracefully map these.
Fixes #15507

fix(lang): improved user language detection from browser preferences

---

weblate/trans/util.py

In previous macOS 15 releases it crashed with OSError, with current macOS 15 release it seems to silently corrupt memory leading to segmentation fault after several executions.
Fixes #14645

fix(utils): avoid using strxfrm on macOS 15

---

weblate/templates/base.html

I think this better structures the menu items making it easier to navigate. Also hides the donate link for sites with purchased support.
After:
Before:

feat: use headers in the support menu

---

docs/admin/install/docker.rst
weblate/settings_docker.py

Adds support for REDIS_USER env variable as per #15674 
No automatic tests exist for `settings_docker.py`, so I tested this manually to ensure that keeping REDIS_USER blank will not change current behaviour.

Add REDIS_USER env variable

---

weblate/glossary/tests.py
weblate/trans/models/translation.py

As the stats are not updated during individual units sync, it needs to be updated after all work has been done.
Fixes #15704

fix(glossary): update stats after glossary sync

---

weblate/trans/models/component.py
weblate/trans/models/translation.py

When a change cannot be committed, do not trigger optional push.
Otherwise we end up in an infinite recursion Component.do_update -> Component.commit_pending -> Component.push_if_needed -> Component.do_push -> Component.do_update
Issue #15691
I think this answers why an attempt to commit in #15691 happens so often. Still, we need a solution to make the failed commit less noisy.

fix(component): avoid push if needed for not commited changes

---

weblate/formats/convert.py
weblate/formats/exporters.py
weblate/formats/tests/test_formats.py
weblate/formats/ttkit.py

Weblate relies it for many features and shadowing it behind translate.storage.po make this non-transparent, especially to type checkers.

chore(formats): directly use pypo implementation for gettext PO

---

weblate/trans/forms.py

It was rendered with the readonly attribute, but it doesn't work for checkboxes in HTML, only for inputs.
Fixes #15685

fix(translate): hide needs editing checkbox on read-only strings

---

docs/changes.rst

- The changelog entries for #15416 were incorrectly added under Weblate 5.12 paragraph , this PR fixes that by moving them to the correct paragraph

docs: Move misplaced changelog entries to correct Weblate versions

---

weblate/trans/bulk.py
weblate/trans/models/component.py

This is way more effective than doing it later. Also filters out strings without backing file which cannot be edited.

fix(bulk-edit): filter out strings at the database level

---

docs/changes.rst
weblate/machinery/libretranslate.py
weblate/machinery/tests.py

LibreTranslate now uses ISO codes instead of model ones, so the logic needs to be adjusted.
Fixes #15967

fix(machinery): LibreTranslate 1.7.0 compatiblity

---

weblate/addons/models.py
weblate/addons/tests.py
weblate/addons/views.py
weblate/templates/addons/addon_list.html

This can be result of broken migration as seen in #15983 or user disabling the add-on.

fix(add-ons): avoid crash when listing unknown add-ons

---

docs/admin/config.rst
docs/changes.rst
weblate/accounts/forms.py
weblate/accounts/middleware.py
weblate/accounts/pipeline.py
weblate/accounts/utils.py
weblate/auth/models.py
weblate/settings_docker.py
weblate/settings_example.py

The 2fa should have a short session expiry as this is expected to happen interactively. Previously 2fa input got the session expiry for authenticated users what was wrong.

fix(auth): shorten session expiry while in 2fa

---

docs/changes.rst
weblate/api/renderers.py

This fixes the format of OpenMetrics in the endpoint `/api/metrics/?format=openmetrics`. The error is caused by using parenthesis instead of curly brackets in specifying labels. 
This fixes issue #15689.
A screenshot of a successful target scrape in Prometheus after the fix:

fix: OpenMetrics format parse issue

---

docs/admin/auth.rst

Apparently Okta doesn't do this by default, so mention it in the documentation.

docs(auth): clarify that RelayState needs to be passed

---

weblate/static/loader-bootstrap.js

Check data-details-url to hide the screenshot-details button for non-screenshot images.
This allows to use the thumbnail feature to be used for non-screenshot images.

Hide screenshot modal details link when no URL is available

---

docs/admin/machine.rst

The URL will no longer work in near future and it is no longer important to describe this to the users (it was merely a migration documentation when Weblate category changed at DeepL), so let's remove it.

docs: remove deprecated DeepL usage

---

docs/admin/access.rst
docs/changes.rst
weblate/api/views.py
weblate/auth/permissions.py
weblate/auth/tests/test_views.py
weblate/auth/views.py
weblate/templates/project.html
weblate/trans/views/basic.py

It was possible to change team properties by the team admins, but the desired behavior was only to change team members. This also changes the admin view visibility, it is now added to the project menu.
Fixes #16186

fix: make team admins behave as documented

---

weblate/utils/search.py

These are typically not needed outside the request, so reduce cache size.
We still want caching inside single request as the query can be parsed multiple times. With multithreaded workers, we still want some buffer to keep parsed result.

fix: reduce search query parser cache

---

docs/admin/access.rst

Just a very small change to make it clear that there can be multiple team administrators.

docs: clarify that there can be multiple team administrators

---

weblate/trans/models/component.py
weblate/utils/stats.py

We are not going to need the queryset again, so utilize iterator to fetch all stats to update.

fix(stats): utilize iterators to avoid Django caching

---

docs/changes.rst
weblate/formats/tests/test_formats.py
weblate/trans/models/component.py
weblate/trans/tests/test_file_format_params.py

- fixes #16269
File format parameters were not correctly passed down when adding a new language, which resulted in inconsistent file formatting on (at least) the 1st commit of the new translation.
However, the behavior observed is the opposite of what is described in the issue (i.e empty tags were self closing instead of having a separate closing tag), so I am not entirely sure if this effectively fixes it.

fix(file-formats) ts2 formatting fix

---

docs/specs/openapi.yaml
weblate/api/serializers.py
weblate/api/tests.py

This was implemented some time ago, but was missing in the serializer so it could not be actually triggered.

fix(api): expose file-sync and file-scan in serializer

---

weblate/addons/tests.py
weblate/addons/views.py

It was not tracked when add-on didn't have a configuration.

fix(add-ons): corectly track user when adding add-on
